### ISSUE TITLE
Problem using Rancher Desktop for users with wsl 1 on Windows 

### ISSUE THREAD

**Issue by cinnamon-coder-hub** [devonfw/ide#1001]
While setting up rancher desktop on windows computers, cases occured in which the rancher-desktop launcher failed with an rather cryptic error output. If I remember it correctly, those cases included the error code 4294967295. Some solutions relating to this error code are given on [stackexchange](https://stackoverflow.com/questions/70953842/error-wsl-exe-exited-with-code-4294967295-on-installing-rancher-desktop).

### Expected behavior

No error code should be thrown out by the rancher-desktop launcher.

### Affected version:

OS: Windows

### Solution
The problem lies in the usage of wsl 1 instead of wsl 2, but can also relate to disabled virtualization (see comment following)
Suggested steps for solving the bug: 

- Recognize that wsl 1 is used
- If so, execute `wsl --update` as admin
- Only start the installation of rancher desktop after these steps

**Comment by cinnamon-coder-hub** [comment]
### Way to reproduce the error code 4294967295
For the record, I could reproduce the error code with the rancher-desktop launcher by disabling virtualization in my computers BIOS (simply switching from wsl 2 to wsl 1 from powershell wasn't enough). 
![34f33964-dd92-46b9-8152-16aecb255c5c](https://user-images.githubusercontent.com/91025735/206416608-3811fca6-648b-4507-917f-5e063fd1c26b.jpg)

The comment of the rancher-desktop launcher, at least in my case, seems quite appropriate, though. Maybe this was modified recently or there may be other ways of getting this error code, but maybe it is better to not not get lost in these details. I'll try to figure out a robust way of testing for wsl 1 etc. instead.

**Comment by cinnamon-coder-hub** [comment]
Today I included a test for if the user has enabled version 1 of wsl. 
It would be nice to have some additional testing, especially as this modification is rather small. 
There was a problem with redirecting the cmd output. 
Therefore I wrote the batch file and the version number into temp-files,
but I'm open to better suggestions that work.

**Comment by hohwille** [comment]
Oh, Microsoft heard our [plea](https://github.com/devonfw/IDEasy/blob/main/documentation/tool-vendor-plea.adoc)
```
$ wsl -v -l
WSL-Version: 2.0.14.0
Kernelversion: 5.15.133.1-1
WSLg-Version: 1.0.59
MSRDC-Version: 1.2.4677
Direct3D-Version: 1.611.1-81528511
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows-Version: 10.0.19045.4412
```
Seems that some windows or WSL update brought this new behavior.
Not sure if this is all still relevant.
Maybe computers with WSL1 are dying out meanwhile and can only be found in museums.
So maybe we can also close this issue as not planned.
