### ISSUE TITLE
Proper error message if bash is not found

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#1005]
In our [setup](https://github.com/devonfw/ide/blob/master/documentation/setup.asciidoc) we have described that we need `git` installed as a pre-requesite. On windows this means git-for-windows that includes git-bash.
However, our user-base is growing and we happen to have users that do not read this properly.
As a result the users get strange errors with not very helpful messages like this:
```
""\bin\bash.exe"" kann syntaktisch an dieser Stelle nicht verarbeitet werden.
```

Bash detection starts here:
https://github.com/devonfw/ide/blob/d867f9a956b0eddc2c01f9b3a0e494edbf12e2ba/scripts/src/main/resources/scripts/devon.bat#L61

IMHO falling back to `cygwin` or whatever is rather pointless.
For KISS we could simply fail if we do not find `git-bash` with a proper error message if git[-bash] was not found like this:
```
ERROR: Could not find bash. It seems git for windows is not installed on your machine (GIT_HOME=)
Please download and install git for windows from the following URL and after that rerun devonfw-ide setup:
https://git-scm.com/download/win
```

**Comment by hohwille** [comment]
Cool, there also is an actual bug in the current code:
https://github.com/devonfw/ide/blob/d867f9a956b0eddc2c01f9b3a0e494edbf12e2ba/scripts/src/main/resources/scripts/devon.bat#L78

Note that in this line unlike the others it says `exists` instead of `exist` so most likely this evaluates to true for some reason and so the actual error message never shows:
https://github.com/devonfw/ide/blob/d867f9a956b0eddc2c01f9b3a0e494edbf12e2ba/scripts/src/main/resources/scripts/devon.bat#L85

**Comment by mustafaokyay** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IDE-61dbfc20045ead0022812582/issues/devonfw/ide/1005?planning-poker) with Zenhub @alfeilex @Amueller36 @cinnamon-coder-hub @CREITZ25 @hohwille @tobka777 @Ttring
