### ISSUE TITLE
Unable to update java software only

### ISSUE THREAD

**Issue by maybeec** [devonfw/ide#1024]
### Expected behavior

As a user, I want to update my java version by `devon ide update java` so that I can update java without running an update of all my software.

### Actual behavior

```
$ devon ide update java

******** ATTENTION ********
Undefined package java
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

. Running  `devon ide update java`

### Affected version:

* OS: Windows
* Console: Git Bash

**Comment by hohwille** [comment]
To do what you are intending to do there is already a solution:
```
devon «tool» setup 
```

So in your case `devon java setup`.
Sorry if the CLI is not most intuitive. When I made this up, I did a survey on Yammer but nobody participated ;)

**Comment by hohwille** [comment]
I hope this helps you do address what you need. IMHO there is nothing to do.

**Comment by maybeec** [comment]
Let me check, maybe I had the case that I installed Java transitively by eclipse and thus got the error although Java was already available. Need to check
