### ISSUE TITLE
Cannot update java

### ISSUE THREAD

**Issue by maybeec** [devonfw/ide#1025]
### Expected behavior

As a admin, I want to update java so that I can work with a different version from now on.

### Actual behavior

```
$ devon ide update all

*** Software Update of devonfw-ide-scripts ***
Updating /d/cobigen from https://repo.maven.apache.org/maven2/com/devonfw/tools/ide/devonfw-ide-scripts
Trying to determine the latest available version from https://repo.maven.apache.org/maven2/com/devonfw/tools/ide/devonfw-ide-scripts/maven-metadata.xml
The devonfw-ide-scripts package is already at the correct version 2022.12.001

*** Setting up eclipse ***
Updating java from version 19_36 to version 11.0.17_8...
Success: run command mkdir
Starting installation of java in version 11.0.17_8 to /d/cobigen/software/java
Trying to download java-11.0.17_8-windows.zip from https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.17%2B8/OpenJDK11U-jdk_x64_windows_hotspot_11.0.17_8.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Failed to download https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.17%2B8/OpenJDK11U-jdk_x64_windows_hotspot_11.0.17_8.zip with exit code 22
Trying to download java-11.0.17_8-windows.zip from https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.17%2B8/OpenJDK11U-jdk_x64_windows_hotspot_11.0.17_8.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 61  188M   61  115M    0     0  5385k      0  0:00:35  0:00:21  0:00:14 5508k
100  188M  100  188M    0     0  5432k      0  0:00:35  0:00:35 --:--:-- 5512k
Download of java-11.0.17_8-windows.zip from https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.17%2B8/OpenJDK11U-jdk_x64_windows_hotspot_11.0.17_8.zip succeeded.
Success: run command unzip
Successfully extracted archive java-11.0.17_8-windows.zip to /d/cobigen/updates/extracted/java
Creating backup by moving existing /d/cobigen/software/java to /d/cobigen/updates/backups/22-12-19
mv: cannot move '/d/cobigen/software/java' to '/d/cobigen/updates/backups/22-12-19/java': Permission denied

******** ATTENTION ********
Failed to move /d/cobigen/software/java to /d/cobigen/updates/backups/22-12-19.
Most probably this is a problem of windows file locks. In such case please terminate all processes locking the files and retry the operation.
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Command 'java setup silent' failed with exit code 255

******** ATTENTION ********
Failed to run devon java setup silent
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 255
Command 'eclipse setup' failed with exit code 255

******** ATTENTION ********
Failed to run devon eclipse setup
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 255
```

Critical line: `mv: cannot move '/d/cobigen/software/java' to '/d/cobigen/updates/backups/22-12-19/java': Permission denied`

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Setup new devon-ide with default settings
2. Change `conf/settings/devon.properties` and add new line specifying another java version `JAVA_VERSION=11.0.17_8`
3. Run `devon ide update all` as `devon ide update java` does not work (#1024)

### Affected version:

* OS: Windows
* Console: Git Bash

**Comment by hohwille** [comment]
Sorry, but you have to ask Microsoft to stop locking every file in use. There is pretty much nothing we can do about this.
You have to stop your java based processes (Eclipse, maven, IntelliJ, etc.) before updating.

Best we could try to do is detect and handle this specific error and give the user more details how to proceed - e.g. open a documentation in the browser (asciidoc on github) explaining how to check for file locks and stop processes, etc.

**Comment by maybeec** [comment]
I am pretty sure I closed everything because I was able to manually delete the java folder and run the script again.
Nonetheless, I agree, possibly I have overseen something and if this cannot be reproduced, than let's close it.

**Comment by hohwille** [comment]
We will at least add something to the documentation. There are also windows tools like https://www.iobit.com/en/iobit-unlocker.php that we can recommend from the documentation for those who like it.
If the `mv` command fails during the installation on windows we could print the link to such documentation or even automatically open it in the default web-browser as a nice-to-have enhancement.

**Comment by hohwille** [comment]
Seems we already tried to address this problem earlier:
https://github.com/devonfw/ide/blob/70baf93ecffb8967f34be86c3ac6f4465b911af3/scripts/src/main/resources/scripts/functions#L808

We should first analyze why this did not help:
* maybe @maybeec was using an older version of devonfw-ide that does not contain this feature? Rather unlikely but possible...
* maybe it is not exactly that move command that fails but some other command like https://github.com/devonfw/ide/blob/70baf93ecffb8967f34be86c3ac6f4465b911af3/scripts/src/main/resources/scripts/functions#L786
* maybe it is the correct line but the "fix" does not work

**Comment by maybeec** [comment]
It's actually not related to an ide sxrops) scripts upgrade.
As shown it is simply trying to upgrade eclipse and the respective Java. For sure there might be always zombie processes blocking this although I am pretty sure that I tried closing as much as possible as I know this issue quite well. Can even occur in case you ran Maven on a console that the console is blocking the process executables although the Maven execution already ended... So if you cannot reproduce it in several tries, let's close it or think about more proper message output.

**Comment by CREITZ25** [comment]
The command:
   mv "${source}" "${backup_dir}/" || doFail "Failed to move ${source} to ${backup_dir}.\nMost probably this is a problem of windows file locks. In such case please terminate all processes locking the files and retry the operation." 

works fine. The output is:

******** ATTENTION ********
Failed to move /d/cobigen/software/java to /d/cobigen/updates/backups/22-12-19.
Most probably this is a problem of windows file locks. In such case please terminate all processes locking the files and retry the operation.

At this point the function ends with "exit 255", and  return to the previous function

**Comment by hohwille** [comment]
@CREITZ25 you are correct. The hint is already reported in the error message. I was just not reading the log carefully.
So we might provide a more details asciidoc for this topic and can add the link to that error message.

**Comment by CREITZ25** [comment]
@hohwille From my point of view it makes no sense to add an URL that points to a documentation that actually says exactly the same thing. One should instead emphasize the very rare occour error message on the screen more clearly.
https://user-images.githubusercontent.com/95033856/214826582-cf555af6-61a9-43d5-8242-93d72bbc2221.JPG

**Comment by CREITZ25** [comment]
Create a new documentation for tools which are able to terminate processes is not a bug. Please create another ticket for a new functionality
