### ISSUE TITLE
Python update failed as alpha versions not correctly parsed resp. ignored

### ISSUE THREAD

**Issue by maybeec** [devonfw/ide#1029]
### Expected behavior

As a user, I want to update all my software to latest state so that I can continue working with the latest versions

### Actual behavior
Having python installed, I now get
```
*** Setting up python ***
Updating python from version 3.10.8 to version 3.12.0...
Success: run command mkdir
Starting installation of python in version 3.12.0 to /d/cobigen/software/python
Trying to download python-3.12.0-windows.zip from https://www.python.org/ftp/python/3.12.0/python-3.12.0-embed-win32.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   146    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Failed to download https://www.python.org/ftp/python/3.12.0/python-3.12.0-embed-win32.zip with exit code 22

```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Install a new devonfw ide with python of version 3.10.8 
2. Remove the python version configuration to get the latest version from the web
3. It will say that the latest version 3.12.0 is not available as the version should be 3.12.0a1 or 3.12.0a2 or 3.12.0a3 as shown here https://www.python.org/ftp/python/3.12.0/

### Comments/Hints:

It seems that the naming convention with a01 is referring to an alpha version: https://www.python.org/downloads/release/python-3120a1/
So either these versions should be correctly parsed or ignored by the ide-mirror repository. 

Workaround available by simply setting `PYTHON_VERSION=3.11.1` in `settings/devon.properties`

### Tested on:

* OS: Windows
* Console: Git Bash

**Comment by hohwille** [comment]
See #941 - we will not invest into the old and buggy approach but soon replace it with a reliable solution that will solve all these problems. Thanks for reporting the bug anyway.

**Comment by hohwille** [comment]
fixed in mirrors (see commit linked above).
