### ISSUE TITLE
Environment variables defined in devon.properties are not available in devonfw CMD

### ISSUE THREAD

**Issue by patrickvogel** [devonfw/ide#1043]
### Expected behavior

As a developer, I want the environment variables of a devonfw CMD to be set as defined in `conf/devon.properties` of my `ide-settings`.

### Actual behavior 

The environment variables defined in `conf/devon.properties` are not available in a devonfw CMD.

### Steps to reproduce 

1. Install a `devonfw-IDE` with `ide-settings` having a `conf/devon.properties` containing some specific environment variables, e.g.
```
export FOO=BAR
```
2. Open up a devonfw CMD and execute `echo %FOO%`
3. Result is `%FOO%` / expectation would be `BAR`

### Related/Dependent Issues
Probably https://github.com/devonfw/ide/issues/954

### Comments/Hints:
I guess using `setlocal ENABLEDELAYEDEXPANSION` in devon.bat somehow prevents the environment variables to be set correctly. If I add a `echo %FOO%` directly after https://github.com/devonfw/ide/blob/release/2022.11.002/scripts/src/main/resources/scripts/devon.bat#L130 , the variable is empty. If I add `echo !FOO!`, the value is `BAR`.

### Affected version:
Noticed in 2022.12.001, but probably 2022.11.002 and newer

* OS: Windows

**Comment by hohwille** [comment]
Seems to be the same bug as #1066
