### ISSUE TITLE
creation of a documentation for using the software IObit Unlocker to find processes that block specific files

### ISSUE THREAD

**Issue by CREITZ25** [devonfw/ide#1051]
As a devonfw IDE user/admin, I want to find processes which block specific files. For this is a small guide in an asciidoc file required, which should also be linked in the case of corresponding error messages. The software can be found at https://www.iobit.com/en/iobit-unlocker.php

**Comment by CREITZ25** [comment]
Place to implement the url::

[ide/scripts/src/main/resources/scripts/functions](https://github.com/devonfw/ide/blob/70baf93ecffb8967f34be86c3ac6f4465b911af3/scripts/src/main/resources/scripts/functions#L808)

Line 808 in [70baf93](https://github.com/devonfw/ide/commit/70baf93ecffb8967f34be86c3ac6f4465b911af3)

mv "${source}" "${backup_dir}/" || doFail "Failed to move ${source} to ${backup_dir}.\nMost probably this is a problem of windows file locks. In such case please terminate all processes locking the files and retry the operation."

**Comment by hohwille** [comment]
@CREITZ25 thanks for creating this story.
To refine this: Actually what we really want is a general documentation about windows file locks and resulting problems + solutions and additionally outputting a link to that documentation page in the file locking error message we already have.

On this documentation page, we can link to Unlocker but also to ProcessExplorer and other tools.
