### ISSUE TITLE
devon ide update fails on vs code download

### ISSUE THREAD

**Issue by mdriesse** [devonfw/ide#1055]
### Steps to reproduce (bug)

run "devon ide -b -f update all"

### Comments:
vs code download fails with error
Failed to download https://update.code.visualstudio.com/v14/win32-x64-archive/stable
A log is attached for your reference.

### Observations:
URL is no longer valid and returns "Cannot GET /v14/win32-x64-archive/stable".
After update error running "devon vscode start" fails as well.

### Affected version:

* OS: Windows

[devon_upgrade_log.txt](https://github.com/devonfw/ide/files/10581771/devon_upgrade_log.txt)

**Comment by mdriesse** [comment]
Bug is caused by an error in the file "\devon\mirrors\vscode\available-versions"
First 3 lines contain wrong version numbers.

**Comment by mdriesse** [comment]
Solved the issue with a hard git reset to the origin/master.
I don't have a clue how the wrong version numbers got into the file.

**Comment by hohwille** [comment]
@mdriesse thanks for the feedback.
Indeed we once had this bug (with versions like `master-with-conflict-190418` as versions are also detected from branches). As it seems you had a git issue updating your `ide-mirrors` repo locally, I would tend to close this.
Surely the same error might also affect other users but there is a workaround that you have already found and we are replacing `ide-mirrors` with `ide-urls` (see #941).
