### ISSUE TITLE
VSCode remote editing

### ISSUE THREAD

**Issue by amarinso** [devonfw/ide#106]
Category: enhancement

Having played with the new VSCode remote editing plugin (currently on the insiders preview version) I think it opens for new portable development possibilities 

https://code.visualstudio.com/docs/remote/remote-overview

this allows working with the VSCode in local machine, in your host OS but having the files and target application running on another (remote) system, being that an SSH or Docker container

So, imagine having the portability of the Docker container (all people have the same environment) and the convenience of local responsiveness

**Comment by hohwille** [comment]
@amarinso sounds very cool. Thanks for the valuable input.

Should this better be integrated into our extension pack?
https://github.com/devonfw/devonfw-extension-pack-vscode
Or does it make sense to directly add this to devon-ide?

**Comment by amarinso** [comment]
I'm not quite sure.
If the extension pack starts packaging all available or potentially useful plugins... VScode is going to become a bloated IDE sooner than later...
I don't know which is the current strategy to have this under sensible control

**Comment by dario-rodriguez** [comment]
Hello @amarinso ,

The remote plugin was already added some months ago to devonfw Platform Extension Pack plugin. It's a useful extension for all stacks (java, node, python...)

Related to have a bloated VSCode: that's true, there are lot of extensions in the devonfw plugin for all stacks, but in my opinion, it's not a problem at all. VSCode allows you to enable/disable plugins only for a workspace, so the first time that you open a VSCode in a concrete folder/workspace, you only need to enable/disable the plugins that you need and the next time you open that folder/workspace it will remember the plugins that you disable and will load only the enabled ones.

The workflow that I follow is: in my VSCode, disable most of plugins and only keep the transversal ones (Remote, gitlens, github pull request...). Then, I enable only for a specific workspace the plugins that those project needs (language support, formatters...). I have installed like 200 plugins and it works pretty well.

**Comment by hohwille** [comment]
@dario-rodriguez thanks for your notice. So I can close this issue as the plugin is already included.
However, IMHO the real feature does make more sense for ProductionLine and other server-side solutions, but in case someone wants to use devonfw-ide inside a server-side solution it might be handy...

**Comment by dario-rodriguez** [comment]
It's not only related to work in a remote server. It's just a feature. But the most interesting feature is you can work inside a docker container. In that case you won't need to install any other tool than VS Code. No more java, maven, nodejs and so on installed locally, you can use a docker image that already have that tools.

Another cool feature of this plugin is you can work easily in the WLS.

Last point, in production line you can't deploy any application, so that's true, it doesn't make sense for production line, but you can use it with a virtual machine where you have your application deployed.
