### ISSUE TITLE
Align tool names in scripts

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#1085]
For epic #941 and as special addition for story #1084 we want to use the migration from `mirrors` to `urls` also as cleanup:
In general we follow the best practice and convention that if we have a tool `«tool»` then we use the same name in the following places:
* commandlet: `scripts/command/«tool»`
* software folder: `software/[extra/|macos/]«tool»`
* ide-urls folder: `ide-urls/«tool»/«edition»/«version»/`
* variables: `«TOOL»_VERSION` and `«TOOL»_EDITION`
* When running `devon «tool» «args»` you should get the same effect as when running `devon` followed by `«tool» «args»` except that if the tool is not yet installed in the first case it will be downloaded and installed and in the second case it will fail as the tool is not installed.

However, there are currently the following excuses/exceptions to that rule:
* `mvn` vs. `maven` - as the command to run is given as `mvn` we have to use that instead of `maven` consistently.
* `node` vs. `nodejs` - as the command to run is given as `node` we have to use that instead of `nodejs` consistently.
* `sonar` vs. `sonarqube` - here we do not have any matching given command except `StartSonar.bat` or the like that is not even in the `PATH` after set by `devon` command. For simplicity, I would propose to stay with the shorter name `sonar` and rename `sonarqube` occurances to `sonar`.
* `cobigen` vs. `cobigen-cli` vs. `cli`. The command is actually `cg` and `cobigen`. We can discuss with @jan-vcapgemini but IMHO `cobigen` is more self explanatory than `cg` that could confuse new users that might never get what this is about and therefore miss the according features behind it.

The acceptance criteria of this story is that devonfw-ide strictly follows this rules.
Therefore according scripts (see details above) need to be adapted accordingly.
Further we also have to change our `devon.properties`:
https://github.com/devonfw/ide/blob/117cc4684142405103ff64c0f48518c24ee8db15/scripts/src/main/resources/scripts/devon.properties#L18
Please also do a cleanup of internal variables such as `COBIGEN_CLI_HOME` vs. `COBIGEN_HOME`, etc.

This story does NOT care about backward compatibility as this is addressed by #1087.

Blocked by dependencies:
* #1086 
* #1087
* #1035 
* #1084

**Comment by CREITZ25** [comment]
@hohwille 
In order to adjust the cobigen commandlet according to the specifications, the path cobigen-cli must be changed to cobigen. The variable COBIGEN_CLI_HOME should also be adjusted to COBIGEN_HOME. However, the problem arises that the variable is already used in the cobigen environment. Therefore, in the scripts/devon.properties file, the variable COBIGEN_HOME is already set to a configuration file or directory. How do I have to proceed here?

**Comment by CREITZ25** [comment]
@hohwille after the issue has been implemented, the doGetToolFolderName function is free of the exceptions and generates the name of the software from the transferred software path. Perhaps the function should be renamed to doGetToolName, or replace the calls directly with the contents of the function.

**Comment by CREITZ25** [comment]
node is already adapted
