### ISSUE TITLE
Assure portability of vsCode

### ISSUE THREAD

**Issue by maybeec** [devonfw/ide#111]
Assure vsCode portability by setting the custom configuration for extension and home path.
Also you need to adapt the start script to check if no other instance is running, which is not started from the installation of the IDE as vsCode is working with shared application runtime, which would break with the project settings:

[vscode.txt](https://github.com/devonfw/devon-ide/files/3177462/vscode.txt)

**Comment by hohwille** [comment]
Thanks for the feedback. This is valueable input.

```
for /f tokens^=*^ delims^=^ eol^= %%i in ('powershell -command Get-Process -ProcessName Code ^^^| Format-List path') do (
	set PROCESS_LIST="%%i"
	goto:break
)
```
However, this is really ugly as we just got rid of the platform specific code for commandlets, etc.
I have to think about a good way to integrate this but am currently too busy with other stuff.

**Comment by hohwille** [comment]
can you give guidance how to configure individual "extension and home path"?
Our config can be found here:
https://github.com/devonfw/devon-ide/blob/master/settings/src/main/settings/vscode/workspace/update/.vscode/settings.json

Currently it is minimalistic as I am lacking the knowledge what to configure.
I found this guide:
https://code.visualstudio.com/docs/getstarted/settings

```
"emmet.extensionsPath"
```
Is that what you are talking about???
Not a single clue what `emmet` could stand for?!?

**Comment by hohwille** [comment]
I would love to have some active contributors using tools like vscode, node.js, npm, yarn, etc. providing PRs to add the support. For me it is very inefficient if nobody is giving me the details what we need to put in which configuration file, etc.
Do you know any developer with according knowledge who could make all this happen in a screen-sharing session to boost the progress?

**Comment by hohwille** [comment]
vscode is a beast. It sometimes does not properly exist what causes any furhter instance to startup:
```
/projects/ide-test/software/vscode/bin/code: line 2: 98869 Trace/BPT trap: 5       "/projects/ide-test/software/vscode/Visual Studio Code.app/Contents/MacOS/Electron" $@
```

Is there any way to prevent this Electron crap and define an individual vscode "instance-id" for each installation of devon-ide?

**Comment by maybeec** [comment]
As far as I know, no. Therefore, I came up with the process list scan and checking the current instance running to be the one of the intended IDE.
I would be happy to find a different solution.

**Comment by hohwille** [comment]
I also have seen that it is possible to configure the root folder where the extensions are stored:
https://code.visualstudio.com/docs/editor/extension-gallery#_command-line-extension-management

I do not know what the default is, but IMHO a central folder (e.g. in user home directory) leading to bugs with our sandbox concept that each IDE is isolated from others.

**Comment by hohwille** [comment]
Indeed. The default is `~/.vscode/extensions`. That clarifies why the installation of `devonfw-ide` interfered with a globally installed instance of VS-Code. I filed isse #379 for this.

**Comment by maybeec** [comment]
Hi @hohwille, I think we already talked about that.
Please see 

```batch
@echo off

pushd %~dp0

rem sets the required environment variables
call scripts\environment-project.bat

set VSCODE_CONF=%CD%\%CONF_PATH%\ide-settings-vscode

setlocal enabledelayedexpansion
rem set PROCESS_LIST="powershell -command Get-Process -ProcessName Code ^^^| Format-List path"
for /f tokens^=*^ delims^=^ eol^= %%i in ('powershell -command Get-Process -ProcessName Code ^^^| Format-List path') do (
	set PROCESS_LIST="%%i"
	goto:break
)
:break
setlocal disabledelayedexpansion

echo.%PROCESS_LIST%|findstr /C:"%SOFTWARE_PATH%\vscode\Code.exe" >nul 2>&1
if errorlevel 1 (
	echo.%PROCESS_LIST%|findstr /C:"Cannot find a process" >nul 2>&1
	if errorlevel 1 (
		goto :closevscode
	)
)

if [%1]==[] goto executewithoutpath
start "" "%SOFTWARE_PATH%\vscode\Code.exe" --new-window --user-data-dir "%VSCODE_CONF%\user-data" --extensionHomePath "%VSCODE_CONF%\extensions" "%1"
goto :end

:executewithoutpath
start "" "%SOFTWARE_PATH%\vscode\Code.exe" --new-window --user-data-dir "%VSCODE_CONF%\user-data" --extensionHomePath "%VSCODE_CONF%\extensions"
goto :end

:closevscode
echo VSCode is running from another location. You have to close it to start this IDE instance of VSCode in an isolated environment.
echo Further information: VSCode manages a global state, which is reused by any opened window. It is not supported by VSCode to start new windows isolated with different runtime arguments.
pause

:end
popd
```

which is a start windows batch file to assure, that no other vscode instance is running as vscode always assures, that there is just one executable running and in this case starts a new window of the already running executable.

Regarding the issue, there are two parameters of interest --user-data-dir for isolating the settings and --extensionHomePath for isolating the installation of plugins in an instance.

**Comment by hohwille** [comment]
https://code.visualstudio.com/docs/editor/portable

**Comment by hohwille** [comment]
Hi Malte the CLI option `--extensionHomePath` that you are suggesting is inofficial or does not exist. I better go with the official documentation:
https://code.visualstudio.com/docs/editor/command-line

**Comment by maybeec** [comment]
It may have changed, but it continues to work until now :)
But better go with the official one. Agreed.

**Comment by hohwille** [comment]
https://github.com/microsoft/vscode/issues/48

**Comment by hohwille** [comment]
VS Code is a beast:
```
launching VSCode...
[main 2020-03-27T16:13:56.169Z] Could not delete obsolete instance handle Error: ENOENT: no such file or directory, unlink '/Users/hohwille/projects/devon/workspaces/main/ide/scripts/target/integration-test/test-setup/conf/vscode/1.43.2-main.sock'
    at Object.unlinkSync (original-fs.js:976:3)
    at Object.doStartup (/Users/hohwille/projects/devon/workspaces/main/ide/scripts/target/integration-test/test-setup/software/vscode/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:558:254)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  errno: -2,
  syscall: 'unlink',
  code: 'ENOENT',
  path: '/Users/hohwille/projects/devon/workspaces/main/ide/scripts/target/integration-test/test-setup/conf/vscode/1.43.2-main.sock'
}
[main 2020-03-27T16:13:56.173Z] Error: ENOENT: no such file or directory, unlink '/Users/hohwille/projects/devon/workspaces/main/ide/scripts/target/integration-test/test-setup/conf/vscode/1.43.2-main.sock'
    at Object.unlinkSync (original-fs.js:976:3)
    at Object.doStartup (/Users/hohwille/projects/devon/workspaces/main/ide/scripts/target/integration-test/test-setup/software/vscode/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:558:254)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
Failed to run command: '/Users/hohwille/projects/devon/workspaces/main/ide/scripts/target/integration-test/test-setup/software/vscode/bin/code' --new-window --user-data-dir '/Users/hohwille/projects/devon/workspaces/main/ide/scripts/target/
```

I assume we need a contributor for devonfw-ide who uses vscode for his daily work and also has a motivation to make these things working and perfect... I am too old for this Electron magic - LOL.

**Comment by hohwille** [comment]
Github autoclosed this issue.
Can people test and give feedback? Accroding to @sjimenez77 this is now working.
I retested on MacOS and can confirm:
* Now every installation of vscode in devonfw-ide has its isolated plugins/extensions
* Launching `devon vscode` opens the vscode instance for the current IDE instance even if other VS Code instances are currently running while it just focuses the current VSCode if it already runs for the same devonfw-ide instance. IMHO this is exactly what we wanted to archive.

However, on MacOS I seem to face a different issue (might not be OS specific):
When I setup devonfw-ide now with an exsiting settings git that does not have `vscode/plugins` configured, then I do not get the `devonfw-extension-pack` installed. Is that OK or should we file a bug issue for this?
