### ISSUE TITLE
Separate eclipse plugins and keep software installation pristine

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#1114]
As a devonfw-ide maintainer and product-owner, I want to keep the installation of the `Eclipse` IDE product pristine and have plugins and their updates in a separate folder so that the `Eclipse` installation itself remains "read-only" and pristine and can be shared across multiple devonfw-ide instances without side-effects between projects.

We already have managed to archive this goal for vscode and intellij so Eclipse is the only tool missing to complete the goal (see also bug #1082 that otherwise cannot be cleanly resolved).

One option could be to set this:
```
-Dorg.eclipse.equinox.p2.reconciler.dropins.directory=«my-plugins-folder»
```

However, this will only cause Eclipse to load (additional) plugins/features from there while still installing new plugins/features into the `Eclipse` product itself that therefore manipulates itself.

Another option to try could be:
```
-configuration «my-plugin-folder»
```

Maybe there are even other options so first step would be to test, evaluate and analyse this before even creating a PR.
The goal would be that plugins installed via commandline AND plugins installed within Eclipse itself (ideally including via Eclipse update functionality of its own internal plugins shipped with the product) would go to the newly configured `«my-plugin-folder»` that could be `${DEVON_IDE_HOME}/software/eclipse-plugins` to follow current conventions. But also we could revisit this and consider moving plugins from `software` to their own top-level `plugins` folder as they are something different to the rest we put in `software`.

**Comment by alfeilex** [comment]
I tried the `-configuration` option and it works to install plugins in an external location, either with command or via a GUI. 

I mentioned that the plugins do not show up in the Eclipse GUI, but after searching for the installed plugin in the marketplace, the plugin shown as "installed" marked.

**Comment by alfeilex** [comment]
I have a problem uninstalling plugins via `devon eclipse remove-plugin <id>`. There is no uninstall option to specify the location of installed plugins.

**Comment by alfeilex** [comment]
> I have a problem uninstalling plugins via `devon eclipse remove-plugin <id>`. There is no uninstall option to specify the location of installed plugins.

I could fix this problem by https://github.com/devonfw/ide/pull/1135/commits/7fcc663cee6085a22b8181b5c17d1b73322238e1

**Comment by alfeilex** [comment]
Some tests need to be done to check shared configuration etc.
