### ISSUE TITLE
ability to configure and setup milestone versions of Eclipse

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#1118]
As a devonfw-ide admin and user, I want to be able to test intellij milestone releases so that I can prepare the official setup for the next upcoming release, test new features as well as test and report bugs to improve the quality of an official eclipse release.

Currently only Release-Versions of Eclipse are supported and this is hard-coded:
https://github.com/devonfw/ide/blob/c3d56da8a90b950be0f9acfecd0e5f6cc651d536/url-updater/src/main/java/com/devonfw/tools/ide/url/updater/eclipse/EclipseCrawler.java

So for proper support, we also need to discover milestone versions in `Updater` and build the URL dependent if the version is a milestone or an official release.

**Comment by alfeilex** [comment]
How should we distinguish between release-types? Should we rename other releases that are not `R`, e.g. `2023-06-<release-type>`

**Comment by alfeilex** [comment]
I was able to get `2023-06 M1` version in https://www.eclipse.org/downloads/packages/release 

If we would like to change the name in the final directory, we have to update the `version` already in object `UrlVersion` .
