### ISSUE TITLE
treat 404 downloads of url-updater

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#1131]
Our url-updater is hitting many 404 (not found) errors for download URLs.
Sometimes various versions that we find seem not to exist as download or at least not in the expected URL schema.
In other cases only a particular OS+architecture combination seems to be missing leading to 404.

Before we decide to just ignore all these errors, we should do some investigation and analysis if maybe we have to fix something.
Further, my expectation is that for versions that are found in some HTML structure but not as download file entirely (all OS+architecture), we will repeat the according errors every night what is undesired. However, we also do not want to add a folder for this version containing no download as the existence of a version folder implies the existence of the tool edition version for devonfw-ide (at least by the current design).

**Comment by alfeilex** [comment]
`aws` version 2.0.32 does not exist and therefore the url responds with 404 error

**Comment by alfeilex** [comment]
- AWS
 > 2.0.32 does not exist and therefore the url responds with 404 error
- Azure
 > Fix with new regex [910fe25](https://github.com/devonfw/ide/pull/1155/commits/910fe25f2de73d0d78b7f68702b4af8e029f258c)
- Dotnet
 > Fix with new regex [910fe25](https://github.com/devonfw/ide/pull/1155/commits/910fe25f2de73d0d78b7f68702b4af8e029f258c)

**Comment by alfeilex** [comment]
Should we add some functions to filter out versions, which do not provide the required installation files? Or should we just override `mapVersion` function in each updater? 

But sometimes there are versions that do not provide windows installation files up to certain version... how we can control this?

**Comment by alfeilex** [comment]
The most 404 errors occurs because 

- download links for arm architecture are not available for all releases
- versions are crawled in wrong format

**Comment by alfeilex** [comment]
See the changelog for the tools in related PR
