### ISSUE TITLE
Separate plugins from software

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#1147]
We should move plugins from `software` to their own top-level `plugins` folder as they are something different to the rest we put in software.

Current layout:
```
/ DEVON_IDE_HOME
└──/ software
   ├──/ az
   ├──/ cobigen-cli
   ├──/ dotnet
   ├──/ eclipse
   ├──/ eclipse-plugins
   ├──/ extra
   ├──/ intellij
   ├──/ intellij-plugins
   ├──/ java
   ├──/ maven
   ├──/ vscode
   └──/ vscode-extensions
```

New layout proposed by this issue:
```
/ DEVON_IDE_HOME
├──/ plugins
|  ├──/ eclipse
|  ├──/ intellij
|  └──/ vscode
└──/ software
   ├──/ az
   ├──/ cobigen-cli
   ├──/ dotnet
   ├──/ eclipse
   ├──/ extra
   ├──/ intellij
   ├──/ java
   ├──/ maven
   └──/ vscode
```

This story affects all commandlets that can have plugins:
* [android-studio](https://github.com/devonfw/ide/pull/1136)
* [eclipse](https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/scripts/command/eclipse)
* [intellij](https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/scripts/command/intellij)
* [vscode](https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/scripts/command/vscode)

**Comment by maybeec** [comment]
I would not agree to that. What is the benefit? You might even run into incompatibility issues if someone does a major upgrade of an ide causing the ide not to start anymore.

**Comment by hohwille** [comment]
> I would not agree to that. What is the benefit? You might even run into incompatibility issues if someone does a major upgrade of an ide causing the ide not to start anymore.

Thanks for your feedback, I try to explain more... not part of this story but for the rationale:

In the future we will enable [shared repository](https://github.com/devonfw/ide/blob/master/documentation/software.asciidoc#shared) by default (for the real solution of #1082).
Then `software` folder will only contain symbolic links to software tool-edition versions from the central shared software repository (except for the `extra` folder that we could also eliminate entirely or move from `software/extra` to `extra-software`).
Each tool can then have "dependencies" (e.g. `jenkins` version `x1` needs `java` version `j1` while `eclipse` version `e1` needs `java` version `j2` while `sonarqube` version `s1` needs `java` version `j3` causing severe conflicts if `j1!=j2!=j3`.

For compatibility we introduced [migration scripts](https://github.com/devonfw/ide/issues/971). We are using this feature also to resolve other "incompatibilities" like #1087.

**Comment by hohwille** [comment]
I better create a new story for that, as this story is already labelled with milestone `2023.07.001` so reopening and adding changes to the next release will fake the release history and cause confusion.
