### ISSUE TITLE
Replace WebsiteUrlUpdater with JsonUrlUpdater

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/ide#1172]
As a devonfw-ide developer, I want to benefit from the json version files provided by the vendors so that I can take a valid download URL with its corresponding checksum instead of having to grab version from websites and generating checksums through downloading each program.

**Comment by jan-vcapgemini** [comment]
For dotnet I've already found a json file which we can use: https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/7.0/releases.json
Referenced from: https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json

**Comment by hohwille** [comment]
I updated the summary/title as GithubUrlUpdater extends JsonUrlUpdater and therefore this did not make sense to me.

**Comment by Oumal1** [comment]
for python i fond the following File which we can also use : [https://github.com/actions/python-versions/blob/main/versions-manifest.json](url)

**Comment by hohwille** [comment]
was auto-closed by merging PR #1205 but still not completed.
