### ISSUE TITLE
Intellij and Eclipse devonfw-ide code reformats are not the same

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/ide#1173]
### Expected behavior

As a devonfw-ide developer/user, I want to use the same code reformat settings for eclipse and intellij so that I don't get diff wars.

### Actual behavior
Javadocs and import orders are not the same for eclipse and intellij.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Apply a reformat in eclipse, commit
2. Apply a reformat in intellij, commit
3. Check changes

### Affected version:

* devonfw-ide: 2023.05.001-SNAPSHOT

**Comment by hohwille** [comment]
We plan to solve this with the eclipse formatter plugin for intellij.
The documentation should also be extended with a hint that projects with focus on intellij can/should remove the plugin and use the native intellij code style. Also users that want to use the plugin should be informed via the documentation that the most settings from the Java code style in Intellij are overruled if that plugin is active (installed and actively configured).
