### ISSUE TITLE
Download link for latest devonfw-IDE scripts doesn't work

### ISSUE THREAD

**Issue by patrickvogel** [devonfw/ide#1183]
### Expected behavior

As a user, I want to be able to download the latest version of devonfw-IDE via the Link in the README

### Actual behavior

A login prompt is shown by the browser

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Go to README
2. Click on the "here" link of https://github.com/devonfw/ide/blame/master/README.asciidoc#L42

### Comments/Hints:
https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.devonfw.tools.ide&a=devonfw-ide-scripts&v=LATEST&p=tar.gz asks for credentials

The download links on the releases page work (https://github.com/devonfw/ide/releases)

### Affected version:

* OS: Windows/Linux/Mac
* Browser: Chrome/Firefox/Safari

**Comment by hohwille** [comment]
@patrickvogel thanks for reporting. Actually the bug resides in a service offered by sonatype and we can do very little about it.
However, I will temporary add the direct download link to the instructions so users do not get lost.

**Comment by hohwille** [comment]
I hoped that sonatype would notice the global bug immediately and take action. As the error is still present, I created a JIRA issue:
https://issues.sonatype.org/browse/MVNCENTRAL-8154

**Comment by hohwille** [comment]
The sonatype service is still broken and the ticket above did not help. I am giving up on this as I do not have any other idea how to reach out the responsible people. Instead I just replaced that link with a link to our release overview that always shows the latest version on top with the download link first. This requires one additional click for the user but should be feasible.
