### ISSUE TITLE
Integrate url-updater and configurator into ide

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#1194]
Currently we have the Java-based modules `url-updater` and `configurator`.
With #1090 almost all will go to Java code and this separation does not make sense anymore (the only separation left will be `ide` and `dashboard`).
Once #1191 is done, this story can start and migrate the modules `url-updater` and `configurator` into the `ide` module.
* [x] move the code from `url-updater` into `ide`, delete `url-updater` folder and module from top-level POM
* [x] copy the code from `configurator` into `ide` (we do not want to touch/break the existing configurator so at any point in time the current devonfw-ide-scripts release is still fully functional. You can also create a maven dependency to configurator instead of copying the code, if you prefer)
* [x] Integrate the configurator into a Java `Eclipse` commandlet that allows to trigger the `ws-update` feature.
* [ ] Build a native image of the result and test if this works with GraalVM
* [x] Adapt the github action that runs the url-updater accordingly (1. build ide instead of url-updater, 2. explicitly specify the main class as the new default main class will become our new Java CLI).

**Comment by alfeilex** [comment]
This task: **Build a native image of the result and test if this works with GraalVM** will be solved with issue: #1192 

After merge I will check this task as completed
