### ISSUE TITLE
Integrate ToolCommand with UrlUpdater

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#1195]
After #1194 is implemented, we want to archive that we can implement one "tool" in one class with as little effort and code as necessary. My vision is that we will just have once class for each tool called `Mvn`, `Java`, `Eclipse`, etc. that both contains the commandlet logic as well as the logic for the UrlUpdater. 
In case this does not work out well with inheritance (different UrlUpdater base-classes and `ToolCommand` base-class that later might also get further abstract sub-classes), we could have a method `public abstract UrlUpdater getUpdater()` in `ToolCommand`. In our classes like  `Java`, `Eclipse`, etc. we can have the `UrlUpdater` implementation as inner class and return its singleton instance via `getUpdater()`.

**Comment by alfeilex** [comment]
Moved to IDEasy https://github.com/devonfw/IDEasy/issues/40
