### ISSUE TITLE
Create a custom logic to determine the latest version of ide-scripts

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/ide#1196]
As a devonfw-ide developer, I want to easily access the latest version of ide-scripts.

We need a custom solution to always provide the latest version as our current approach:

https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.devonfw.tools.ide&a=devonfw-ide-scripts&v=LATEST&p=tar.gz

is not reliable anymore.
See: #1183

**Comment by hohwille** [comment]
IMHO the service is just down for few hours or days and will be up and shiny again next week.
If that is the case, we can close the issues and consider it stable again.
Once the problem comes back again, we can still take action.

**Comment by hohwille** [comment]
I simply close this as "wontfix" (rejected).
We have found a simple workaround for #1183 so IMHO there is nothing left to do.
