### ISSUE TITLE
Docker is not running properly on Windows

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/ide#1226]
### Expected behavior

As a devonfw-ide docker user, I don't expect docker to report error messages when booting my OS.

### Actual behavior
Directly after starting Windows, following error message pops up within a new git bash window.

```
You are not inside a devonfw-ide installation: /c/WINDOWS/System32
docker is already installed at /c/Program Files/Rancher Desktop/resources/resources/win32/bin/docker
Client:
 Version:           24.0.2-rd
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        e63f5fa
 Built:             Fri May 26 16:43:15 2023
 OS/Arch:           windows/amd64
 Context:           default
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.
devonfw-ide environment variables have been set for /d/devonfw-test in workspace main
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Install docker using `devon docker`
2. Restart your OS

### Comments/Hints:
The docker command run from my devonfw-ide project folder works though.

### Affected version:

* OS: Windows
* devonfw-ide: 2023.04.001-SNAPSHOT

**Comment by hohwille** [comment]
This is IMHO a user error. You need to have the docker daemon running so that you can work with docker without errors.
RTFM: https://github.com/devonfw/ide/blob/master/documentation/docker.asciidoc#important-notice
