### ISSUE TITLE
Docker is not working on MacOS

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/ide#1244]
### Expected behavior

As a devonfw-ide MacOS user I want to install Docker-Desktop/Docker-Rancher, so that I can use it for my projects.

### Actual behavior
uninstalled docker
Successfully downloaded docker-rancher
Successfully installed docker
mv: rename /Users/username/devonfw-test-vanilla/updates/install/docker/\*.app to /Application/\*.app: No such file or directory
Failed to run mv
Exit code was 1
Running docker again will repeat this error.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Run devon docker
2. run devon docker again

### Comments/Hints:
The same problem occurs for docker-rancher.

### Affected version:

* OS: Mac
* devonfw-ide: 2023.07.001-SNAPSHOT

**Comment by CREITZ25** [comment]
Rancher desktop works fine

**Comment by CREITZ25** [comment]
No checksum file will be fixed with #1317
