### ISSUE TITLE
tomcat is not working on MacOSX

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/ide#1245]
### Expected behavior

As a devonfw-ide MacOS user I want to install tomcat, so that I can use it for my projects.

### Actual behavior
After installation following error occurs:

```
/Users/username/devonfw-test-vanilla/scripts/command/../functions: line 84: /Users/username/devonfw-test-vanilla/software/tomcat/bin/catalina.sh: Permission denied
Exit code was 126
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Run `devon tomcat version set 9.0.76`
2. run `devon tomcat setup`

### Comments/Hints:
Could possibly be fixed with setting the permissions inside the tomcat command script.

### Affected version:

* OS: Mac
* devonfw-ide: 2023.07.001-SNAPSHOT

**Comment by hohwille** [comment]
I should have properly stopped merging new features like tomcat until we had completed our release.
Now, we should fix this before releasing... Pity.

**Comment by hohwille** [comment]
Should be fixed after my commits and when the updater runs again tonight.

**Comment by hohwille** [comment]
Seems to be OK, as I checked X-flags manually in tar.gz and URLs are updated.
