### ISSUE TITLE
gcViewer version change/update not working

### ISSUE THREAD

**Issue by moritzLanger** [devonfw/ide#1299]
### Expected behavior

As a user, I want to be able to upgrade and downgrade my gcViewer version so that i can use the desired versions.

### Actual behavior

The current [GCviewer Script ](https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/scripts/command/gcviewer#L36)is not deleting the unused versions, leading to the first installed version being the one opened/used regarless of the version devon claims to be using.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1.  install any version of gcViewer (`devon gcviewer setup`)
2.  use `devon gcviewer verstion set 1.XX` to change the version 
3. redo `devon gcviewer setup`
4. launching gcviwer and going to help revelas the diffrent version than `devon gcviewer version get`

### Comments/Hints:

<img width="389" alt="image" src="https://github.com/devonfw/ide/assets/44358321/40d2b5f9-1e07-4d41-b3c8-0ec163692706">

<img width="251" alt="MicrosoftTeams-image" src="https://github.com/devonfw/ide/assets/44358321/c8454ba9-a395-4d68-8e0c-6379c9d7c790">

### Affected version:

* OS: Windows/Linux/Mac

**Comment by hohwille** [comment]
* https://github.com/devonfw/ide/blob/35770460cc08b8b5aba9c86170987a1ba5843a14/scripts/src/main/resources/scripts/command/gcviewer#L36
* https://github.com/devonfw/ide/blob/35770460cc08b8b5aba9c86170987a1ba5843a14/scripts/src/main/resources/scripts/command/gcviewer#L22
