### ISSUE TITLE
Setup doesn't download Eclipse Enterprise edition

### ISSUE THREAD

**Issue by duracotton** [devonfw/ide#1368]
### Expected behavior
Setup downloads Enterprise edition of Eclipse.

### Actual behavior
devonfw ide's setup.bat falls back to Standard edition of Eclipse:
![image](https://github.com/devonfw/ide/assets/25416153/6516b508-0cb2-4cec-a2e6-8fb49fa198bb)

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Create devon.properties entry: "export ECLIPSE_EDITION_TYPE=JEE"
2. Start setup to install eclipse
3. Above behaviour shows

### Comments/Hints:
- Choosing Eclipse Edition between Standard or Enterprise has been introduced 2 years ago: https://github.com/devonfw/ide/issues/507 but modified since then (didn't track down all changes).
- The official documentation still offers to use the ECLIPSE_EDITION_TYPE variable here: https://devonfw.com/website/pages/docs/devonfw-guide_ide.wiki_cli.asciidoc.html#devonfw-guide_ide.wiki_eclipse.asciidoc
- But ide-urls Repository does not have any Enterprise edition url defined: https://github.com/devonfw/ide-urls/tree/master/eclipse/eclipse/2023-09 nor is the url auto-generated=> see above error
- The devonfw-ide-scripts's Eclipse command script currently puts out a warning that ECLIPSE_EDITION_TYPE is outdated and replaced by ECLIPSE_EDITION: https://github.com/devonfw/ide/blob/af67497e06fb82e2e50a4d9ffa10e3f9dda44aa1/scripts/src/main/resources/scripts/command/eclipse#L262 (or see above screenshot) while documentation (see above) does not warn about that or differentiate between those variables.

=> Above is confusing, so how can I configure devon to install Enterprise edition in the end?

### Affected version:
devonfw-ide-scripts-2023.09
* OS: Windows

**Comment by hohwille** [comment]
@duracotton thanks for reporting this issue and for your precise details what is very valuable to trace down the problem.
So mainly I would consider this as a feature request to add support for the enterprise edition of Eclipse.
As it seems we earlier supported this "accidentally" or "without being aware of it", it somehow is also a regression bug since something that worked earlier now stopped working.
I never used the enterprise edition of Eclipse (only ultimate edition of IntelliJ what seems like a similar use-case).
So I added this issue to our board and we will try to implement this.

**Comment by hohwille** [comment]
> Above is confusing, so how can I configure devon to install Enterprise edition in the end?

There was a migration that should have solved this automatically for you:
https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/scripts/migrations/2023.07.003#L9

As nobody in our team developing devonfw-ide was actually aware of an enterprise edition of Eclipse it was never covered or tested.

I can find the variable explained in the documentation:
https://github.com/devonfw/ide/blob/master/documentation/eclipse.asciidoc

Rationale and details can be found in #1088 and #1086.
