### ISSUE TITLE
Release broken: system folder empty

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#1370]
### Expected behavior

As a devonfw-ide user, I want to make use of the full system-integration so that I can get the most out of it.

### Actual behavior

In Release `2023.09.001` the `system` folder in the *.tar.gz download file is empty!

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. download [release 2023.09.001](https://repo1.maven.org/maven2/com/devonfw/tools/ide/devonfw-ide-scripts/2023.09.001/devonfw-ide-scripts-2023.09.001.tar.gz)
2. extract or open it and browse the `system` folder.

### Comments/Hints:

This bug was not present in [release 2023.08.001](https://repo1.maven.org/maven2/com/devonfw/tools/ide/devonfw-ide-scripts/2023.08.001/devonfw-ide-scripts-2023.08.001.tar.gz)

### Affected version:

* 2023.09.001

**Comment by alfeilex** [comment]
I searched the last commits in the devon-ide repository. I found this 
https://github.com/devonfw/ide/commit/12ac70c9c71b4b4d678a13442c2b6f403c5a3981#diff-6edd7810d88397a53afad8a80e446407d60189d764c71638729ff9b91ca436be

Probably this `exclude` blocks the extraction of `system`.
