### ISSUE TITLE
gcviewer download fails

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#1371]
### Expected behavior

As a devonfw-ide user, I want to be able to install tools seamless so that I do not waste my time and benefit from automation.

### Actual behavior

If the automation fails the opposite effect happens: Users get blocked and may experience devonfw-ide as a black-box.
Currently the download of gcviewer fails:
```
$ devon gcviewer setup
Success: run command mkdir
Starting installation of gcviewer in version 1.36 to /d/projects/devonfw/software/gcviewer
Trying to download gcviewer-1.36-windows.zip from https://sourceforge.net/projects/gcviewer/files/gcviewer-1.36.jar/download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   965    0   965    0     0   2459      0 --:--:-- --:--:-- --:--:--  2487
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
Failed to download https://sourceforge.net/projects/gcviewer/files/gcviewer-1.36.jar/download with exit code 35

******** ATTENTION ********
Download of gcviewer in version 1.36 failed after trying 1 url(s).
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. devon gcviewer version set 1.36
2. devon gcviewer setup

### Related/Dependent Issues

Search for sourceforge in our issue tracker and you will see that we already had quite some fun with downloads from sourceforge.net.

### Comments/Hints:

Error seems to be related to TLS and revoked certificates. Maybe there is simply a malconfiguration on the sourceforge.net site and there is nothing we can do about it.
First thing to try would be to download the file manually in the browser.
If that works we have a "bug" in our product and should fix it.

### Affected version:

* gcviewer at least in 1.36 - maybe all versions or any download from sourceforge.net is affected.

**Comment by jan-vcapgemini** [comment]
GcViewer is really small (549KB), what about adding the latest version of it to our project by default?

**Comment by hohwille** [comment]
The problem was temporary on the server-side of sourceforge.net and has meanwhile been resolved.
Hence, I am closing it.
