### ISSUE TITLE
Username for accessing servers via Maven must not be encrypted

### ISSUE THREAD

**Issue by ohecker** [devonfw/ide#1389]
### Expected behavior

As a user of Maven within the devonFW IDE, I want to use the given settings.xml template (https://github.com/devonfw/ide-settings/blob/main/templates/conf/mvn/settings.xml) to generate my local configuration when setting up the IDE.

### Actual behavior

The templating mechanism uses the maven password encryption mechanism for every encountered variable `$[...]` to be replaced. Within the given default template this results in also the username (not just the password) to be encrypted:
https://github.com/devonfw/ide-settings/blob/b1d63fbc7849e9585d52595d786c30362212c34e/templates/conf/mvn/settings.xml#L20-L26.  

Using the generated settings.xml results in HTTP 401 Unauthorized.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

See above.

### Related/Dependent Issues

- https://github.com/devonfw/ide/issues/542

### Comments/Hints:

Using encryption on all variables to be replaced was a design decision documented in https://github.com/devonfw/ide/issues/542 . This decision was obviously based on the assumption that encrypting variables is a universal feature and can be used throughout the whole settings.xml. This is not correct: The option to use encryption in the settings.xml is only available for server passwords.

Possible quick fix/workaround: If the user name to be used is the name of the current OS user then 
 ```
 <servers>
    <server>
      <id>repository</id>
      <username>${env.USERNAME}</username>
      <password>$[mavenRepoPassword]</password>
    </server>
  </servers>

```
or
```
  <servers>
    <server>
      <id>repository</id>
      <username>${user.name}</username>
      <password>$[mavenRepoPassword]</password>
    </server>
  </servers>

```
will do the job.

If this is not the required user name, then probably the templating mechanism need to be extended to allow choosing if a variable should be encrypted or not.

### Affected version:

* OS: all
* Browser: N/A

**Comment by hohwille** [comment]
Note:
* for devonfw-ide fix here: https://github.com/devonfw/ide-settings/blob/dev-ide-settings/templates/conf/mvn/settings.xml#L23
* for IDEasy fix here: https://github.com/devonfw/ide-settings/blob/main/templates/conf/mvn/settings.xml#L23

**Comment by hohwille** [comment]
was auto-closed by github.
Reopening since only fixed for IDEasy but not for devonfw-ide.
