### ISSUE TITLE
ability to invoke specific migration features from CLI

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#226]
With our java migrator for devonfw projects we provide a very valuable tool for automatic code migration.
Currently we include very valuable code migrations like:
* migration of dozer from sourceforge to github version
* migration of queryDSL from mysema to official namespace version
* migration of junit4 to junit 5 (see #225)
* specific spring-boot updates, etc.

However, we have strictly bundled these migrations with particlar `devon4j` (and `oasp4j`) versions.
What if we would open this tool to all projects and make it more flexible?
What I the CLI would allow any project to run the migration from junit4 to junit5 on the project?

I do not want to spend enourmous extra effort in making this perfect, but just exposing the features we already have in the code to the CLI would be easy to do and bring a lot of additional value.

**Comment by tobka777** [comment]
I will develop a solution ;)!

**Comment by baumeister25** [comment]
This sounds like a cool feature. 
What is the status? Is this still in progress?

**Comment by hohwille** [comment]
I am closing as #991 makes more sense than reinventing the wheel.
