### ISSUE TITLE
Introduce DEVONFW_IDE_TRACE variable to enable tracing script output

### ISSUE THREAD

**Issue by markusschuh** [devonfw/ide#261]
Edited: Updated the enhancement proposal to use DEVONFW_IDE_TRACE instead. 

As a developer of devonfw-ide I want to have some means for debugging script execution, so that issues can be narrowed down a bit easier.

batch / shell scripting has it limits when it is about debugging. Setup of an IDE that could be used for single step execution isn't trivial, especially not, if both Windows batches and bash scripts need to be debugged. So I propose the following enhancement - it just enables some poor man debugging option - but even this could help:

All `*.bat` scripts of devonfw-ide could get the following line after the initial `@echo off`:
```
if NOT "%DEVON_IDE_DEBUG%"=="" echo on
```

and all `*.sh` scripts the line
```
if [ ! -z "$DEVON_IDE_DEBUG" ]; then set -vx; fi
````
If that is added inside `scripts\functions` the command scripts, that source the `functions`, won't need a change.

With that configuration in place a developer could set `DEVON_IDE_DEBUG` to `y` (or any other value except the empty string) and afterwards the scripts echo each line before execution - the bash scripts additionally a second time, when everything in script line is expanded.

**Comment by hohwille** [comment]
nice idea. Planned for 3.3.0.

**Comment by hohwille** [comment]
I decided to add a debug option (`-d` or `--debug` can now be provided).
See also #315

**Comment by hohwille** [comment]
Fixed with PR #317

**Comment by markusschuh** [comment]
I reopen my enhancement proposal.

The debug option introduced in #317 just outputs a few more messages - only when function `doRunCommand` is used, what does not even yet seems to be used in all cases, where external commands are executed by the devonfw-ide scripts. 
But this does not really enable a quick narrow down, what is happening in the background.

Let's use #363 where my proposal, when realized, could help to narrow down some potential issue. 
Instead the currently already realized `-d`, that is:

```
devon ide -d update settings
```

does not help at help, to understand, what is going on in the background. There is the `bashdb` - bach debugger - but running this in the typical environments, where `devonfw-ide` is used, isn't trivial.

I admit, that  my above proposal might be too vague and imperfect. But why not then discuss a bit on this? For example it could be, that my intention is more to have a TRACE - not only DEBUG output of `devonfw-ide` execution sequence within the scripts.

So a better proposal might be to use in all `*.bat` scripts 

```
if NOT "%DEVONFW_IDE_TRACE%"=="" echo on
```

and in all *.sh scripts the line

```
if [ ! -z "$DEVONFW_IDE_TRACE" ]; then set -vx; fi
```

**Comment by markusschuh** [comment]
I can provide a PR - but will only do this, when agreed upon the details. What in my understanding matches the sense of the CONTRIBUTING policy. 

For the moment I continue to "pimp" my local `devonfw-ide` installation when needed with help of

```
find $HOME/.devon/devon $(cut -d= -f 2 $HOME/.devon/home )/scripts/ -type f \! -name \*.\* | xargs sed -i -e '/^#!\/usr\/bin\/env bash/aif [ ! -z "$DEVONFW_IDE_TRACE" ]; then set -vx; fi'
```

which at least enables the tracing of the bash scripts.

So 

```
export DEVONFW_IDE_TRACE=1
devon ide update settings 2>&1 | less
```

allows me the wanted insight into the script flow of the specific commandlet, where I currently want a closer look ...

**Comment by hohwille** [comment]
@markusschuh I am happy to receive a PR as you commented in #433 you have easily done this change locally. It would be great if you can share your solution so we can integrate it.
