### ISSUE TITLE
bash's "process substitution" for input file descriptors fails in msys

### ISSUE THREAD

**Issue by markusschuh** [devonfw/ide#262]
### Expected behavior

As a user, I want setup to work, so that devon ide can be used.

### Actual behavior

During call of "setup.bat" the output contains
```
scripts/environment-project: line 7: /dev/fd/62: No such file or directory
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. ensure, git for windows is installed 
1. ensure, there is no other reference to a former devon version inside %USERPROFILE%
1. extract devon-ide-3.0.0-beta23.tar.gz, switch to base dir and run "setup.bat"

### Comments/Hints:

The error is from [line 50 of scripts/environment-project](https://github.com/devonfw/ide/blob/2de0abfba83905af3584c9ab717cd4c95132ed78/scripts/src/main/resources/scripts/environment-project#L50)
The script uses process substitution - but bash provides this feature only on systems, where FIFO support exists. And this isn't the case for `msys` on windows.  (Cygwin and the new WSL of Windows 10 do support FIFO)

### Affected version:

* OS: Windows 10 (1903)
* GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)

**Comment by markusschuh** [comment]
Proposal for code replacement, what works in environment without FIFO, too:

```
tr -d "\r" < "${1}" | 
  while IFS='=' read -r key value
  do
    ...
  done
```

**Comment by markusschuh** [comment]
It seems, the above proposal has the side effect, that the `eval ...` within the while loop - now executed as part of a pipe - changes the scope of the `key=value" definitions somehow - with the netto effect, that the properties are not defined, when `doLoadProperties` returns.
I have notified this due a missing "SETTING_PATH" after testing the above proposed change.

So maybe the following change proposal - which avoids the new pipe - is a better one:

```
  while IFS='=' read -r key value
  do
   value=$( echo -n $value | tr -d "\r")
    ...
  done | "${1}"
```

**Comment by gceasori** [comment]
where do I get devon-ide-3.0.0-beta23.tar.gz???

In this link:
https://repo.maven.apache.org/maven2/com/devonfw/tools/ide/devon-ide-scripts/
does not appear.

**Comment by hohwille** [comment]
@markusschuh thanks for the issue and the excellent analysis. I have no clue why the error does not happen in my win10 environment. Maybe it only happens on win7 or on native Win (I am using VM). However, I already got info from someone else that this like is causing issues on his machnine and it seems as you have traced down the root problem and suggested a fix.
I will try to change this accordingly and provide an update asap.

**Comment by hohwille** [comment]
Fixed in beta23 that has just been released.

**Comment by markusschuh** [comment]
Some more background:

My assumption, that there were no FIFO support at all in MSYS was **wrong**. There is even a mkfifo.exe in MSYS. It seems, the bash's issue with process substitution is just caused due to a non existing `/dev/fd` in `Git bash`

Normally the `/dev/fd` should just be a symbolic link to `/proc/self/fd` If I start a full MSY64 environment, the symbolic link **exists** and a bash there has correct process substitution. 

But the MSYS in Git-for-windows is "incomplete". It is just providing, what is needed for use of Git. So I guess: Either the "/dev/fd" was willingly removed there - or it is a kind of a regression. Anyway, it is better to avoid process substitution here at all. (as now realized)

**Comment by superole** [comment]
> But the MSYS in Git-for-windows is "incomplete". It is just providing, what is needed for use of Git. So I guess: Either the "/dev/fd" was willingly removed there - or it is a kind of a regression. Anyway, it is better to avoid process substitution here at all. (as now realized)

FYI: it seems like process substitution works in Git-for-windows' bash from version 2.25.0
