### ISSUE TITLE
Command autocompletion

### ISSUE THREAD

**Issue by dario-rodriguez** [devonfw/ide#287]
As a develop, could be useful to have some hints while I'm writting a devon-ide command.

For example: while I'm writting the command `devon java` could be useful to have some help if you forget some command, so if you press TAB it will show you the commands available for `devon java`. 

It's a nice to have. I don't know if it is possible to do for all consoles (cmd, powershell, bash...)

**Comment by hohwille** [comment]
I already planned this (e.g. via bash completion). Thanks for the issue. Would be a very helpful feature indeed.

**Comment by markusschuh** [comment]
I have prepared some first draft for autocomplete. But while it is easy enough to realize this for the majority of commands / sub commands and options there are a few special constructs used by devonfw-ide, which are harder to realize such as correct auto-complete support for `--all` in the related sub commands.

My draft isn't yet ready for production - and I'm afraid, I won't be able to work on that in the next time in order to produce a real PR. I'll create a fork and upload it there and will reference it here.

**Comment by markusschuh** [comment]
see draft currently available at
https://github.com/markusschuh/devon-ide/blob/feature-autocomplete/scripts/src/main/resources/system/bash/devon_autocomplete.sh

**Comment by hohwille** [comment]
@markusschuh great that you did create a draft already. Unfortunately you seem to have deleted your fork entirely from github. So the link is not working.
I found your new fork here:
https://github.com/markusschuh/ide/

But it does not seem to contain that feature either...

**Comment by markusschuh** [comment]
I have left that branch offline by intention, when I have recreated my fork to run on „ide“ instead of the older name. The autocomplete draft needs a bit rework now anyway, since after 5 months a few changes in the defonfw-ide command line syntax have happened. I will republish the next draft version.

But let‘s keep expectation low: There are some challenges in how the defonfw-ide CLI syntax was set up, that may need quite some more work for a autocomplete solution to follow those small - sometimes maybe unnecessary - differences between similar subcommands.

**Comment by tobka777** [comment]
I find this feature very interesting and have done some research. Unfortunately, there seems to be no solution for all terminals. 

With Bash you can use the complete command (`complete -W "now tomorrow never" dothis`) to do the autocompletion. It works for Linux and Macos. 
For zsh it seems to work as @markusschuh wrote. 
For Powershell and CMD I did not find a solution. You have to activate the autocompletion with Tab by `Set-PSReadlineKeyHandler -Key Tab -Function Complete`. However I have not found a way to do the autocompletion. Maybe someone has more experience and can help.

**Comment by hohwille** [comment]
> For Powershell and CMD I did not find a solution. You have to activate the autocompletion with Tab by Set-PSReadlineKeyHandler -Key Tab -Function Complete. However I have not found a way to do the autocompletion. Maybe someone has more experience and can help.

Do not worry about Powershell or CMD yet.
We only want to have it for bash.
On Windows we use `git-bash` that comes with git for windows and can be opened from Windows Explorer via `open git bash here`.
As the gitbash is technically a MINGW environment it might be limited. I have no clue if `complete` command is actually available.
I am using `zsh` on MacOS. Support for this is nice-to-have. For the first solution we should concentrate on `bash` and ideally support all 3 major platforms/OS.
However, let's be agile: Start with a prototype that solves the easy cases and might not work on all OS or shells. Also do not already implement it completely for all availble commands. Just pick one like `devon eclipse ...` or `devon ide ...` (whatever you are familiar with). Let us then have a look together what works well and what is not working or would be tricky to solve.

**Comment by hohwille** [comment]
So you are talking about this:
https://iridakos.com/programming/2018/03/01/bash-programmable-completion-tutorial
Is it possible to complete further arguments (2nd, 3rd, ...)?
It is already nice if `devon [tab]` will offer me `eclipse`, `help`, `ide`, `mvn`, `intellij`, `vscode`, `npm`, etc.
However, it is more likely that people are lost after this level and need help there more often.
What have been the options for `devon ide` to update the scripts again?
What have been the options for `devon eclipse` to reverse-merge the preferences again?
OMG I forgot all these options so I want to type `devon ide [tab]`.
Can we solve this as well?

**Comment by hohwille** [comment]
Seems to work as well...

**Comment by hohwille** [comment]
> It may even be helpful / necessary to modify the sub command options themselves a bit, since there seem to be some few unnecessary differences / inconsistencies. Why for example are the --batch --quiet --force described as options of the sub commands in the usage output? It might make more sense to define those as common options for main devon command - which I did for the moment inside this first autocomplete draft.

That makes perfectly sense. I just wanted `devon help eclipse` or `devon help ide`, etc. to print these options so you see *all* options and do not have to know about some kind of "inheritance" of options from `devon help`.
AFAIK I technically implemented these options and their help centrally so it is not duplicated in the commands themselves. Technically these are options of the `devon` command and not of the commandlet itself. I do not even know if `devon --force release` also works as `devon release --force`. Ideally it should but I have not tested...

**Comment by hohwille** [comment]
executable permission is still missing for `autocomplete` script:
https://www.edureka.co/community/13526/how-to-give-a-file-execute-mode-permissions-in-git
