### ISSUE TITLE
Setup quiet mode

### ISSUE THREAD

**Issue by jambulud** [devonfw/ide#315]
### Expected behavior

As a developer, I want to run the setup process in quiet mode so that I setup devonfw ide without questions.

### Actual behavior

Neither `setup --batch --quiet` nor `setup --quiet` avoids the "Settings url" question:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/43032659/70617210-62bf9a80-1c10-11ea-9362-b163e3eae8ff.png)

### Steps to reproduce bug

1. run `setup --batch --quiet` in a powershell console.

### Related/Dependent Issues

#316

### Comments/Hints:

When setup finishes it displays "Press any key to continue..." because the script has a harcoded "pause"

### Affected version:

* OS: Windows 10
* Console: Powershell

**Comment by hohwille** [comment]
All works with `devon` if options are provided after commandlet. However I can confirm it does not work with `setup`.

**Comment by hohwille** [comment]
Fixed with PR #317
