### ISSUE TITLE
devon ide settings url in batch mode

### ISSUE THREAD

**Issue by jambulud** [devonfw/ide#316]
### Expected behavior

As a developer, I want to setup devonfw ide in quiet mode without specifying a settings url so that I can manage the setup with just one command.

### Actual behavior

When running `devon ide setup -b -q` it takes the `b` token as the settings url. 

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/43032659/70617946-ff366c80-1c11-11ea-8729-c60b45af456d.png)

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1.  run `devon ide setup -b -q`

### Related/Dependent Issues

#315

### Comments/Hints:

if the command "devon" is not found run "./scripts/devon" (in general, the path of devon.bat).

`./scripts/devon ide setup ""  -b -q` works

### Affected version:

* OS: Windows 10
* Console: Powershell

**Comment by hohwille** [comment]
@jambulud thanks for filing this bug report.
First of all I analyzed the problem:
* the `setup.bat` script for windows does not pass arguments at all what is a first bug that is trivial to fix.
* next `setup[.bat]` is invoking `devon ide setup` with the given arguments appended.
* therefore `setup -b -q myUrl` will result in `devon ide setup -b -q myUrl`
* the handling of the CLI options is currently implemented in `functions` that is sourced by all commandlets including `ide` commandlet.
* this currently only works if the options follow immediately after the commandlet.
* however to make it work this way the command would need to be `devon ide -b -q setup myUrl` but as stated above it is `devon ide setup -b -q myUrl`
* finally the `ide` commandlet does not honor `${batch}` and `${quiet}` for the `setup` what is yet another bug.

The first and the last issue are trivial to fix. However, the CLI issue is tricky and to be honest my CLI parsing code in `devonfw-ide` is really poor. Implementing a proper CLI parser framework in bash it IMHO out of question. An options would be to use `getopts` what is a build-in shell command.
The only drawback is that it does not support long options:
https://stackoverflow.com/questions/402377/using-getopts-to-process-long-and-short-command-line-options

This is kind of a pity but I think it would be acceptable to get rid of the long options then (what means that we remove features from our CLI API - however, as we only have more or less inofficial releases yet, it would be acceptable IMHO).

The only alternative would be to add some specific function for handling the standard options and call it from every commandlet while parsing arguments. What does not work it to work on $@ and use shift within a function as each function has its own arguments context.
What would be possible is a function taking a single arg and handling the standard options, causing the according side-effects and returning wheter a standard option was handled or not.

**Comment by hohwille** [comment]
Please note:
* `-q|--quite` only suppresses output
* `-b|--batch` run in batch mode and suppresses unser input (no interfactive questions).

**Comment by hohwille** [comment]
Fixed with PR #317
