### ISSUE TITLE
Do not respect global Java installation

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#325]
As reported by @markusschuh on Yammer, the `setup` of Java may find a globally installed Java. As `devonfw-ide` is supposed to work isolated and portable and guarantee that a project can use exactly the Java version that is configured for that project, this is to be changed.

**Comment by markusschuh** [comment]
I checked, what I wrote in yammer on Dec 16, 2019. This was a comment to some issue, where the download URL for java setup was calculated as "-"  and this may have been related to a java preexisting outside of the devonfw-ide base.  As far as I can remember, it was more likely, this external java was introduced via PATH - not via explicit call via JAVA_HOME. But I may miss something.

Anyway I agree, this issue should be close for now. If there exists a specific log, when an externally found component overwrites an internal devonfw-ide software component and causes issues, another issue can be opened.

**Comment by hohwille** [comment]
Closing as invalid then.
