### ISSUE TITLE
Can't put setting_url manually in the case of swtbot automation

### ISSUE THREAD

**Issue by Rohit90700** [devonfw/ide#332]
Ref link  -https://github.com/devonfw/swtbot/issues/1

Reason of this issue creation is , if we make devon-ide setup automated, for example -

1.  Download, complete devon-ide package
2. its extraction
3. run setup.bat       ( these all things should be automated)

In the case of step 3) - run setup.bat ,its need  setting_url to be entered manually,  we cannot provide manual intervention in jenkins.
Then idea is, we will pass extra parameter to setup.bat  for swtbot automation and for regular setup if parameter is not there then it will work as it is.

**Comment by hohwille** [comment]
This is wrong. You can supply "-" as default. Can you just have a look at the existing integration tests that already solve all such issues?

**Comment by hohwille** [comment]
https://github.com/devonfw/ide/blob/master/scripts/src/test/bash/test-setup#L19
