### ISSUE TITLE
Improve CobiGen CLI with update support

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#340]
As discussed in #59 the current integration of CobiGen CLI is a little hackish.
We need a rework of the `cli` artifact of CobiGen and then can change the `cobigen` commandlet in `devonfw-ide` to replace the hack with an official installation that will also support detecting the current version and decide if the version to be installed (latest by default) is newer than the currently installed one and then do the update automatically.
We provide this kind of support for all tools except for `cobigen` in `devonfw-ide`.

**Comment by hohwille** [comment]
Did cobigen consider this for its upcoming release?
Can we fix this now?

**Comment by hohwille** [comment]
Seems that it is fixed in CobiGen. When CobiGen gets released asap, wen can resolve this and include it into `2020.08.001` of `devonfw-ide`. Fingers crossed.

**Comment by maybeec** [comment]
I will check with Mike tomorrow, but don't think it's fixed as of my last information.

**Comment by hohwille** [comment]
I have an appointment with Mike tomorrow. Hopefully, we can quickly resolve everything preventing this to be fixed.

**Comment by hohwille** [comment]
I moved to next release as this is too much on the edge. I created a PR for Mike showing how to use maven to build the *.tar.gz properly and easily. However, this will need some time and testing. Release of devonfw-ide is terminated for today EOB.

**Comment by hohwille** [comment]
See also https://github.com/devonfw/cobigen/issues/1159

**Comment by hohwille** [comment]
I had to move the milestone again as CLI is not yet updated and devonfw-ide release will be done tomorrow.

**Comment by hohwille** [comment]
Unfortunately we are not making good progress in CobiGen, so we have to move this story again.
