### ISSUE TITLE
Remove not necessary documents from ide.wiki repository

### ISSUE THREAD

**Issue by sjimenez77** [devonfw/ide#350]
With the Travis CI documentation process we are copying former documentation over the new one located at `/documentation` folder, what means that it is also being copied in the `devonfw-guide` repository.  

We should clean up the wiki repository deleting all the files, commit and push the changes, then make a minor change in the `/documentation` folder and then Travis CI will copy the necessary files only.

**Comment by hohwille** [comment]
Ah, I see so the wiki was created long time ago and still contains files that do not exist in `documentation` folder. You suggest that we cleanup the wiki and delete such files (or all files) and then do a change in `documentation` that we rebuild the wiki repository. OK, got it.

**Comment by hohwille** [comment]
Do you have a particular example? I just had a look at the full index of the wiki and could not identify any "garbarge" ?

**Comment by hohwille** [comment]
Maybe this one?
https://github.com/devonfw/ide/wiki/Redesign

**Comment by hohwille** [comment]
Should we delete this as well?
https://github.com/devonfw/ide/wiki/eclipse-plugins

How about the images?

**Comment by hohwille** [comment]
Done as requested.
