### ISSUE TITLE
Java 11.0.6 fails to launch eclipse on MacOS

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#370]
Cannot launch Eclipse with default JDK (11.0.6) on MacOS:
```
Error: could not find libjava.dylib
Failed to GetJREPath()
```
https://bugs.openjdk.java.net/browse/JDK-8213362

Workaround: `JAVA_VERSION=11.0.5_10`

See #366

**Comment by markusschuh** [comment]
At least there exists a [workaround](https://bugs.eclipse.org/bugs/show_bug.cgi?id=559482#c11), that could be used until this regression is resolved upstream.

Since there already exists such a "link workaround" within the `java` commandlet of `devonfw-ide`, it might o.k. to add this second one:

```
doRunCommand "ln -sf '../Home/lib/jli/libjli.dylib' '${DEVON_IDE_HOME}/software/jdk/Contents/MacOS'"
```

Works for me. (macOS 10.5.3)

**Comment by hohwille** [comment]
@markusschuh thanks for your hint. I would appreciate a workaround...

But your command does not work. That path does not exist. However, I could figure out, what you actually meant and intended.

But I already have `libjli.dylib` both in
* ${DEVON_IDE_HOME}/software/jdk/Contents/MacOS
* ${DEVON_IDE_HOME}/software/jdk/Home/lib/jli

So should I delete the file in the first location and symlink it to the second to make it work, or what are you actually suggesting?

**Comment by hohwille** [comment]
OK, I went through the eclipse issue and guessed what the actual fix is.
Really I have to delete a lib that is broken in the JDK release and replace it with another lib of the same name also contained in that release.
Adding this "workaround" is IMHO too dirty.
I better rollback to 11.0.5 and wait till a new release of Java 11 is out that is working fine.

**Comment by hohwille** [comment]
Done with PR #385.

**Comment by markusschuh** [comment]
It‘s not the dylib that is broken, the both files are identical. It is the implementation of openjdk - or only adoptopenjdk. Not sure - on MacOS that is not up to date with the over time slowly enhancing security requirements / package implementation guidelines of Apple.

**Comment by hohwille** [comment]
@markusschuh Thanks for the explanation. I assume there will be the one or other user that may stumble over this error when manually seeting the Java version to 11.0.6. Then I can point such user to this issue and he can find how to workaround it.

Furhter, I hope for an `11.0.7` comming soon where this problem is fixed and we will then just update to that version preventing the error and adding workarounds to devonfw-ide.
