### ISSUE TITLE
Do not setup devonfw projects by default

### ISSUE THREAD

**Issue by maybeec** [devonfw/ide#372]
### Expected behavior

As a user, I want to use the IDE for a specific devonfw project so that I can start developing easily.

### Actual behavior

Downloading the devonfw ide and installing it results in an endless processing of multiple devonfw projects like devon4j, mts, ... although I might not want to have any or just one of the projects to be checked out for editing

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Download devon ide 3.3.0
2. run setup.bat

### Comments/Hints:

It might be worth to ask the user after initialization, whether or which projects he wants to be setup.

### Affected version:

* OS: Windows

**Comment by hohwille** [comment]
@maybeec Thanks for this feedback. 
First of all devonfw-ide is fully configurable for each project via the settings git.
So in the end the question is about the default settings.
Here we have contradicting demands as it seems:
* Some people told us to work on supporting that devonfw-ide has MTS imported automatically by default
* You are now telling to do the opposite.

I am not biased for any of these choices but I think we have to discuss this with the entire community to make the decision or to even think of a compromis (e.g. asking the user or whatever).

**Comment by hohwille** [comment]
> Downloading the devonfw ide and installing it results in an endless processing 

It is not "endless" but surely it takes quite some time. We have already been discussing about omtimizing the import of multiple projects so that eclipse in not launched multiple times.

> of multiple devonfw projects like devon4j, mts, ... 

Further by default exactly two projects are imported: "devon4j" and "mts".

**Comment by maybeec** [comment]
Yes you are right and I Totally agree that the default should be devonfw focused.
I just raised this issue as currently it takes ages to setup the ide as Devon4J and mts is build and tested by maven during the process, which btw also raises errors if tests are failing.
In my opinion, tests execution should definitely not be part of the provisioning.

**Comment by hohwille** [comment]
So what I could offer as a quickfix:
* Create a fork of `ide-settings` repository without the projects configured
* Add the URL to that forked git to the documentation. Then users who do not want to setup their own settings (what is still the recommended way to start) can easily use that URL to avoid the "endless setup".

**Comment by maybeec** [comment]
Yes, that's the general way to go.
But as a general question, why to you want to run all tests of all repositories on ide provisioning? I don't see the reason and it even does not scale

**Comment by maihacke** [comment]
We could add -DskipTests=true to the initial IDE setup

**Comment by hohwille** [comment]
> We could add -DskipTests=true to the initial IDE setup

Great. Even better:
```
-DskipTests=true -Darchetype.test.skip=true
```
(as maven-archetype-plugin is unfortunately too stupid to honor `skipTests` like other testing plugins do).

**Comment by maybeec** [comment]
You could even think about `-Dmaven.test.skip=true` to simply disable compiling tests completely for IDE provisioning.

**Comment by maihacke** [comment]
So gentlemen, please decide ;-)

**Comment by maybeec** [comment]
I am not sure about the reason, why the compilation is running by maven.
The only think I could imagine is, that you want to process maven just in case, there are some maven plugins which cannot be processed by m2e automatically.
Or do you simply want to assure, that all dependencies are once loaded by maven native process?

If the latter is the case, then we should not go for `-Dmaven.test.skip=true` as this will also prevent from test dependency resolution.

**Comment by maihacke** [comment]
The reason is, that @hohwille  faced problems if all the dependecies had to be downloaded by m2e. m2e seems not to be very reliable.

**Comment by maihacke** [comment]
I revisited the code currently in  `ide` we trigger the "default" build command with `doDevonCommand build`. I do not want to change that behaviour....
My proposal is to change that to:

`doDevonCommand build dependency:resolve`

I think that is even better then skip tests, because it is exactly what we want to achieve here.

**Comment by maybeec** [comment]
Is there any chance also to make the mvn goal configured in the project setup file?
By default it could be resolve but maybe on some repos you want to run different goals to run some maven plugins which cannot be run automatically by m2e

**Comment by maihacke** [comment]
After some more analysis I recognized that changing thinks here is a bit complicated. At the moment we call devon-ides build command, which then detects if to call `mvn`, `gradle` or `npm`. I the eclipse import tries to provide parameters this will fail since it works only for `mvn`.
Making it configurable will put this complexity a bit to the user.
I'm wondering if were are on the wrong track here and used recheck if m2e is able to do the download.
What do you mean?

**Comment by maybeec** [comment]
Agree. Another more decoupled workaround could be to support a project setup configuration option to run any command at the projects root.
Thus, you don't need to interfere with the modular scriptlets of devonfw ide and anyhow you could support any more advanced project setup.

**Comment by maihacke** [comment]
`dependency:go-offline` seems to not download all required artifacts and m2e fails also so the projects in eclipse to do not compile initially

**Comment by maybeec** [comment]
That again seems to be a reason for me to better make any post clone commands configurable by project setup files. So everybody can decide what needs to be done.

**Comment by maihacke** [comment]
That was the PR provides ;-)
