### ISSUE TITLE
consider doLoadProperties for project import

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#382]
To simplify the reading of the configuration, I used the `doLoadProperties` function now to read properties configuring plugins in Eclipse (see #381 ) or VSCode (see #378).
The same approach would also make sense for the projects to clone and import.
https://github.com/devonfw/ide/blob/babca50e8df4edc076827ffbced701099ab6eb42/scripts/src/main/resources/scripts/command/ide#L323

**Comment by hohwille** [comment]
Acutally we did a design mistake here that will prevent us to do this in a downward compatible manner:
Variables use dot (`.`) as separator and bash variables may not contain this character. We would need to use the underscore (`_`).
As the feature is quite new and not widely used, we could IMHO still do the improvement.

**Comment by hohwille** [comment]
We could even grep for `git.` in the `.properties` file and if found, we could "migrate" the file by replacing `git.` with `git_` and `build.` with `build_` before the new processing.

**Comment by hohwille** [comment]
Besides I just noticed, that there is a bug in the script:
If the `projects` folder exists but is empty, it will try to read the file `*.properties` that does not exist.

**Comment by hohwille** [comment]
I could even replace `.` with `_` in the property name in `doLoadProperties`.
However, the variable `path` is used that clashes with the OS `$PATH` variable:
https://github.com/devonfw/ide-settings/blob/94c28ac128d6d2a5287d61ba34f1621d0f5e3459/projects/devon4j.properties

**Comment by markusschuh** [comment]
I suggest to keep the `.` within the `*.properties` files and replace them with `_`, when a variable is created. IMHO this is a usual convention. I have seen the same in some other tools. The difference is just, that usually the environment variables can overwrite 

Also I suggest to use different scopes for the different use cases for `doLoadProperties`. For this the function needs an additional `scope` option. If not given, the global scope is to be used - and only this one should support the `export` feature. This also would solve the class for `path` - just use a `project` scope in this case. I personally would even say, the scope should better be `devonfw_ide_projectimport`

The variable definition - if `scope` is defined - would then be

```
eval "${scope}_${key}"="${value}"
```

Btw: the `eval` should be replaced here with some more secure method, but this worth its own issue.
