### ISSUE TITLE
Avoid redundant versions of `variables` and `variables.bat`?

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#39]
For platform independence we (and all projects using devon-ide) currently have to provide and maintain `variables` "scripts" together with a redundant windows variant `variables.bat`.

With `oasp4j-ide` the support for platforms other than Windows was extremely poor. Therefore projects so far only cared about windows scripts (`variables.bat`, `ide-properties.bat`, `variables-customized.bat`). With the new `devon-ide` and cross-platform support (see #21) all this changed.

Now, it would be awesome to find a neutral way to tweak variables. Currently the `variables` are sourced and `variables.bat` are executed. This is pragmatic and allows to even unset variables or do additional initialization logic.
However, as some of these files come from external sources (git repositories) there is also the danger that some evil attacker could add script commands to do harm.

JSON or XML is most probably not the best formats to be parsed in bash or CMD but it would be nice to have an option to define the `variables` in an OS independent and neutral way. Still something like Java properties files would be an option if we could find a simple way to "parse" them in Bash and CMD without executing code. We have to be aware that we do not only declare flat properties but also arrays (`ECLIPSE_PLUGINS`) but we could also modify the eclipse commandlet to parse a comma or whitespace seprated string.

**Comment by hohwille** [comment]
* https://stackoverflow.com/questions/28830225/how-to-read-a-properties-file-which-contains-keys-that-have-a-period-character
* https://stackoverflow.com/questions/7708681/how-to-read-from-a-properties-file-using-batch-script

**Comment by hohwille** [comment]
Using properties seems to be feasible. I am proposing `${var}` variable syntax and even try to automatically convert this to `%var%` syntax on windows. Still tricky to solve, but seems as if I can make it.

**Comment by hohwille** [comment]
Merged PR #63

**Comment by markusschuh** [comment]
I dare to comment  that the provided solution does not (under bash) resolve the topic: "there is also the danger that some evil attacker could add script commands to do harm." 
In case that part is important (I'm unsure) there need to be some more input checks, like e.g.  "no space inside variable name" and "only allowed prefix is 'export'".  Shall I open a new issue on that?
