### ISSUE TITLE
Redo PATH adaptation if devon.bat is not in PATH

### ISSUE THREAD

**Issue by maybeec** [devonfw/ide#409]
As a user, I want to migrate my installed programms from one machine to another as best as possible so that I can start working again after copying all files.

Copying over the $HOME/scripts/devon.bat file causes the scripts of devonfw to believe, that everything is setup already and correctly also in the PATH.
Anyhow, the PATH will never be migrated in such cases.

So from my point of view, it would be better to actually check for the PATH to include the devon.bat script rather than checking for file existence as this might cause some strange (edge case) issues at some users.

**Comment by hohwille** [comment]
@maybeec Thanks for reporting this issue.
So in detail we are talking about this:
https://github.com/devonfw/ide/blob/cbaabfff9916f2d4f0b17741cff13ba5e699a8bf/scripts/src/main/resources/scripts/devon.bat#L13

If you want to propose the same also for bash/linux/max then it is additionally this:
https://github.com/devonfw/ide/blob/cbaabfff9916f2d4f0b17741cff13ba5e699a8bf/scripts/src/main/resources/scripts/devon#L69

So to summarize: At the moment we are copying the devon script to the users home directory and "install" it to the path. If we detect that it is already present in that location inside the users home directory, we assume that the path is already setup.
While this typically is true, in some edge-cases like yours it was not (e.g. machine was newly setup and the user home was restored from some backup.
Therefore the check could be more accurate. The drawback is that this will cost more time and currently we observe that esp. on windows the performance is already noticably slowed down by similar "improvements" like #401 
So maybe we should also question if this is done in the setup script or in the devon script.

**Comment by hohwille** [comment]
Why dont we simply do this check again on every setup?
This will not be a performance issue then but still adds a nice self-healing capabitlity.

**Comment by maybeec** [comment]
would be fine for me. it would be enough as it will give the option to simply re-execute setup.bat and it will fix it, which I feel is something intuitive

**Comment by hohwille** [comment]
@magail had the same error. Raising prio :)

**Comment by hohwille** [comment]
Fix is simple:
Move the block from
https://github.com/devonfw/ide/blob/71c62a97bc93bff4b302dc93d9d6e01ecd210943/scripts/src/main/resources/scripts/devon.bat#L22
to
https://github.com/devonfw/ide/blob/71c62a97bc93bff4b302dc93d9d6e01ecd210943/scripts/src/main/resources/scripts/devon.bat#L44

out of this IF block:
https://github.com/devonfw/ide/blob/71c62a97bc93bff4b302dc93d9d6e01ecd210943/scripts/src/main/resources/scripts/devon.bat#L19

Ideally move the following three echos inside the moved IF block:
https://github.com/devonfw/ide/blob/71c62a97bc93bff4b302dc93d9d6e01ecd210943/scripts/src/main/resources/scripts/devon.bat#L45

**Comment by hohwille** [comment]
See also #866 (slightly related setup bug).
