### ISSUE TITLE
devon ide update command fails with error while setting up vscode

### ISSUE THREAD

**Issue by ravicm2** [devonfw/ide#411]
### Expected behavior

As a user of devon-ide , i wanted to update my devon-ide . So i ran the command **devon ide update** but it fails with the error mentioned in below comment.

### Actual behavior
when i run command  **devon ide update** but it fails with the error mentioned in below comment.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. goto the location where devon-ide got installed
2. right click-> open devon cmd here
3. execute devon ide update

### Affected version:

* devon-ide : 2020.04.001
* OS: Windows
* Browser: Chrome

**Comment by ravicm2** [comment]
C:\projects\devon\devonfw-ide-scripts-2020.04.001>devon intellread ECONNRESET
Failed Installing Extensions: devonfw.devonfw-extension-pack
Failed to run command: '/c/projects/devon/devonfw-ide-scripts-2020.04.001/software/vscode/bin/code' --new-window --user-data-dir '/c/projects/devon/devonfw-ide-scripts-2020.04.001/conf/vscode' --extensions-dir '/c/projects/devon/devonfw-ide-scripts-2020.04.001/software/vscode-extensions' --force --install-extension devonfw.devonfw-extension-pack

 

******** ATTENTION ********
ERROR: Failed to run command '/c/projects/devon/devonfw-ide-scripts-2020.04.001/software/vscode/bin/code'
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 1

 

Unknown command intell

**Comment by Rohit90700** [comment]
Hi @ravicm2 , I have followed above steps to reproduce it but its working for me. Not getting any kind of issue.

**Comment by ravicm2** [comment]
i ran the command again it worked fine . Thank you @Rohit90700 for the help.
