### ISSUE TITLE
workingsets are not set correctly on eclipse import

### ISSUE THREAD

**Issue by maybeec** [devonfw/ide#412]
### Expected behavior

As an architect, I want to specify the projects to be cloned and imported into the eclipse workspace whereas the projects should be categorized into workingsets so that the developers can start with a clean and easy to recover workspace.

### Actual behavior

Workingsets are not created in eclipse.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. specify `settings/projects/your-project.properties with the following content
```
path=project
git.url=<any maven project repostiory>
git.branch=master
eclipse=import
workingsets=project
```
2. Run setup.bat and enter the settings url, referring to the settings specified in point 1
3. Start eclipse after setup

### Comments/Hints:

From my analysis, it seems the issue is with passing the information to the import job or even within the import job itself. The debug log of ide setup shows

```
Importing from /d/tmp/settings/projects/project.properties...
Project (Path: project, Url: <any maven project repostiory>, Branch: master, Eclipse: import, Workspace: main, Workingsets: project)
Pull or clone git project project...
```

So it seems the workingsets property is correctly recovered from the file and passed to the import scripts. But if you have a look at the log of the eclipse import itself, you will see that no workingsets are passed:

![Inkedimport-workingsets-eclipse-log-small_LI](https://user-images.githubusercontent.com/1427255/81160346-3bd07f00-8f8a-11ea-8a76-a8e4a981140d.jpg)

### Affected version:

* OS: Windows10

**Comment by hohwille** [comment]
Can someone say if this issue is fixed with PR #406:
https://github.com/devonfw/ide/pull/406/files

**Comment by maybeec** [comment]
yes it's working, but I think I got to know, why the import is not working for maven modules correclty building the projects. I am not sure what the SmartImport is doing, but it seems to import the project first as a "general" project, which means, that the project name is determined by the folder name the project is located in.
This behavior is different to what is expected if you import a maven project directly as this project has the name of the maven artifact id of a module.
Although the import is now working in general, it's not working as intended as the projects names are not recoverable and even there is some conflict resolution done by the import job on the project names in case you import two devon4j applications which obviously come with the same module folder names like core, api, server.

**Comment by maybeec** [comment]
Meanwhile I am thinking whether this is the right approach.
Especially for workspace setup oomph seems a lot more powerful to me. I would suggest to create a simple oomph setup description, which can be part of the settings and which will automatically be linked by the ide scripts to your eclipse installation.

**Comment by hohwille** [comment]
@maybeec we initially planned to use OOMPH and had several tries to do the import with it.
However, nobody was able to do it with that as the design of OOMPH does not fit and it is way too complicated. If we get a working PR we are happy to change asap if it is better. At the moment I am happy that @maihacke was able to find a working solution at all. For all such things please refer to #377.

For this issue itself I am closing as the initial problem is fixed. If something is wrong with "maven modules not correctly building the projects" please file a new bug. IMHO this is a bug that has nothing to do with devonfw-ide itself but with m2e being unable to reliably download artifacts and downloading an initially empty maven repo for projects like MTS requires to download half the internet. If you constantly rebuild and clean broken downloads from m2 repo it is working. However, with m2e and an empty m2 repo the entire approach is kind of nuts.
