### ISSUE TITLE
Update Eclipse to 2020-03

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#413]
As a user of devonfw-ide, I want to get the latest software and Eclipse by default so that if I setup a new IDE with default settings I can benefit of new features and bugfixes.

Eclipse has released `2020-03` release. We should update. According to my first tests, some URLs have changed or mirrors are not updated. If we really have to change download URLs in our scripts that would mean, projects configuring `ECLIPSE_VERSION=2020-03` in `devon.properties` of their settings git repository, will require a new release of devonfw-ide. We should check and test this properly and if so document this properly.

**Comment by hohwille** [comment]
According to my personal tests the new Eclipse is working fine.
@maybeec has some additional use-cases with CobiGen and p2 plugin development and discovered some problems with 2020-03.

**Comment by maybeec** [comment]
finally, after a lot of **** on my machine, I found just one issue regarding a shipped updatesite: https://www.eclipse.org/forums/index.php?t=msg&th=1080241&goto=1826713&#msg_1826713 but this is not critical maybe.

**Comment by hohwille** [comment]
Was easier than expected. The URLs did not change. Only the mirror we use was not synced with the latest release when I tested this last time. Meanwhile it works without changing URLs.

**Comment by hohwille** [comment]
Done with PR #422.
@maybeec Projects that have issues with 2020-03 can at any time configure the desired `ECLIPSE_VERSION` in their `settings/devon.properties`
