### ISSUE TITLE
Eclipse Plugin Installation not always reliable

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#414]
The installation of Eclipse plugins sometimes fails.
We should investigate this and improve stability (retry strategy?).

**Comment by hohwille** [comment]
For me CobiGen often fails to install:
```
!MESSAGE HTTP Server 'Gateway Timeout': https://dl.bintray.com/devonfw/cobigen.p2/cobigen-openapiplugin/plugins/com.devonfw.cobigen.openapiplugin_2.4.0.jar
!STACK 1
org.eclipse.ecf.filetransfer.IncomingFileTransferException: HttpComponents connection error response code 504.
	at org.eclipse.ecf.provider.filetransfer.httpclient45.HttpClientRetrieveFileTransfer.openStreams(HttpClientRetrieveFileTransfer.java:615)
	at org.eclipse.ecf.provider.filetransfer.retrieve.AbstractRetrieveFileTransfer.sendRetrieveRequest(AbstractRetrieveFileTransfer.java:885)
	at org.eclipse.ecf.provider.filetransfer.retrieve.MultiProtocolRetrieveAdapter.sendRetrieveRequest(MultiProtocolRetrieveAdapter.java:146)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.sendRetrieveRequest(FileReader.java:442)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.readInto(FileReader.java:378)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:107)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:166)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.downloadArtifact(SimpleArtifactRepository.java:720)
```

Please add other observations if you are facing such problems.

**Comment by maybeec** [comment]
I had the same with eclemma plugin and sonarlint while being connected by a customer VPN, which actually was needed.
So I don't see any way around a retry mechanism to be implemented here, which even might slow down again the installation but will make it much more reliable in non reliable networks.

**Comment by hohwille** [comment]
Does it really make sense to workaround network issues happening inside a product like Eclipse from and outside script?
How can we reliably know why the plugin installation failed after all? There are many issues where a retry is entirely pointless?
So the the expectation of a tool like Eclipse, Maven, VS Code, etc. is to be perfect and even handle such errors shouldnt we file issues in that tools itself?

I am quite unsure if we are heading in the wrong direction here...
What we could do is to track for every plugin if it was successfully installed or not. If you launch Eclipse next time and some plugins have not been properly installed, we first retry to install them. However, if a plugin was taken offline then this will annoy users every time they launch Eclipse. Surely they can manually fix this but without insights how this IDE works internally they will be lost and start hating it.
Obviously if required plugins are missing users will also be annoyed.
But if you unplug the network during installation - what should happen? I see the danger of overengineering here.
Currently we have an approach like docker. Setting up is fully automated. If something went wrong, dump your container (e.g. delete `software/eclipse` folder) and start again.

**Comment by hohwille** [comment]
If we want to improve here, my suggestion would be the following:
During setup (e.g. "devon eclipse setup") we go through all configured and active plugins every time.
For each plugin to be installed, we check if it has already been installed.
Therefore we will honor the exit-code of the installation (currently more or less ignored, except for a warning that is logged) and only on success write a file (similar to `.devon.software.version`) for each plugin (e.g. `.devon.«plugin».installed`).
This way we could retry failed plugins when setup is called again.
IMHO we should NOT retry whenever eclipse is started as this could be annoying when there is a plugin that will ALWAYS fail to be installed (see e.g. #546).

**Comment by tobka777** [comment]
Thanks @hohwille for your explanation! I will look into and create a PR.

**Comment by tobka777** [comment]
I implemented the functionality. It seems to work fine. I'm not familiar with eclipse plugins, so I created the `.devon.«plugin».installed` files to be sure.
