### ISSUE TITLE
Meta information about all available devonfw instances in a system

### ISSUE THREAD

**Issue by suprishi** [devonfw/ide#416]
As a developer of [Devon Dashboard](https://github.com/devonfw/devonfw-dashboard), I would like to have a feature where I can list all available devon instances in a system so that I can display the workspaces and the projects they hold.
Could it be possible to have some kind of meta file containing this information in a common directory (like the **username** directory available in windows, mac and linux systems). The file should be updated every time a devon instance is installed or uninstalled.

**Comment by hohwille** [comment]
Should definitively be in `$DEVON_HOME/.devon/` (`.devon` folder in users home directory).
For the design make a suggestion. IMHO I see two obvious options:
1. a subfolder `installations` with a file for each installation containing the absolute path
2. a single file containing the absolute path of each project one on each line

IMHO the 2. option makes more sense to me.

This config should IMHO be maintained during setup in `ide` commandlet:
https://github.com/devonfw/ide/blob/2a096e33af58b75427c992a363f6b40728385288/scripts/src/main/resources/scripts/command/eclipse#L24

Will you try to provide a PR?

**Comment by suprishi** [comment]
Based on what I could understand, the solution if implemented could work for future versions of Devon. We can have a single file, could be XML or JSON (preferably JSON, as it will be easier to read in a JavaScript environment), which is updated each time the user sets up a new Devon instance and also when projects and workspaces are created using the IDE. 
Currently, do we have any way of querying the instances/workspaces/projects already setup in a system so that we can get a list of earlier versions as well?

**Comment by hohwille** [comment]
> Currently, do we have any way of querying the instances/workspaces/projects already setup in a system so that we can get a list of earlier versions as well?

Nope. There is one instance that can be found in `~/.devon/home` but other instances could only be found by scanning the disc (optimized with some heuristics, e.g. assuming that all IDEs are installed in the same toplevel folder or share the same parent folder, this could be fast, but otherwise it will be pain).

So ideally some dashboard driver could start working on this story so we can push this new feature our sooner and have it spread out in the wild for future dashboards.
