### ISSUE TITLE
Create documentation how to use oracle JDK

### ISSUE THREAD

**Issue by fdcg** [devonfw/ide#457]
I cannot find any documentation on how to integrate an Oracle JDK. This should be created.

**Comment by hohwille** [comment]
Feel free to write a documentation and provide as PR.
However, due to legal restrictions from Oracle we can not provide this OOTB.
Maybe it would be possible for you and your team like this assuming all team members have a valid subscription:
https://github.com/devonfw/ide/blob/master/documentation/software.asciidoc#repository

**Comment by hohwille** [comment]
I changed from bug to enhancement as there is no bug.
As I am quite clueless how to properly resolve the issue, I flagged as `help wanted` and `waiting for feedback`.

**Comment by fdcg** [comment]
You have to maintain an Oracle JDK manually with the following steps:
1. Setup devon IDE
2. Delete content of the folder software/java
3. Install Oracle JDK in the folder software/java
4. Add file .devon.software.version with the content 8u271b09-oracle (e.g.) to the folder software/java
5. Add JAVA_VERSION=8u271b09-oracle (e.g.) to devon properties.

Alternatively ou can use an already installed Oracle-JDK:
1. Add JAVA_HOME=<path to oracle jdk> to devon properties.
2. Add JAVA_VERSION=8u271b09-oracle (e.g.) to devon properties.
3. Add file .devon.software.version with the content 8u271b09-oracle (e.g.) to the oracle jdk folder (content of JAVA_HOME)

**Comment by hohwille** [comment]
Thanks for your suggestion. I could add this to the documentation. However, this does not seem to be a real solution but rather a hack. Every user would have to do this manually. Updates would also have to be installed manually. The entire idea of `devonfw-ide` is automation and simplification of setting up and updating the IDE during the project lifecycle.

Did you read the documentation I linked:
https://github.com/devonfw/ide/blob/master/documentation/software.asciidoc#repository

If at all I would recommend to create a custom tgz file for the oracle JDK and provide this internally in your company for your team. I have no idea if OracleJDK license conditions would explicitly prohibit this.
After all my recommendation is not to use OracleJDK but OpenJDK in your IDE.
There is no difference except for security fixes that are not that relevant for local development.
What I do recommand for any professional usage is to use OracleJDK for running and operating your software in production and test environments.

**Comment by hohwille** [comment]
An alternative if really required by a larger ammount of users could be the following:
We allow some configuration variable that you could set in `settings/devon.properties` to enable OracleJDK (may also be the case if variable `JAVA_VERSION` ends with `-oracle`).
If that variable is set, then the `java` commandlet would honor this during `setup` and try to find an existing OracleJDK installation on your machine (via `JAVA_HOME`, `PATH`, etc. or by doing OS specific lookups - on Windows OracleJDKs are typically installed in the same directory on every machine) and then doing the required configuration tweaks (setting JAVA_HOME in `config/devon.properties` automatically and writing the expected `.devon.software.version` if required).

**Comment by hohwille** [comment]
I am closing this as a stale issue. All projects I have seen just use OpenJDK and there is no legal and public URL for automated download of OracleJDK.
