### ISSUE TITLE
Outdated readme.txt

### ISSUE THREAD

**Issue by fdcg** [devonfw/ide#458]
The file system/windows/cmd/readme.txt describes the OASP4J IDE. Please correct it.

**Comment by hohwille** [comment]
@fdcg thanks for reporting. Indeed an old leftover:
https://github.com/devonfw/ide/blob/ae754469d1b9203928af244c96f6cc77ab5656e8/scripts/src/main/resources/system/windows/cmd/readme.txt

IMHO we can simply delete the file. The installation has been automated so no more instructions are needed.

**Comment by hohwille** [comment]
Done.
