### ISSUE TITLE
$PATH variable not assigned globally on a Mac

### ISSUE THREAD

**Issue by suprishi** [devonfw/ide#463]
After running and completion of setup on a Mac, the PATH variable displays its value (by `echo $PATH`) in the same terminal as the setup, but in a new terminal, the value is not retained. It causes the `devon` command to be unavailable.

**Comment by suprishi** [comment]
Adding the logs of installation and subsequent `echo $PATH` for reference:

yadamhs-MacBook-Pro:~ yadamh$ cd /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003 && devon
-bash: devon: command not found
yadamhs-MacBook-Pro:devonfw-ide-scripts-2020.04.003 yadamh$ source setup
Setting up your devonfw-ide in /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003
Copying devon CLI script to your home directory...
The devon CLI script has been installed to your system.
Now in any new shell, you can call devon to setup your IDE environment variables.
You can also provide arguments to devon for advanced usage (try calling 'devon help')
Creating main workspace directory
Missing your settings at /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/settings and no SETTINGS_URL is defined.
Further details can be found here:
https://github.com/devonfw/ide/blob/master/documentation/settings.asciidoc
Please contact the technical lead of your project to get the SETTINGS_URL for your project.
In case you just want to test devonfw-ide you may simply hit return to install default settings.

Settings URL: 
Cloning into '/Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/settings'...
remote: Enumerating objects: 284, done.
remote: Counting objects: 100% (284/284), done.
remote: Compressing objects: 100% (193/193), done.
remote: Total 284 (delta 106), reused 187 (delta 48), pack-reused 0
Receiving objects: 100% (284/284), 78.90 KiB | 281.00 KiB/s, done.
Resolving deltas: 100% (106/106), done.
Copying template /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/settings/devon/conf/devon.properties to /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/conf/devon.properties.
Copying template /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/settings/devon/conf/npm/.npmrc to /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/conf/npm/.npmrc.
Copying template /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/settings/devon/conf/.m2/settings.xml to /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/conf/.m2/settings.xml.

*** Setting up java ***
Starting installation of java to /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/jdk from https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.5%2B10/OpenJDK11U-jdk_x64_mac_hotspot_11.0.5_10.tar.gz

     ..........  ///                                                            
    ..........  /////                  dd                                       
   ..........  ////////               ddd                                       
  ..........  //////////              ddd                                       
 ..........    //////////        dddddddd   eeeeeee  vvv         vvv   oooo     
..........      //////////     dddddddddd  eeeeeeeeee vvv       vvv oooooooooo  
..........       //////////   dddd    ddd eeee    eee  vvv     vvv oooo    oooo 
..........      //////////    ddd     ddd eeeeeeeeeee   vvv   vvv  ooo      ooo 
 ..........    //////////     ddd     ddd eeeeeeeeeee    vvvvvvv   ooo      ooo 
  ..........  //////////       ddd    ddd eeee            vvvvv     ooo    ooo  
   ........  //////////         dddddddd   eeeeeeeeee      vvv       oooooooo   
     .....  //////////            ddddd      eeeeee         v          oooo     
      ...  //////////                                                           

Welcome to devonfw-ide!
This product and its 3rd party components is open-source software and can be used free (also commercially).
However, before using it you need to read the license agreement with all involved licenses agreements.
With confirming you take notice and agree that there is no warranty for using this product and its 3rd party components.
You are solely responsible for all risk implied by using this software.
You will be able to find it in one of the following locations:
https://github.com/devonfw/ide/blob/master/documentation/LICENSE.asciidoc
Also it is included in /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/devon-ide-doc.pdf

Do you accept these terms of use and all license agreements? (yes/no) yes

Artifact already exists at /Users/yadamh/Downloads/java-11.0.5_10-mac.tar.gz
To force update please delete the file and run again.
Successfully extracted archive java-11.0.5_10-mac.tar.gz to updates/extracted
Successfully installed java
To be fully functional please rerun 'devon' command to update your PATH properly.
Creating symlink as workaround for Java on MacOS
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

*** Setting up mvn ***
Starting installation of maven to /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/maven from https://archive.apache.org/dist/maven/maven-3//3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz
Artifact already exists at /Users/yadamh/Downloads/maven-3.6.2.tar.gz
To force update please delete the file and run again.
Successfully extracted archive maven-3.6.2.tar.gz to updates/extracted
Successfully installed maven
To be fully functional please rerun 'devon' command to update your PATH properly.
Successfully created /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/conf/.m2/settings-security.xml
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T20:36:16+05:30)
Maven home: /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/maven
Java version: 11.0.5, vendor: AdoptOpenJDK, runtime: /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/jdk/Contents/Home
Default locale: en_IN, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

*** Setting up eclipse ***
Starting installation of eclipse to /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/eclipse from https://ftp.osuosl.org/pub/eclipse/technology/epp/downloads/release/2020-03/R/eclipse-java-2020-03-R-macosx-cocoa-x86_64.dmg
Artifact already exists at /Users/yadamh/Downloads/eclipse-2020-03-mac.dmg
To force update please delete the file and run again.
"disk3" unmounted.
"disk3" ejected.
Successfully extracted archive eclipse-2020-03-mac.dmg to updates/extracted
Successfully installed eclipse
To be fully functional please rerun 'devon' command to update your PATH properly.
Doing workarounds for MacOS quirks...
Installing eclipse plugin AnyEditTools from http://andrei.gmxhome.de/eclipse/
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
Installing AnyEditTools.feature.group 2.7.2.201911221520.
Operation completed in 12620 ms.
Installing eclipse plugin net.sf.eclipsecs from https://checkstyle.org/eclipse-cs/update/
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
Installing net.sf.eclipsecs.feature.group 8.35.0.202008141925.
Operation completed in 15522 ms.
Installing eclipse plugin com.devonfw.cobigen.eclipse.feature from https://dl.bintray.com/devonfw/cobigen.p2/
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
Installing com.devonfw.cobigen.eclipse.feature.feature.group 7.0.0.
Installing com.devonfw.cobigen.tempeng-freemarker 7.0.0.
Installing com.devonfw.cobigen.htmlplugin 7.0.0.
Installing com.devonfw.cobigen.javaplugin 7.0.0.
Installing com.devonfw.cobigen.jsonplugin 7.0.0.
Installing com.devonfw.cobigen.openapiplugin 7.0.0.
Installing com.devonfw.cobigen.propertyplugin 7.0.0.
Installing com.devonfw.cobigen.textmerger 7.0.0.
Installing com.devonfw.cobigen.tsplugin 7.0.0.
Installing com.devonfw.cobigen.tempeng-velocity 7.0.0.
Installing com.devonfw.cobigen.xmlplugin 7.0.0.
Operation completed in 65019 ms.
Installing eclipse plugin com.ess.regexutil from http://regex-util.sourceforge.net/update/
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
Installing com.ess.regexutil.feature.group 1.2.4.
Operation completed in 11366 ms.
Installing eclipse plugin com.github.spotbugs.plugin.eclipse from https://spotbugs.github.io/eclipse/
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
Installing com.github.spotbugs.plugin.eclipse.feature.group 4.1.2.r202008190436-1a2aa9d.
Operation completed in 9305 ms.
Installing eclipse plugin de.bastiankrol.startexplorer.feature from https://basti1302.github.com/startexplorer/update/
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
Installing de.bastiankrol.startexplorer.feature.feature.group 1.6.1.
Operation completed in 6040 ms.
Installing eclipse plugin org.eclipse.tm.terminal.feature from https://download.eclipse.org/tm/terminal/marketplace
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
Installing org.eclipse.tm.terminal.feature.feature.group 4.1.0.201603090932.
Installing org.eclipse.tm.terminal.view.feature.feature.group 4.1.0.201603090932.
Installing org.eclipse.tm.terminal.control.feature.feature.group 4.1.0.201603090932.
Installing org.eclipse.tm.terminal.connector.ssh.feature.feature.group 4.1.0.201603090932.
Installing org.eclipse.tm.terminal.connector.telnet.feature.feature.group 4.1.0.201603090932.
Operation completed in 33528 ms.
name=Eclipse Platform
id=org.eclipse.platform
version=4.15.0
Created script /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/eclipse-main

*** Setting up vscode ***
Starting installation of vscode to /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/vscode from https://update.code.visualstudio.com/1.44.2/darwin/stable
Artifact already exists at /Users/yadamh/Downloads/vscode-1.44.2-mac.zip
To force update please delete the file and run again.
Successfully extracted archive vscode-1.44.2-mac.zip to updates/extracted
Successfully installed vscode
To be fully functional please rerun 'devon' command to update your PATH properly.


******** ATTENTION ********
Installing plugin (devonfw.devonfw-extension-pack) into VS code...
Please wait until VSCode has successfully installed all plugins.
You may then use or close VSCode as you like.
Created script /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/vscode-main

*** Setting up node ***
Starting installation of nodejs to /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/node from https://nodejs.org/dist/v12.16.2/node-v12.16.2-darwin-x64.tar.gz
Artifact already exists at /Users/yadamh/Downloads/nodejs-v12.16.2-mac.tar.gz
To force update please delete the file and run again.
[main 2020-09-17T06:17:08.045Z] update#setState idle
Successfully extracted archive nodejs-v12.16.2-mac.tar.gz to updates/extracted
Successfully installed nodejs
To be fully functional please rerun 'devon' command to update your PATH properly.
v12.16.2

*** Setting up npm ***
npm is already installed at /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/node/bin/npm

*** Setting up ng ***
(node:41623) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:41623) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:41623) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:41623) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:41623) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:41623) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:41687) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:41687) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/node/bin/ng -> /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/node/lib/node_modules/@angular/cli/bin/ng

> @angular/cli@10.1.2 postinstall /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/node/lib/node_modules/@angular/cli
> node ./bin/postinstall/script.js

+ @angular/cli@10.1.2
added 277 packages from 207 contributors in 15.517s
Importing from /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/settings/projects/devon4j.properties...
Project is not active by default.
Skipping project - use force (-f) to setup all projects...
Importing from /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/settings/projects/mts.properties...
Project is not active by default.
Skipping project - use force (-f) to setup all projects...

Completed 
yadamhs-MacBook-Pro:devonfw-ide-scripts-2020.04.003 yadamh$ [main 2020-09-17T06:17:38.057Z] update#setState checking for updates
[main 2020-09-17T06:17:38.761Z] update#setState downloading
2020-09-17 11:48:02.222 Electron[41604:6233505] Download completed to: file:///Users/yadamh/Library/Caches/com.microsoft.VSCode.ShipIt/update.ddNcIEB/VSCode-darwin-stable.zip
[main 2020-09-17T06:18:04.854Z] update#setState ready

yadamhs-MacBook-Pro:devonfw-ide-scripts-2020.04.003 yadamh$ source setup
Setting up your devonfw-ide in /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003
Already up to date.
Configuration /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/conf/devon.properties already exists - skipping to copy from /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/settings/devon/conf/devon.properties.
Configuration /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/conf/npm/.npmrc already exists - skipping to copy from /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/settings/devon/conf/npm/.npmrc.
Configuration /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/conf/.m2/settings.xml already exists - skipping to copy from /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/settings/devon/conf/.m2/settings.xml.

*** Setting up java ***
Version 11.0.5_10 of java is already installed.
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

*** Setting up mvn ***
Version 3.6.2 of maven is already installed.
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T20:36:16+05:30)
Maven home: /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/maven
Java version: 11.0.5, vendor: AdoptOpenJDK, runtime: /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/jdk/Contents/Home
Default locale: en_IN, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

*** Setting up eclipse ***
Version 2020-03 of eclipse is already installed.
name=Eclipse Platform
id=org.eclipse.platform
version=4.15.0

*** Setting up vscode ***
Version 1.44.2 of vscode is already installed.

******** ATTENTION ********
Installing plugin (devonfw.devonfw-extension-pack) into VS code...
Please wait until VSCode has successfully installed all plugins.
You may then use or close VSCode as you like.

*** Setting up node ***
Version v12.16.2 of nodejs is already installed.
v12.16.2

*** Setting up npm ***
npm is already installed at /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/node/bin/npm

*** Setting up ng ***
angular-cli (ng) is already installed at /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/node/bin/ng
Importing from /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/settings/projects/devon4j.properties...
Project is not active by default.
Skipping project - use force (-f) to setup all projects...
Importing from /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/settings/projects/mts.properties...
Project is not active by default.
Skipping project - use force (-f) to setup all projects...

Completed 
yadamhs-MacBook-Pro:devonfw-ide-scripts-2020.04.003 yadamh$ [main 2020-09-17T06:22:28.918Z] update#setState idle
(node:42019) Electron: Loading non-context-aware native module in renderer: '/Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/vscode/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-sqlite3/build/Release/sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:42019) Electron: Loading non-context-aware native module in renderer: '/Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/vscode/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:42048) Electron: Loading non-context-aware native module in renderer: '/Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/vscode/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

yadamhs-MacBook-Pro:devonfw-ide-scripts-2020.04.003 yadamh$ devon
devonfw-ide environment variables have been set for /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003 in workspace main
yadamhs-MacBook-Pro:devonfw-ide-scripts-2020.04.003 yadamh$ echo $PATH
/Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/vscode-extensions:/Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/vscode/bin:/Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/node/bin:/Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/maven/bin:/Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/jdk:/Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/java/bin:/Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/software/eclipse:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
yadamhs-MacBook-Pro:devonfw-ide-scripts-2020.04.003 yadamh$

**Comment by suprishi** [comment]
Log results of `devon` command and `echo $PATH` in a separate terminal:

cd /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003 && devon
yadamhs-MacBook-Pro:~ yadamh$ cd /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003 && devon
-bash: devon: command not found
yadamhs-MacBook-Pro:devonfw-ide-scripts-2020.04.003 yadamh$ devon
-bash: devon: command not found
yadamhs-MacBook-Pro:devonfw-ide-scripts-2020.04.003 yadamh$ /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003
-bash: /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003: is a directory
yadamhs-MacBook-Pro:devonfw-ide-scripts-2020.04.003 yadamh$ /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/scripts
-bash: /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/scripts: is a directory
yadamhs-MacBook-Pro:devonfw-ide-scripts-2020.04.003 yadamh$ /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003/scripts/devon
devonfw-ide environment variables have been set for /Users/yadamh/Documents/devonfw-ide-scripts-2020.04.003 in workspace main
yadamhs-MacBook-Pro:devonfw-ide-scripts-2020.04.003 yadamh$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
yadamhs-MacBook-Pro:devonfw-ide-scripts-2020.04.003 yadamh$

**Comment by suprishi** [comment]
@hohwille is there anything that can be done about this issue?

**Comment by hohwille** [comment]
I am still confused what should be the actual bug here.
So let me explain how a shell like `bash` works:
If you execute a script in a shell on linux a sub-shell is created and all changes to environment variables only affect this sub-shell. When the sub-shell is terminated you are back in the original shell and you still have your unchanged environment variables like `PATH`. This is how every reasonable shell (except windows CMD works). I assume you are used to windows CMD behaviour and may be new to `bash` or `MacOS` and therefore have wrong expectations.
However, this is a fact and there is nothing in `devonfw-ide` or whereever that we can do to change this.

So what `devonfw-ide` is doing to work on linux and MacOS is to tweak your `~/.bashrc` file by adding `devon` as an alias. You can see that here:
https://github.com/devonfw/ide/blob/306881afd2d924e88d18b7950988e05a39ea96b4/scripts/src/main/resources/scripts/devon#L82

Therefore after a successful `setup` if you open a new shell the `devon` command is available as alias and will properly set your environment including `PATH`.
If you run `setup` as a command it is impossible to define the `devon` command or change the `PATH` so you afterwards need to open a new shell or just type bash (or you may restart your Mac or whatever).
You can even run `source setup` instead what you actually did in your logs and you even confirmed that then after that the `devon` command workd and the path is properly setup.

So I can only close this issue as invalid.
However, as you may have a problem that I can not identify:
Are you probably using a different shell that is neither `bash` nor `zsh`?
Or is there anything I might be missing?
So you ran `setup` properly on your Mac. Can you verify that the `devon` alias was added to your `.bashrc` and `.zshrc` files? If you open a new shell (`bash` or `zsh`) that alias needs to be available and therefore `devon` command shall work as expected.

**Comment by hohwille** [comment]
Any feedback? Can we close this or are there more insights leading to a remaining bug?

**Comment by suprishi** [comment]
Sorry for the delayed response. I think we can close this for the time being due to lack of more insights.

**Comment by hohwille** [comment]
Thanks @suprishi for your feedback. Once you get more insights or find details indicating a bug, please file a new issue.
