### ISSUE TITLE
Error for vscode plugin installation

### ISSUE THREAD

**Issue by kaustubh-gajare** [devonfw/ide#479]
Hi,
 
I have configured vscode plugin using attached properties file, but facing below issue for "devon vscode add-plugin <<plugin-name>>". I am using script version 2020.08.001.
 
```
C:\projects\specification-viewer\devonfw-ide>devon vscode add-plugin debugger-for-chrome
/c/projects/specification-viewer/devonfw-ide/scripts/command/vscode: line 169: doAddPlugin: command not found
```
Below are the contents of debugger-for-chrome.properties file,
```
plugin_id=msjsdiag.debugger-for-chrome
```

Regards,
Kaustubh

**Comment by hohwille** [comment]
So the line of the error is this one:
https://github.com/devonfw/ide/blob/1bf3124e2194b4ad4d2d9be6bc9931d64c4db69d/scripts/src/main/resources/scripts/command/vscode#L169

And indeed this is a copy&paste bug when the `vscode` commandlet has been copied from the `eclipse` commandlet - outch! Sorry for that.
There is no such function, but this one:
https://github.com/devonfw/ide/blob/1bf3124e2194b4ad4d2d9be6bc9931d64c4db69d/scripts/src/main/resources/scripts/command/vscode#L75

So we must rename the function or change the name in line 169.
