### ISSUE TITLE
SortedPropertiesTest fails on windows

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#494]
As identified in PR #487 the `SortedPropertiesTest` does not seem to work on windows.

Problem is this line:
https://github.com/devonfw/ide/blob/4328c88f087d671889b2273f34ee01fa537a7cc1/configurator/src/test/java/com/devonfw/tools/ide/configurator/SortedPropertiesTest.java#L27

We need to consider that windows EOL style also contains a carriage return that we should add as optional to this regex.

**Comment by hohwille** [comment]
So `.*` does not match `\r`.
Do we need `"#.*(\r)?\n"` then to make it work on all plattforms?
As an alternative we could retrieve the OS specific EOL sequence from Java and append it to the regex (but IMHO only if the above regex does not work).

**Comment by Gabyk0** [comment]
End-of-line code is:
- `\n` on Unix/Unix-like platform;
- `\r` on old Mac platform (pre-Mac OS X);
- `\r\n` on Windows platform.

`#.*\r?\n` (or `#.*(\r)?\n`) will work on Unix and Windows, to cover all three cases, `(\r\n|\r|\n)` should do the trick.

So, the following line will solve the issue:
 ` String result = buffer.toString().replaceAll("#.*(\r\n|\r|\n)", ""); // remove invariant date header `

**Comment by hohwille** [comment]
Done with PR #496
