### ISSUE TITLE
Enable configuration of version for yarn and angular cli (ng)

### ISSUE THREAD

**Issue by fdcg** [devonfw/ide#499]
As a user, I want to configure the version of yarn and angluar cli  (ng) so that these versions are installed via `devon ide setup`.

The actual documentation suggests, that this is possible by using the variables `NG_VERSION` and `YARN_VERSION`, but it don't work.

**Affected version:**

- OS: Windows 10
- devon IDE: 2020.08.001

**Comment by hohwille** [comment]
Done with PR #500
