### ISSUE TITLE
Unify home / Downloads directory

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#50]
The locations of HOME (`~`) and Downlods (`~/Downloads`) sometimes differ leading to duplicated downloads, devon script installation and licenses agreement. Locations are:
* `C:\Users\«user»\` for windows and git-bash on win
* `C:\cygwin[64]\home\«user»\` for cygwin
*  `/Users/«user»/` on mac
* `/home/«user»/` on linux
* Further if you are using virtualization e.g. VM Ware Fusion can "embed" your native Downloads directory from your host into the VM. So I am running windows 10 as VM inside MacOS. Then in Win10 I see my MacOS "Downloads" inside Windows Explorer. But it is redirecting to `\\vmware-host\Shared Folders\Downloads` and still there is a regular folder `C:\Users\«user»\Downloads` where `devon-ide` will put Downloads from git-bash.

This is surely nice to have. Maybe we should not bother too much about cygwin but if we want to support both git-bash and cygwin, then IMHO it would be good to only define a single location `.devon` and `Downloads` on the same machine.

**Comment by markusschuh** [comment]
Within cygwin the value of  `$(cygpath $USERPROFILE\Downloads)` could be used as download directory. I have never seen a cygwin that had  /home/<user>/Downloads pre installed.

Also I'd vote to only use any fixed prefixes like "C:\Users" if there isn't any other option. This could be for example D:\Users.  (might even be true on Capgemini Group windows image - not sure)
It is better to rely on HOME variable. On Windows no predefined %HOME% exists, so either "%USERPROFILE% or %HOMEDRIVE%%HOMEPATH% needs to be used.

**Comment by hohwille** [comment]
* For linux/mac there is no issue as there is only one concept of a home directory (`~` = `$HOME`)
* For windows CMD world everything is already solved via %USERPROFILE%
* For windows git-bash everything is also solved as it uses %USERPROFILE% as `$HOME`
* The only issue is with `cygwin` that is using a different `$HOME` directory to isolate from the windows world (e.g. if you are using tools both natively in windows and in cygwin this can lead to conflicts if that tool writes its settings to something like `~/.tool` but these settings are not portable). As we can not change the way `cygwin` is working, we still will end up with duplicate `.bashrc`, `.zshrc`, etc. We could avoid duplicating `.devon` folder in the 2 different home directory as well as `Downloads`. For `Downloads` I would strongly vote for doing so. For `.devon` I do not care much as the disc space is not an issue so it is more about simplicity/complexity here vs. there (cygwin workarounds for installation vs. uninstallation).

**Comment by hohwille** [comment]
fixed with PR #114
