### ISSUE TITLE
Remove or adjust AnyEditTools plugin update site

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/ide#514]
The current URL: http://andrei.gmxhome.de/eclipse/ is dead and needs to be removed/replaced.

###Comments:

The old Eclipse update site for all my plugins is moved now: from http://andrei.gmxhome.de/eclipse/ to https://raw.githubusercontent.com/iloveeclipse/plugins/latest/. Same way, my "home" is moved to https://github.com/iloveeclipse/plugins/wiki.

### Affected version:

devonfw-ide: 2020.12.001

**Comment by hohwille** [comment]
Thanks for the issue and the details. Even created PR #517 - awesome 👍

**Comment by hohwille** [comment]
why is github replacing first label, when I add a new label?

**Comment by maybeec** [comment]
It's replacing the auto assigned one if you assign a custom.
