### ISSUE TITLE
Allow environment variables in <project>.properties

### ISSUE THREAD

**Issue by andreasrichtercg** [devonfw/ide#515]
As an Architect,
I want to be able to use environment variables like ${USERNAME} in <project>.properties
so that I can make project import more flexible, e.g. importing from individual developer repositories (e.g. https://my-pl.pl.s2-eu.capgemini.com/gitlab/${username}/my-project.git

**Comment by hohwille** [comment]
you can already do that. Read the documentation:
https://github.com/devonfw/ide/blob/master/documentation/configuration.asciidoc#configuration

**Comment by hohwille** [comment]
If I missunderstood your feature request please be more precise but for me this is working.

**Comment by andreasrichtercg** [comment]
@hohwille Does this work for you also for environment variables not defined by devon itself, such as ${username} ?

**Comment by andreasrichtercg** [comment]
ok my fault. Working for me too. Windows does not make a difference between %USERNAME% and %username%. However it is important for devon / bash
