### ISSUE TITLE
improve release to check for SNAPSHOT versions

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#523]
`devon release` massively boosts automation of releases and makes my life easier.
However, I expect a release to have no `*-SNAPSHOT` verions in `pom.xml` files of maven projects.
Current behaviour is that `devon release` does not warn or complain in such case.

Therefore I would suggest to improve `devon release` such that it also checks for `*-SNAPSHOT` verions when it analyzes the `pom.xml` files. If a `*-SNAPSHOT` verion is present it should render a _strong_ warning and ask the user for confirmation before proceeding (and in `batch` mode fail immediately if not `force` is also active).
This feature would improve `devon release` and prevent users from creating "broken" releases saving time and despair.

**Comment by maybeec** [comment]
How about the often discussed cases where no release version is committed to git anymore? I actually would not support this feature request as it would block from such cases if it is not carefully implemented by checking resolved version numbers only.

**Comment by hohwille** [comment]
I am using CI-friendly maven and propagates it also in `devonfw` to all repos I am responsible for. It also allows to deploy some nightly build reelases with individual (e.g. timestamp-based) release versions without leaving any trace in git.
However, when I build an official release, I need to at least tag it. If a release from a tag should be rebuild it should IMHO carry the according release-number. With CI-friendly-maven all we do is chaning one additional and blody simple file (`.mvn/maven.config`). This also help to see on development (`master` branch) what version we are currently working on.

The alternative might be to have something like `dev-SNAPSHOT` once and forever in your git and never change it. When you create a release then you override the version via maven commandline parameters. I would not recommend the approach. However, I am willing to support it in `devonfw-ide`. However, I learned not to implement theoretical use-cases upfront. If users drop by with that need and might even be willing to contribute I am more than happy to support this. But if we do not even recommend this, why build it without having a real demand. Feel free to point projects to this discussion if you find some interested in this feature...

**Comment by tobka777** [comment]
I would like to develop this extension for`devon release` that warns the user when SNAPSHOT versions are used.
