### ISSUE TITLE
Provide help on "bash.exe was not found."

### ISSUE THREAD

**Issue by maybeec** [devonfw/ide#528]
As a user new to devonfw ide, I want to get guidance on installation so that I can solve

![grafik](https://user-images.githubusercontent.com/1427255/107765680-8dd0dd00-6d32-11eb-8183-831da85d0b6b.png)

on my own.

Therefore, it might be quite easy to provide a hint like 

"bash.exe was not found. Please consider installing Git from https://git-scm.com/downloads"

IF you are in a windows environment only.

I feel this is needed as some people even think it enough to install TortoiseGit for example and they will fail and don't know why.

**Comment by hohwille** [comment]
I am slightly confused. How did you reproduce this error?
We have a bash detection in `devon.bat` that does exactly what you are proposing (maybe the link needs to be updated or so):
https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/scripts/devon.bat#L68

**Comment by maybeec** [comment]
Is this code also executed on initial setup.bat?

**Comment by hohwille** [comment]
> Is this code also executed on initial setup.bat?

Sure:
* https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/setup#L5
* https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/setup.bat#L6

**Comment by hohwille** [comment]
So is this issue invalid? Or can we reproduce this?

**Comment by hohwille** [comment]
I assume that error from the screenshot surely really occurred.
My guess is that it occurred for a completely different reason:
I think `\bin\bash.exe` looks odd. Seems as bash was found in a *nix environment like cygwin as `/bin/bash` and somehow this was converted to a windows path to be executed as *.exe what obviously failed. Still I am clueless how this error could be reproduced.

**Comment by maybeec** [comment]
Just another hint maybe. I recently observed at a team member that he was running devonfw ide and always the environment was initialized using Linux paths although he was executing even windows cmd.

So might this be something related to os detection in general which seem to not work properly in some rare system setups?

**Comment by maybeec** [comment]
At least I recognized that bash became a system command since windows 10 20H2. In former versions there were multiple system setups possible basically caused by wsl installations also in different versions v1/v2 and also based on different installation paths as there was a lot of change in the process of integration of wsl into windows 10.

So just thinking out loud: possibly this may cause some of the rare system setups where os detection might not fit the detection assumptions properly.

**Comment by hohwille** [comment]
So I am leaving this open for now but without further details to reproduce, I can not make progress. Hence, I will label as waiting for feedback...

**Comment by maybeec** [comment]
I just got a new machine with Win10 20H2 which works fine as well.
(WSL2 by default enabled + git bash installed) everything fine. So let's close it for now. Seems to be an exotic case.
