### ISSUE TITLE
migration from travis CI to github actions

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#531]
Due to limitations and problems with travis-ci we want to migrate to github actions for all our devonfw repositories.

**Comment by hohwille** [comment]
Still not working:
```
 Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.971 s <<< FAILURE! - in com.devonfw.tools.ide.migrator.MigrationsTest
Error:  testMigrations(com.devonfw.tools.ide.migrator.MigrationsTest)  Time elapsed: 0.81 s  <<< ERROR!
java.nio.file.NoSuchFileException: ../settings/src/main/settings/eclipse/archetype-catalog.xml
	at com.devonfw.tools.ide.migrator.MigrationsTest.testMigrations(MigrationsTest.java:52)
```

Seems as if cloning is not happening recursive and therefore submodules are missing.

**Comment by hohwille** [comment]
https://github.com/marketplace/actions/checkout-submodules

**Comment by hohwille** [comment]
This is still not done. I just noticed in PR that we now do not have any CI in place anymore:
https://github.com/devonfw/ide/pull/540

**Comment by maybeec** [comment]
@hohwille, what exactly do you mean by that?
 
![grafik](https://user-images.githubusercontent.com/1427255/113339258-85585400-932a-11eb-8e67-9a0fec537331.png)

**Comment by hohwille** [comment]
OSSRH nexus deployment now also works.
I can close this issue as all is working now as planned.
