### ISSUE TITLE
Improve handling of aborted downloads

### ISSUE THREAD

**Issue by maihacke** [devonfw/ide#536]
During IDE updates DevonFW IDE downloads a lot of larger files.
If you interrupt a download a partially downloaded files is kept.
If you then restart the update process the script detect this files as already downloaded and tries to unzip/install it. This fails since the file isn't complete.
To resolve this you have to manually delete the file before restarting the update.
This is not clear to endusers.

We should find a better approach here.

A solution could be to download files to a temp file and rename them after download is completed.

**Comment by hohwille** [comment]
@maihacke thanks for reporting this problem.
My expectation was that `curl` and `wget` will download to a temporary file and then rename to the actual file only when the complete download has been successful.
If that is not the case, we have to implement this feature ourselves...

**Comment by maybeec** [comment]
Possibly there is something like that by adding some parameters https://www.binarytides.com/wget-automatically-resume-broken-downloads/

**Comment by hohwille** [comment]
> Possibly there is something like that by adding some parameters https://www.binarytides.com/wget-automatically-resume-broken-downloads/

Nice hint. Thanks @maybeec 
However to cite from the website:

> However even this technique has limitations, for example if the connection exists but data transfer fails, then wget will think that no data is being served and would quit.

Further this is only an answer for `wget` and by default we use `curl` as primary tool if available. Further, we do not resume any download if the file is already present.
Therefore my suggestion would be:
1. We do not use `~/Downloads` but something more specific like `~/Downloads/devonfw-ide` as download folder to prevent that manual downloads matching by name would be used (accidentally) by devonfw-ide
2. We use curl (or wget as fallback) to download the file to a temporary folder instead.
3. After successful download, we move to `~/Downloads/devonfw-ide` so only successful and consistent downloads will be there.
4. We can optionally do some nice-to-have testing with retries but I would rather waste some time downloading something from scratch if a download failed than ending up with a corrupted result and manual user interaction needed to fix this.

**Comment by hohwille** [comment]
For the record: We do not use `wget` at all. `curl` is given in the prerequesites and already comes with "git for windows" and is preinstalled on MacOS. On Linux systems IMHO both `wget` and `curl` are typically present or otherwise can be installed very easily. Therefore we never implemented any fallback to `wget.

**Comment by maybeec** [comment]
if you have large downloads and a non-stable or even slow connection, might resuming be an option?
https://www.cyberciti.biz/faq/curl-command-resume-broken-download/
