### ISSUE TITLE
Update eclipse to 2021-03

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#537]
Eclipse 2021-03 is comming out soon:
https://wiki.eclipse.org/Simultaneous_Release

We should carefully test this release and if QA is good, include this as default in our next milestone release.

**Comment by hohwille** [comment]
Release is out but not looking good:
* performance desaster
* Open type not working (nothing found, index broken?)

**Comment by hohwille** [comment]
Performance is really inacceptable. I got 1640% CPU Load at 2,7GB RAM killing my entire system.
Eclipse update is a no-go with the current release.

**Comment by tobka777** [comment]
I tested eclipse 2021-03 on my mac and I got 190% (open project) and 0.5 % (idle) CPU with 630 MB RAM. I think this is within the limits of an IDE and uses less power than my Intellij which was running at the same time.

**Comment by hohwille** [comment]
@tobka777 thank you very much for your testing and feedback.
It seems my problem was due to a rather exotic case of having a very large project base with many dependencies in combination with JPMS. However, I was able to also solve this so it is looking quite good now.
Further, I observed some popup that was suggesting me to install additional natures. I cancelled this but it came back some more times what was a little annoying but now it is gone.
The search is also working fine now and I also observed an improvement with m2e:
When I have all maven projects up-to-date and without errors and then closed eclipse and restarted it, with the old version it always came up with build errors and I had to manually do "update maven projects" running long builds to make these errors go away. This problem now seemed to have disappeared with the new version of eclipse.
Finally I observed some errors with plugin installations:
```
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.java.product -application org.eclipse.equinox.p2.director -repository https://basti1302.github.com/startexplorer/update/ -installIU de.bastiankrol.startexplorer.feature.feature.group
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -application org.eclipse.equinox.p2.director -repository https://basti1302.github.com/startexplorer/update/ -installIU de.bastiankrol.startexplorer.feature.feature.group

!ENTRY org.eclipse.equinox.p2.artifact.repository 4 1000 2021-04-20 11:02:55.800
!MESSAGE No repository found at https://basti1302.github.com/startexplorer/update/.

!ENTRY org.eclipse.equinox.p2.metadata.repository 4 1000 2021-04-20 11:02:56.086
!MESSAGE No repository found at https://basti1302.github.com/startexplorer/update/.

!ENTRY org.eclipse.equinox.p2.core 4 0 2021-04-20 11:02:56.089
!MESSAGE Unable to load repositories.
```
Hence plugin installation failed.

**Comment by tobka777** [comment]
Now I also get this error and I think I found the reason. We have to change `http://basti1302.github.com/startexplorer/update/` to `http://basti1302.github.io/startexplorer/update/`
Maybe you can change this in the PR. For we this bug was a nice test case for #414 ;).
Important is to change in ide-setting:
https://github.com/devonfw/ide-settings/blob/613e7c5964fbea716bc89d778d5167070cd2283d/eclipse/plugins/startexplorer.properties#L1
and for deprecated ide version also in ide:
https://github.com/devonfw/ide/blob/bad2355cd833b9e6f15c4292b0e7846f9efc7c07/scripts/src/main/resources/scripts/command/eclipse#L159

**Comment by tobka777** [comment]
I created a PR for ide-settings: https://github.com/devonfw/ide-settings/pull/16
