### ISSUE TITLE
Make default Eclipse version dependent on JAVA_VERSION

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#538]
When ECLIPSE_VERSION is not defined, we use the latest version that we define as a fallback and update frequently when new Eclipse releases come out.
I got feedback from projects that have set their `JAVA_VERSION` to earlier versions (1.8) but the latest eclipse version does not work with this Java version. I then tell them to also set the `ECLIPSE_VERSION` accordingly.
IMHO in general projects should have their own settings git repo and maintain versions of their tools explicitly in `devon.properties` via this git. However, we have the knowlege, what is the latest version of Eclipse that still runs with Java 1.8, etc. The projects might not easily know this. So it would still be relatively easy for us to check the `JAVA_VERSION` when we determine the default `ECLIPSE_VERSION`.
WDYT?
Too complicated and overengineered? Or greate feature that we should definetly ship?

**Comment by maybeec** [comment]
I would say nothing to invest into.
Basically I fully agree to the case that each project should get a copy of there settings git. I would vote much more to have a proper tutorial in place describing the general application of a devonfw ide to your project.

@SchettlerKoehler

**Comment by hohwille** [comment]
> I would say nothing to invest into.

All I did now is to detect a misconfiguration if ECLIPSE_VERSION does not fit with JAVA_VERSION and dump out a WARNING so the user can easily notice and fix the problem.
