### ISSUE TITLE
Improve devon release to support other versioning strategies

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#539]
We have learned from @maybeec that some projects use [ci-friendly-maven](https://maven.apache.org/maven-ci-friendly.html) but in a different way:
* `changelist` is not used
* instead the entire version is in `revision` (with or without `-SNAPSHOT`)
* some projects even have no `.mvn/maven.config` at all and always have `revision` set to `dev-SNAPSHOT`. All the versioning is done externally via tagging and by calling the build with `-Drevision=«version»` where `«version»` can be generated from date/time based information as well as build numbers, hashes, etc.

We should improve `devon release` to support those cases as well.
It is IMHO very easy:
1. When we determine the current version as only `dev-SNAPSHOT` we can ask the user what the release version should be.
2. We should also support a CLI arg to provide the (generated) version without human interaction
3. When we set the version we should be able support if `.mvn/maven.config` is not using `changelist`
4. When we set the version we should be able support if `.mvn/maven.config` is not not used at all and `dev-SNAPSHOT` is always the version for development and no change for version bumping is needed at all.
5. If we already improve this, we could allow to configure the prefix for version tags. Currently it is `release/`. Users should be able to change this including to the empty string so only the pure version number is used as tag (or to `v` that some projects seem to use). I still think our default is good but we should allow others to use something else not being forced and dictated by devonfw standards. Ideally a config file comitted to git could configure this so I do not have to use CLI args (that I might forget) nor have to even more pollute my shells with env variables.

**Comment by maybeec** [comment]
Just asking openly. Who is doing releases from any developers / architects machine in future? Do we really need this devon ide commands?
I don't see the benefit right now and even less in future. So my feeling is that such a release feature from the ide become more and more non important. So if I don't oversee any really interesting case, I barely doubt that we should invest our time in this to make it more feature rich.
We could easily say that the ci friendly concept does not match with local release scripts and therefore it's up to the project on jwo they do the releases at all.

**Comment by hohwille** [comment]
I see your point but I still see lots of project doing it not on the server side. Reasons are:
* problems dealing with secrets
* dealing with errors: what if your deployment fails due an error. In case of "connection reset/refused/timeout" you may want to repeat otherwise you may need to rework. I have never seen any automated solution being able to properly compensate such problem.

Further, I have seen very poor solutions on the server-side. I can even use `devonfw-ide` on the server-side itself in my automated job.
So I at least am a user of this and fixing such issue takes me at max 1-2 hours.
But I fully agree that this is not our focus or priority :)

**Comment by hohwille** [comment]
BTW:
```
Setting version of your project to 0.2.2-SNAPSHOT ...
updated .mvn/maven.config
from: -Drevision=0.2.1
to: -Drevision=0.2.2
```

So that is what currently happens when you are not using `changelist`.

**Comment by hohwille** [comment]
I have implemented this as PR #541 and leave it open for today so someone might review or raise concerns...

**Comment by hohwille** [comment]
BTW: regarding the best-practices it is not the best idea to choose `dev-SNAPSHOT` as it is not compliant with JPMS:
```
[ERROR] error: bad value for --module-version option: 'dev-SNAPSHOT'
```
So instead `0-SNAPSHOT` would be a better option as best-practice and recommendation.

**Comment by hohwille** [comment]
Also implemented support for `0-SNAPSHOT`. PR done.

**Comment by maybeec** [comment]
> problems dealing with secrets (including PGP keys - tell me how to automate a OSSRH deployment with GHA? -It is IMHO impossible so we still have the need in devonfw or any other OSS project deploying to maven central)

technical no problem, you can again use the secrets and pass it to the build or make the build taking it from environments.

> dealing with errors: what if your deployment fails due an error. In case of "connection reset/refused/timeout" you may want to repeat otherwise you may need to rework. I have never seen any automated solution being able to properly compensate such problem. A server-side automated solution is awesome if it works but pain if it does not and you have no way to step in.

that should be an exceptional issue anyhow, where in any case an expert needs to have a look, who can then simply try re-executing the documented commands from the build configuration on his machine or rerun it directly on GHA if it's an indeterministic break. Therefore, I voted to simply not concentrate on it as this scenario will not serve to a lot of persons at all.

**Comment by maybeec** [comment]
but as it's already implemented, let's go ahead.
