### ISSUE TITLE
VSCode user-data-dir shall be part of workspace config

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#553]
With PR #543 I figured out that we did a mistake with the VSCode user-data-dir:
* we have the philosophy of a multi-workspace concept that allows to launch IDEs for a particular workspace with an isolated config that should not have side-effects on other workspaces or IDE-installations
* we have the concept to synchronize and manage such workspace configurations in a homogenous way using our workspace synchronizer

However, we currently configure the user data dir (`--user-data-dir`) to `${DEVON_IDE_HOME}/conf/vscode` what turns out as a mistake. Instead we should relocate this directory inside the workspace folder. My suggestion would be `${WORKSPACE_PATH}/.vscode/.userdata`.

This willl also allow us to manage configs in userdata with our existing (single) synchronization for vscode config (see devonfw/ide-settings#15).

**Comment by sjimenez77** [comment]
I fully agree with the user data folder change. Indeed, for every workspace configuration VS Code adds this `.vscode` folder with specific settings and setup that even takes care of enabled and disabled extensions, debug configurations and so on. 

We only need to ensure that this config can be updated for new workspaces, although I think that it should not be a problem at all.

**Comment by hohwille** [comment]
Jep, this `.vscode` folder was already managed by devonfw-ide's [configurator](https://github.com/devonfw/ide/blob/master/documentation/configurator.asciidoc#configurator).
By changing the userdata dir to be inside this folder, we now are able to also manage specific userdata settings like disabling the telemetry (see https://github.com/devonfw/ide-settings/blob/master/vscode/workspace/update/.vscode/.userdata/User/settings.json).
I therefore consider your commend as a kind of approval to my PR #553 and will merge this.
