### ISSUE TITLE
Setting up Jenkins locally with 'devon jenkins setup' throws error

### ISSUE THREAD

**Issue by suprishi** [devonfw/ide#565]
### Expected behavior

As a devon user, I want to setup Jenkins locally with `devon jenkins setup`

### Actual behavior
When I run `devon jenkins setup` it throws an error stating: `Unable to access jarfile path/to/jenkins.war` followed by `Failed to run command: java -jar 'path/to/jenkins.war' --version`

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Open the terminal
2. Run the command `devon jenkins setup`

### Affected version: 2021.04.001-SNAPSHOT

* OS: Windows

**Comment by hohwille** [comment]
Problem comes from PR #547 as download dir has changed. Will fix asap.
