### ISSUE TITLE
jasypt support for password encryption and decryption

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/ide#575]
As a developer, I want password encryption feature so that I can add my encrypted password (eg: database password) in application.properties 

eg:
```
devon jasypt encrypt masterPassword=secret input=passwordToBeencrypted
```

Refer the below documentation:
https://github.com/devonfw/devon4j/blob/master/documentation/guide-configuration.asciidoc#security

**Comment by hohwille** [comment]
I found a small obstracle and posted for help:
https://stackoverflow.com/questions/67422151/how-to-execute-maven-goal-but-ignore-potential-local-pom-xml
