### ISSUE TITLE
Settings repos with branches

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/ide#585]
As a person who manages the IDE settings repo, I want my team members to be able to select a branch of a settings repo during the installation so that subteams can use variations of common settings and to test new settings before making them public to the team.

Possibly the branch could be encoded into the settings URL e.g. https://github.com/devonfw/ide-settings.git#branch

**Comment by hohwille** [comment]
Typically I do that manually or simply fork & merge, but surely a nice-to-have-improvement that would make sense.

**Comment by tobka777** [comment]
Now we support also branches in the settings url.
I tested with:
- https://github.com/devonfw/ide-settings.git#maybeec-patch-1
- https://github.com/devonfw/ide-settings.git
