### ISSUE TITLE
Default eclipse version not downloadable

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/ide#616]
### Expected behavior

As a IDE user, I want the IDE to be usable with the default settings so that I can easily try the IDE without effort.

### Actual behavior
ERROR: Failed to download eclipse-2021-03-windows.zip from https://ftp.osuosl.org/pub/eclipse/technology/epp/downloads/release/2021-03/R/eclipse-java-2021-03-R-win32-x86_64.zip
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 22

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Run setup in the latest version with default settings

### Comments/Hints:
The version 2021-03 is the default version in the current IDE release and is not downloadable anymore. See https://ftp.osuosl.org/pub/eclipse/technology/epp/downloads/release/

### Affected version:

* OS: Windows

**Comment by hohwille** [comment]
@SchettlerKoehler thanks for this feedback and creating the issue 👍 
Indeed a painful bug. However, the assumtion of a reasonable OSS project like e.g. Eclipse was from our perspective that downloads of releases remain stable. If that is not the case, we are in general trouble. We can fix this for future versions but such things will break old releases spread in the wild and there is pretty much nothing we can do about it.
Eclipse has messed it!

**Comment by hohwille** [comment]
IMHO the best approach would be to get in touch with the maintainer of `ftp.osuosl.org` and ask what happened here and if it is possible to get the release back online.

**Comment by maybeec** [comment]
@hohwille, I think the main issue here is, that eclipse community has a registry of providers of downloads. These are universities and other founders of download capabilities. The download button at the eclipse website is a load balancer, which checks providers for the download to be available. Here it seems, that devonfw ide is requesting contents from just one of these download servers, which is not agreed to contain all data all the time. 

**For a quickfix as devonfw ide is not working at all with default settings, we should switch the download url to a working one.**

In addition, we should create a ticket to switch the download URL to a more stable one (possibly even trying to use the load balancer of the eclipse download button on the eclipse site)

**Comment by isandesh1986** [comment]
Only one mirror link is working when downloading. Contacting Eclipse mirror support.

**Comment by isandesh1986** [comment]
I am able to access all the links from this mirror. All of them are working. https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2021-09/R/eclipse-java-2021-09-R-win32-x86_64.zip&format=xml

**Comment by isandesh1986** [comment]
I think the below two links which will use the best available mirror would have been a stable choice. WDYT?

https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2021-09/R/eclipse-java-2021-09-R-win32-x86_64.zip&r=1

https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2021-03/R/eclipse-java-2021-03-R-win32-x86_64.zip

**Comment by maybeec** [comment]
Hi @isandesh1986, have you tried these links with the shell script? There is a lot tournarounds with the download tool, possibly curl or similar used in devonfw ide script (please check). If this works out, we should go with the stable link. But please give it a try.

**Comment by Rick-T** [comment]
Hello @maybeec,
I have tried installing eclipse by adding one of the links proposed by @isandesh1986 to the [eclipse command](https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/scripts/command/eclipse).

It worked just fine. I was able to continue my installation successfully. If you want I can create a PR with the changes I made.
