### ISSUE TITLE
IDE does not support JDK 17

### ISSUE THREAD

**Issue by malberer** [devonfw/ide#618]
**Expected behavior**

As a IDE user, I want the IDE to be usable with JDK 17

**Actual behavior**
When configuring JAVA_VERSION=17.0.1 in devon.properties the installer tries to download
local download_url="https://github.com/AdoptOpenJDK/openjdk${major_version}-binaries/releases/download/${jdk_folder}/OpenJDK${major_version}U-jdk_x64_${os}_hotspot_${software_version}${extension}"

However since July 2021 Adopt moved to Eclipse and is now called Temurin and is available e.g. at https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz

**Steps to reproduce (bug) / Use Case of feature request (enhancement)**

    Run setup in the latest version with JAVA_VERSION=17.0.1

**Affected version:**

    OS: Windows

**Comment by hohwille** [comment]
For the record: PR #630 does not properly solve the problem of choosing the correct download URL:
```
ERROR: Failed to download java-8u312b07-mac.tar.gz from https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jdk_x64_mac_hotspot_8u312b07.tar.gz
```
With PR #643 this is fixed (just tested).

**Comment by hohwille** [comment]
For the record:

> Run setup in the latest version with JAVA_VERSION=17.0.1

There is no java release `17.0.1` so this is setting a wrong expectation.
What works for me with the latest release is something like this:
```
JAVA_VERSION=17.0.1_12
```
