### ISSUE TITLE
IDE, eclipse default version is not getting downloaded.

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/ide#626]
refer the issue https://github.com/devonfw/ide/issues/616
`ftp.osuosl.org` is configured in IDE, but the mirror is not maintaining the version we are looking for.  

#616 is giving the below error:

```
End-of-central-directory signature not found. Either this file is not
a zipfile, or it constitutes one disk of a multi-part archive. In the
latter case the central directory and zipfile comment will be found on
the last disk(s) of this archive.
```

Looks like the configured mirror is not working. Need to configure an alternate.

**Comment by hohwille** [comment]
Fixed with PR #641
