### ISSUE TITLE
Automated test required for the mirrors

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/ide#628]
Github workflow required to check the liveliness of mirrors list kept on Github.
Refer: https://github.com/devonfw/ide/issues/627

**Comment by hohwille** [comment]
Thanks for filing this issue. See also here:
https://github.com/devonfw/ide-mirrors/issues

**Comment by hohwille** [comment]
Is #663 a duplicate of this issue or vice versa?

**Comment by sujith-mn** [comment]
Yeah.. duplicate issue.
Closing this.
