### ISSUE TITLE
terminal control codes aren't processed when using Cobigen-cli with devon prefix

### ISSUE THREAD

**Issue by LarsReinken** [devonfw/ide#631]
### Expected behavior

As a cobigen user, I want to use cobigen-cli.

### Actual behavior
![image](https://user-images.githubusercontent.com/9500956/142628584-cd9fd2f7-5ec5-4a50-ab8a-bcbf667d6fd6.png)

### Steps to reproduce (bug) / Use Case of feature request (enhancement)
1. install devonfw ide
2. Open a devon cmd using your context menu inside your project
2. Run: "devon cobigen" to install CobiGen CLI
3. Run "devon cobigen generate"

### Related/Dependent Issues
https://github.com/devonfw/cobigen/issues/1404

### Comments/Hints:
after updating the path by running "devon". Using just cobigen doesn't produce these characters, neither is the output coloured.
using git bash instead of devon-cmd works fine.

### Affected version:
release 2021.04.002

**Comment by hohwille** [comment]
Thanks for the feedback. However, I am quite clueless how to solve this:
We are piping the output of cobigen-cli in bash that itself (in case of the error) is processed by a windows CMD terminal that is unable to understand the color control output produced by cobigen.
Maybe we could try to detect if we are inside a CMD terminal and in such case try to pass a parameter to cobigen disabling colors. However, if so then is devonfw-ide in charge at all here or is this a bug of cobigen?
Does it work when cobigen is invoked from CMD without being prefixed by `devon` script?

**Comment by hohwille** [comment]
I just tested this without `devon` as wrapper command and get the same output.
So if you consider this as a bug it is a bug of CobiGen or MSDos/CMD but not devonfw-ide and cannot fix it here.
