### ISSUE TITLE
Helm integration

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/ide#636]
As a devon IDE user, I want to have Helm available in the devon IDE so that I and my team can easily ramp up our development environment and we are using the same and correct versions of the tool.

Acceptance criteria:

- [x] There is a new commandlet that allows to install and launch Helm from the CLI
- [x] The new commandlet is a wrapper for Helm CLI
- [x] Helm can be installed automatically (during setup via settings) as well as via the commandlet call
- [x] During the installation process I get information about the current status of the installation
- [x] The new commandlet is documented on the website
- [x] Helm can be installed and used together with any of the devon IDE standard tools without negative interference
- [x] Helm is integrated in a way that complies with the multi-tenancy of the devon IDE
- [x] Add licence documentation

**Comment by Bene90** [comment]
Hi @CREITZ25, could you update that story? What ACs have been achieved so far?

**Comment by CREITZ25** [comment]
Hi @Bene90, many things are done, but at the moment the workflow doesn't work due to spellcheck errors. Still open is to check Mac and Linux, and License.asciidoc has to be enhanced. It is not done because the pull request with terraform stopped by spellcheck errors, too.

**Comment by Bene90** [comment]
Hi @CREITZ25, ok - could you create seperate tasks for these open bugs / ToDos?
