### ISSUE TITLE
GraalVM integration

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/ide#638]
As a devon IDE user, I want to have GraalVM available in the devon IDE so that I and my team can easily ramp up our development environment and we are using the same and correct versions of the tool.

Acceptance criteria:

- [x] There is a new commandlet that allows to install and launch GraalVM from the CLI
- [x] The new commandlet is a wrapper for GraalVM CLI
- [x] GraalVM can be installed automatically (during setup via settings) as well as via the commandlet call
- [x] During the installation process I get information about the current status of the installation
- [x] The new commandlet is documented on the website
- [x] Other tools are able to find GraalVM (GRAALVM_HOME is set)

Sprint 2 ACs:
- [x] GraalVM integration is wokring with Windows.
- [x]  GraalVM can be installed and used together with any of the devon IDE standard tools without negative interference - also tested
- [x] GraalVM is integrated in a way that complies with the multi-tenancy of the devon IDE(independently of the used system (mac, linux, windows).

Sprint 3 ACs:
- [x] Add licenec documentation

**Comment by hohwille** [comment]
A problem with GraalVM is that it contains commands like `java` in the bin folder. Adding both Java and GraalVM to your path will cause chaos.
It is fine to just install it to `software/extra/graalvm` so it is not automatically added to the path.
However, then we can only do the following:
* export some variable `GRAALVM_HOME` - actually best if the user does this via his `devon.properties` manually?
* provide `graalvm` commandlet as wrapper script delegating to GraalVM (e.g. `devon graalvm java ...`).

**Comment by Bene90** [comment]
@tobka777 Please keep in mind that the lincence documentation must be mentioned.
@hohwille What is the right location for it? (Also relevant for Rancher Desktop, HELM, Terraform)

**Comment by tobka777** [comment]
@Bene90 I did this already! 
See Commit https://github.com/devonfw/ide/pull/698/commits/f892a28190d8c58310f189985661866b2326363d and https://github.com/devonfw/ide/pull/698/commits/6e90e9664f3360508c94af2d8c8294ee20c813da
