### ISSUE TITLE
Eclipse error message after devonfw installation

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/ide#646]
### Expected behavior

As a devonfw CobiGen Eclipse developer, I expect my freshly installed IDE to run without any issues.

### Actual behavior
When installing the latest devonfw right after starting Eclipse, following error pops up:

`Initializing Eclipse Error reporting System has encountered a problem
An internal error occurred during: "Initializing Eclipse Error Reporting System".
Could not find satisfiable constructor in org.eclipse.epp.internal.logging.aeri.ide.notifications.MylynNotificationsSupport`

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Install a fresh devonfw
2. Start Eclipse using the eclipse-main.bat

### Affected version:

* devonfw 2021.04.002

**Comment by maybeec** [comment]
Is it just occurring after running the project setup cobigen command?

**Comment by MikeSchumacherCapgemini** [comment]
It happens immediately upon installing the devon ide.

**Comment by jan-vcapgemini** [comment]
Adjusted title and description because the issue appears right after the standard installation too.

**Comment by maybeec** [comment]
I so had the same right after devonfw ide default installation

**Comment by hohwille** [comment]
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=558840
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=552193

**Comment by hohwille** [comment]
I can confirm this bug is still present.
It is IMHO a bug in eclipse itself or more likely a bug in one of the default plugins we add on installation.
As this error popup comes on every start of Eclipse, this bug is really nasty and needs to be fixed asap.

**Comment by hohwille** [comment]
```
org.eclipse.e4.core.di.InjectionException: Could not find satisfiable constructor in org.eclipse.epp.internal.logging.aeri.ide.notifications.MylynNotificationsSupport
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:412)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:330)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
	at org.eclipse.epp.internal.logging.aeri.ide.IDEStartup.initializeIdeContext(IDEStartup.java:104)
	at org.eclipse.epp.internal.logging.aeri.ide.IDEStartup.access$0(IDEStartup.java:73)
	at org.eclipse.epp.internal.logging.aeri.ide.IDEStartup$1.run(IDEStartup.java:62)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by hohwille** [comment]
according to the eclipse bug [558840 - Remove AERI from CDT target platform](https://bugs.eclipse.org/bugs/show_bug.cgi?id=558840) this issue comes if AERI is present/loaded/on-classpath.

As that issue is closed my first guess is that we have some plugin included, that still contains AERI.

**Comment by hohwille** [comment]
Uninstalling freemarker solved the problem.

**Comment by hohwille** [comment]
I simply disabled freemarker what seems to resolve the problem.

**Comment by hohwille** [comment]
Retested with fresh installation and confrimed to work fine now.
