### ISSUE TITLE
Fix and re-enable some eclipse plugins

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#648]
As discussed in #604 , we had to temporary disable some eclipse plugins that are currently broken.
This issue is about fixing the issues (e.g. changing update-site URL, getting in touch with the plugin maintaners, etc.) and then re-enabling the plugins:
* [spotbugs](https://github.com/devonfw/ide-settings/blob/master/eclipse/plugins/spotbugs.properties)
* [tmterminal](https://github.com/devonfw/ide-settings/blob/master/eclipse/plugins/tmterminal.properties)
* test all other disabled plugins manually and fix if they are broken

**Comment by hohwille** [comment]
See also #673 that is closely related.

**Comment by hohwille** [comment]
From my eclipse log:
```
!MESSAGE www.genuitec.com
!STACK 0
java.net.UnknownHostException: www.genuitec.com
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
```
Regarding [devstyle](https://github.com/devonfw/ide-settings/blob/master/eclipse/plugins/devstyle.properties).

**Comment by Akuhana** [comment]
Plugins that are not working:

- devstyle
- eclipsepde
- github
- soapui
- swtbot
- tmterminal

**Comment by Akuhana** [comment]
- **devstyle** has dependency issues
- **eclipsepde** has dependency issues
 **github** (Egit) Plugin is already installed with a new installation of Eclipse and thus gives an error when trying to install it again.
- **SoapUI** the plugin update site is nowhere to be found, as all of the plugin update sites are out of date. [SoapUI eclipse plugin](https://www.soapui.org/docs/soapui-for-ide/eclipse/eclipse-plugin/)
- **swtbot** has to have eclipsepde plugin installed. When eclipsepde is installed, the swtbot installation works without any issues.
- **tmterminal** is already installed with eclipse ide and therefore can't be installed on top of that.

**Comment by hohwille** [comment]
so for the easy ones:
* `tmterminal` fine, included in Eclipse now and working OOTB. Simply delete `tmterminal.properties` from `ide-settings` and we are done here.
* SoapUI can be installed via ZIP download from https://www.soapui.org/downloads/soapui/soapui-os-older-versions/#soapui-eclipse-plugin as local archive. You can try to implement that if update-site ends with `.zip` then you do download via CURL instead and then start the director with this strange local ZIP URL that eclipse produces from local selected zip archive. If that works great - also change update-site to this ZIP download URL of latest release and we are done. Otherwise simply add the ZIP link I put here in this bullet list in the `eclipse.asciidoc` under a note about the plugins for SoapUI so if someone is interested in SoapUI he can install manually. In this case also remove the `soapui.properties` file.
* `eclipsepde` and `swtbot` are here only for CobiGen. If we are clueless how to get this working we might simply have to delegate this to the cobigen team who has a real interest and motivation to get this working again. If they also don't, we can simply remove those properties files as well.
* `devstyle` is used by quite some developers for dark-mode. Please try if you can add the missing dependencies as additional `.properties` files in the settings (ordered lexicographical before `devstyle.properties`) and see if we can get it fixed. Otherwise we have to give up here and also put a short description into `eclipse.asciidoc` how to install it via marketplace with direct marketplace link that can be opened and drag&dropped into eclipse.
* `github` - seems the mylyn integration is gone. If we can not find it somewhere also delete the `github.properties`. This was a nice feature for devonfw developers but projects do not typically need this.

**Comment by hohwille** [comment]
I deleted some plugins that are not relevant for regular projects or gone/broken anyways.
We could delete more but as they are inactive they do not hurt.
Hence closing this stale issue.
