### ISSUE TITLE
devon npm setup ignores a given version

### ISSUE THREAD

**Issue by fdcg** [devonfw/ide#667]
### Expected behavior

As a user, I want to define the variable `NPM_VERSION` as described in the documentation so that this defined version is installed with `devon npm setup`.

### Actual behavior
The variable `NPM_VERSION` is ignored and there is only the NPM version installed with node available. 

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1.  Install node with `devon node setup`
2.  Call `npm -version` and notice the version
3.  Set the variable `NPM_VERSION` to a different version.
4.  Call `devon npm setup`
5.  Call  `npm -version`

The output of step 5 is the same as of step 2.

### Affected version:
* Devon scripts: 2020.08.002
* OS: Windows
* Browser: independent

**Comment by hohwille** [comment]
npm command itself just delegates to node:
https://github.com/devonfw/ide/blob/1b535ea2c19881a4795e93569e3452c861742df9/scripts/src/main/resources/scripts/command/npm#L21

Seems that someone thought an implicit requirement is to get latest npm insode node command:
https://github.com/devonfw/ide/blob/1b535ea2c19881a4795e93569e3452c861742df9/scripts/src/main/resources/scripts/command/node#L39

IMHO I did not design this part.
Can someone still shed a light into this?

IMHO the expecation of @fdcg is correct and building on this I would say:
1. node command should not install or update npm at all
2. only npm command should do that
3. npm command should honor `${NPM_VERSION}` variable to be consistent with all other commandlets. Only if that variable is undefined it should fallback to `latest`.

**Comment by hohwille** [comment]
@fdcg It seems that npm version is somehow bundled with node version. So the safest and easiest approach would be to maintain `NODE_VERSION` in your project that in the end will both manage `node` and `npm` for your project as these two bundled together are guaranteed to work in together fine.

Do you happen to need a specific `npm` version AND a speciifc `node` version that do not come together?
We could easily add some logic to `npm` commandlet that checks for `NPM_VERSION` and if present does the exact installation of that `npm` version regardless of the `node` version used. However, this approach could easily end in a setup that is broken.

**Comment by hohwille** [comment]
I created a simple fix with PR #672
@fdcg Is this solving your needs?
