### ISSUE TITLE
Alternative for regex-util

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#673]
In #653 we have disabled regex-util as it does not provide an update site with HTTPS download.

For regex-util we could simply try some alternatives:
* https://marketplace.eclipse.org/content/devutils
* https://marketplace.eclipse.org/content/quickrex

So with this story the following should be done:
1. install and try the above linked eclipse plugins (and any other alternative for regex testing that you can find)
2. test each plugin candidate for regular expression tests including group matching feedback, etc.
3. for the best candidate determine the according update site URL and ensure it is HTTPS
4. add an new plugin properties file for it here: https://github.com/devonfw/ide-settings/tree/master/eclipse/plugins
5. provide your changes as PR
6. link the PR in this issue.

**Comment by hohwille** [comment]
I have tested `devutils` and it sucks as you have to press `match` button every time you change your input and if there is some syntax error in your regex the button does nothing and you get not feedback.
However, QuickRex is great and a good replacement for regexutil.

**Comment by Akuhana** [comment]
PR https://github.com/devonfw/ide-settings/pull/27
