### ISSUE TITLE
Generalize MacOS app workaround

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#683]
From PR #682:

On MacOS for Java a workaround is needed:

* java follows MacOS app conventions but not standards of other OS
* that is has a folder Contents that contains subfolders Home and MacOS
* the expected layout of a JDK is within Contents/Home that also contains the bin folder that contains java, etc.
* However, the entire structure is required for the JDK to work
* as a workaround devonfw-ide detects this and then renames the java folder to jdk and creates a symlink java pointing to jdk/Contents/Home so everthing else works as expected.
* as a result also the jdk folder is put on the PATH. This does not cause real harm but it should also be prevented.

We have the same issue also with other apps on MacOS. For Eclipse and IntelliJ we simply create launch scripts ourselves at the expected locations but this only works for "single command tools". For things like GraalVM (see GraalVM integration #638) we will have the same problems as with Java.

Therefore I am thinking about moving this workaround from the java commandlet to the doInstall function and make it generic. Maybe instead of renaming the folder inside software it could be moved to a generic subfolder: something like the new extra folder in software but to avoid conflicts it needs to be a different one - maybe just `macos` or if we expect similar workarounds also for other OS something like `internal` also excluded from the path.

When we implement this we have to consider existing installations. Ideally the old `software/jdk` folder will be deleted/archived if `devon java setup` is executed.

**Comment by tobka777** [comment]
I implemented a general workaround for java and graalvm.
For Eclipse, Intellij, VSCode we have to look for another solution. Now they use a script to pass the arguments.
