### ISSUE TITLE
Evaluate Docker desktop alternatives

### ISSUE THREAD

**Issue by JokeFrels** [devonfw/ide#689]
As a project that has no license for docker desktop, I want to have an alternative docker variant as part of devon-ide so that I can still use devon-ide to set up docker.

Tasks:

Evaluate existing alternatives (the already existing evaluation can be used as a basis)

- Docker in wsl
- Lazydocker in wsl
- Rancher desktop
- Podman-minikube 
- Other alternatives?

Acceptance criteria:

- There is a presentation similar to the current one that compares at least the alternatives listed above (more alternatives are welcome) by sensible criterias like performance, installability, ...
- There is a well-founded recommendation which of the alternatives should be added to the devon IDE standard tools
- The chosen alternative works with Kubernetes
- The chosen alternative works in  VPN
- On the website there is an explanation why the alternative was chosen (similar information as in the presentation) (Ascii-Format)

AC Sprint 3

- Documenation is done.
- .ppt is saved within the public devonfw channel

**Comment by maybeec** [comment]
#634 is the same or simply the epic accordingly?

**Comment by JokeFrels** [comment]
> #634 is the same or simply the epic accordingly?

#634 is the epic to which this story belongs to

**Comment by JokeFrels** [comment]
A sensible criterium is that other cloud tools (Helm, Terraform) should be compatible with the chosen solution

**Comment by hohwille** [comment]
Meanwhile RancherDesktop 1.0.0 (end of beta) has been released.
I already switched from DockerDesktop to RancherDesktop.
It already can ship with docker, kubectl and helm:
<img width="306" alt="Screenshot 2022-01-28 at 16 56 06" src="https://user-images.githubusercontent.com/1923119/151579482-7903395c-bad9-419c-ad2f-4787d8c7015d.png">

**Comment by maybeec** [comment]
RancherDesktop will also come witn docker compose automatically in v1.1.0

**Comment by cinnamon-coder-hub** [comment]
Great news regarding the VPN-problem with WSL2! The solution mentioned by @SchettlerKoehler  and @nikiOstrov,  after working for @SchettlerKoehler, also seems to work for me. So CLI-Tools like docker-cli or podman should be able to e.g. pull images as expected with this package. Maybe this tool should become part of #690? What do you think @hohwille?

**Comment by albertdb** [comment]
> Great news regarding the VPN-problem with WSL2! The solution mentioned by @SchettlerKoehler and @nikiOstrov, after working for @SchettlerKoehler, also seems to work for me. So CLI-Tools like docker-cli or podman should be able to e.g. pull images as expected with this package. Maybe this tool should become part of #690? What do you think @hohwille?

Could you please share the solution for VPN?

**Comment by SchettlerKoehler** [comment]
https://github.com/sakai135/wsl-vpnkit

**Comment by albertdb** [comment]
> https://github.com/sakai135/wsl-vpnkit

Thanks, the one we saw time ago. I thought there was another way. Anyway, thanks!

**Comment by Bene90** [comment]
Hello @nikiOstrov and @cinnamon-coder-hub ,
this task can be closed, right?

**Comment by cinnamon-coder-hub** [comment]
> Hello @nikiOstrov and @cinnamon-coder-hub , this task can be closed, right?

It depends. As far as I know one of the acceptance criteria isn't fulfilled yet. I would want to write down the explanation why Rancher-Desktop  was choosen as alternative together with the documentation for the commandlet implementation of Rancher-Desktop, after implementing the commandlet, or by the end of next week.

**Comment by Bene90** [comment]
@cinnamon-coder-hub, 
i thought implementing the commandlet is part of #690?

**Comment by hohwille** [comment]
Done and documented with PR #720
