### ISSUE TITLE
Nightly test for devon IDE installation

### ISSUE THREAD

**Issue by JokeFrels** [devonfw/ide#691]
As a devon IDE user I want to install the devon IDE without any difficulties to be able to start right away. Since there can be changes, there should be an automated nightly test with GitHub Actions.

Acceptance criteria:
- [x] new workflow in github actions for a nightly test (per week)
- [x] per os (win, mac old, mac M1, linux) use one workflow
- [x] run build check

**Comment by hohwille** [comment]
Please also note that I have already created test-infrastructure:
https://github.com/devonfw/ide/tree/master/scripts/src/test/bash

This is already executed on every build except on windows that does not easily have bash and shellcheck support:
https://github.com/devonfw/ide/blob/master/scripts/pom.xml#L139

IMHO the new tests should be added here and we should find a way to classify tests that should run on every build and others that only run nightly as they are greedy and expensive.

**Comment by maybeec** [comment]
You can simply declare bash as the shell also on windows for github actions. It will run automatically in git bash.

**Comment by hohwille** [comment]
> You can simply declare bash as the shell also on windows for github actions. It will run automatically in git bash.

I am taking about native builds on windows (e.g. `mvn install` in Windows CMD). As maven-exec-plugin is used, windows says that the bash script is not a native executable and fails. However, I was able to install shellcheck in my gitbash on windows...

**Comment by maybeec** [comment]
Don't get the problem, sry. Could you share a link to a broken build in this regard?

**Comment by hohwille** [comment]
> Don't get the problem, sry.

If you run `mvn clean install -Pintegration-test` on windows, you can reproduce the problem:
https://github.com/devonfw/ide/blob/master/scripts/pom.xml#L139

**Comment by alfeilex** [comment]
I get an error in Windows because the shell cannot process the `/test-*` command correctly. As a result, no test is run.
https://github.com/devonfw/ide/blob/master/scripts/src/test/bash/all-tests#L11

**Comment by alfeilex** [comment]
Currently there are no github runner options for m1 devices 
https://github.com/actions/virtual-environments/issues/2187

You would have to host the VM yourself.
