### ISSUE TITLE
Docker setup not working

### ISSUE THREAD

**Issue by EduardKrieger** [devonfw/ide#695]
### Expected behavior

Installing Docker with the command `devon docker setup`

### Actual behavior

The download of the Docker setup.exe fails. Curl returns a 403 error.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Install devonfw-ide
2. Install docker with `devon docker setup`

### Comments/Hints:
Powershell output:
```
PS C:\Users\mkaltenp\Desktop\devonfw_workspace\workspaces\main> devon docker setup
Trying to download docker-stable-windows.exe from https://desktop.docker.com/windows/stable/amd64/Docker%20Desktop%20Installer.exe
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 303 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
curl: (22) The requested URL returned error: 403
Failed to download https://desktop.docker.com/windows/stable/amd64/Docker%20Desktop%20Installer.exe with exit code 22



******** ATTENTION ********
ERROR: Download of docker in version stable failed after trying 1 mirror(s).
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
```

### Affected version:
Tested on 
* OS: Windows native and with a Windows VM 
   1. devonfw-ide version from Windows VM: 2021.12.004, 2022-01-13_08.52.08
   2. devonfw-ide version from native Windows. 2021.12.005, 2022-01-28_20.55.45

**Comment by tobka777** [comment]
Thanks @EduardKrieger! I created a PR, that should fix it.

Note: Should be tested!

**Comment by hohwille** [comment]
Thanks to all! Great 👍 
I merged it.
@EduardKrieger could you retest - should work now... If so please let us know so we can close.

**Comment by EduardKrieger** [comment]
Download of the file is working now, but still I am facing this issue:
```
PS C:\Users\Administrator\Desktop\Projects\workspaces> devon docker setup
Trying to download docker-stable-win.exe from https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  490M  100  490M    0     0  26.5M      0  0:00:18  0:00:18 --:--:-- 29.7M
Installating Docker Desktop for Windows...
/c/Users/Administrator/Desktop/Projects/scripts/command/../functions: line 77: /c/Users/Administrator/Downloads/devonfw-ide/: Is a directory
Failed to run command: /c/Users/Administrator/Downloads/devonfw-ide/

******** ATTENTION ********
ERROR: Failed to run command /c/Users/Administrator/Downloads/devonfw-ide/
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 126
```

**Comment by tobka777** [comment]
Oh, a new error! Now I found a bug related to changes for #641.
The variable `filename` was undefined. So I set the filename.
Furthermore, I removed the code block for the variable `ts`, which was no longer used.

https://github.com/devonfw/ide/pull/647/files#diff-35cfd8f3199645d7984ff9b1f48fb8131a420865239e5e0e1c0e1a5dceb36c3eL53

**Comment by EduardKrieger** [comment]
I have tested the fix on Windows 10 VM and Docker Desktop installation now working for me.

**Comment by hohwille** [comment]
Tomorrow we can discuss if we do a bugfix release right away or if we wait also for #634
