### ISSUE TITLE
Support for windows terminal

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#701]
As a devonfw-ide user on windows, I want to make use of microsoft Terminal app so that I get all my shell sessions as tabs in one window.
Therefore devonfw-ide should notice if Terminal app is installed on windows and if so instead of installing the regular context menu entries like "open devonfw CMD here" install something like this but with full devonfw-ide integration setting up the environment:
https://github.com/lextm/windowsterminal-shell
So as a result in Windows Explorer I would have a menu "Open devonfw Terminal here" with the sub-menu options:

* cmd ([x] open new tab, [x] getting variable, [ ]implementation)

**Comment by hohwille** [comment]
Please note that for the current approach we have `*.reg` files that get imported into the registry:
https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/system/windows/cmd/devon-cmd.reg

We can keep this approach and do not have to copy the linked powershell script solution but just get some inspirations from there.

**Comment by hohwille** [comment]
TDB: Maybe if we rather recommend to use git-bash and get used to it, we should focus on that. The context-menu with sub-menu-entries appears nice in the first place but requires additional attention/selection each time so a single flat entry might still be the best option for power-users. Also we should add a small devonfw icon for our menu entry to make it fancy.

**Comment by hohwille** [comment]
See also https://github.com/microsoft/terminal/issues/7452

**Comment by CREITZ25** [comment]
I have installed Windows the Terminal and created registry keys for the context menu. Applications can be started in different tabs, and now the correct directory has to be given and the devon configuration file has to be executed at start.
