### ISSUE TITLE
Eclipse installation in devonfw IDE fails (ClassNotFoundException)

### ISSUE THREAD

**Issue by arne-busch** [devonfw/ide#704]
### Expected behavior

As a developer, I want to install Eclipse in my devonfw IDE using the command "devon eclipse".

### Actual behavior

Download and installation of Eclipse start, but the installation of the plug-in "startexplorer" fails due to a ClassNotFoundException (see details below).

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Install devonfw IDE (version from 2022-02-14)
2. Open CMD
2. Execute command: devon eclipse

### Comments/Hints:

In case it's relevant: During the installation of the devonfw IDE it was not possible to set the following settings URL "https://github.com/devonfw/ide-settings". Retrying and leaving the settings URL empty, however, seemed to have worked.

This is the console output after executing "devon eclipse":
```
C:\xxx\yyy\git\zzz>devon eclipse
You are not inside a devonfw-ide installation: /c/xxx/yyy/git/zzz
Starting installation of eclipse in version 2021-12 to C:\xxx\yyy\devonfw-ide/software/eclipse
Trying to download eclipse-2021-12-java-win32.zip from https://ftp.osuosl.org/pub/eclipse/technology/epp/downloads/release/2021-12/R/eclipse-java-2021-12-R-win32-x86_64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  306M  100  306M    0     0  1451k      0  0:03:36  0:03:36 --:--:-- 1921k
Successfully extracted archive eclipse-2021-12-java-win32.zip to updates/extracted
Successfully installed eclipse
To be fully functional please rerun 'devon' command to update your PATH properly.
Installing eclipse plugin AnyEditTools from https://raw.githubusercontent.com/iloveeclipse/plugins/latest/
Installing eclipse plugin net.sf.eclipsecs from https://checkstyle.org/eclipse-cs-update-site
Installing eclipse plugin com.devonfw.cobigen.eclipse.feature from https://devonfw.com/cobigen/updatesite/stable/
Installing eclipse plugin de.bastiankrol.startexplorer.feature from https://basti1302.github.io/startexplorer/update/
Error: Could not find or load main class com.devonfw.tools.ide.configurator.Configurator
Caused by: java.lang.ClassNotFoundException: com.devonfw.tools.ide.configurator.Configurator
Failed to run command: java -cp 'C:\xxx\yyy\devonfw-ide/scripts/lib/devonfw-ide-configurator-2021.12.005.jar:C:\xxx\yyy\devonfw-ide/scripts/lib/javax.json-1.1.4.jar:C:\xxx\yyy\devonfw-ide/scripts/lib/javax.json-api-1.1.4.jar' com.devonfw.tools.ide.configurator.Configurator -t C:\xxx\yyy\devonfw-ide/settings/eclipse/workspace -w C:\xxx\yyy\devonfw-ide/workspaces/main -v C:\xxx\yyy\devonfw-ide/settings/eclipse/workspace/replacement-patterns.properties -u

******** ATTENTION ********
ERROR: Failed to run command java
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 1
```

### Affected version:

* OS: Windows 10

**Comment by ssarmokadam** [comment]
@arne-busch I have tested it with latest release(2021.12.005) and I am not able to reproduce this issue.

**Comment by arne-busch** [comment]
I just restartet and tried it again, this time by executing "devon eclipse" in the devonfw IDE installation folder. Now it works. When I do the same, Eclipse also starts, but it's a different version. It seems I've still got another (older) version of the devonfw IDE on my computer. Maybe having multiple devonfw IDEs in different versions on a system is the problem.

**Comment by hohwille** [comment]
@arne-busch devonfw-ide is exactly designed to support multiple projects using different versions of tools on the same computer.

```
Caused by: java.lang.ClassNotFoundException: com.devonfw.tools.ide.configurator.Configurator
```

This has nothing to do with Eclipse itself. In your `scripts/lib` folder you will find a file `devonfw-ide-configurator-<version>.jar` that is called here. As it seems this is not found on your machine. Either is is simply deleted or got currupted for whatever reason or so. That JAR file should contain the class `com.devonfw.tools.ide.configurator.Configurator` and all JARs in this lib folder are put on the classpath when running the eclipse configurator.

Could you double check your installation?

**Comment by arne-busch** [comment]
I checked my installation and it seems fine (at least now). Eclipse starts now, even in a second installation for another project. Maybe getting rid of the old devonfw IDE version or a restart helped somehow. At least for now everything seems to work. Thanks for your help!
