### ISSUE TITLE
intellij makes devon ide update fail

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#717]
### Expected behavior

As a user, I want to update my IDE according to the latest settings so that my tools are in the correct version

### Actual behavior

when I run `devon ide update`, I get this error:

```
******** ATTENTION ********
ERROR: Failed to verify installation of IntelliJ (command)
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 1
ERROR: command 'intellij setup' failed with exit code 1
```

As this terminates the entire update process, I am unable to proceed with my actual update.
Since I need to update a custom tool there seems to be now way to proceed (for a regular tool, I could run `devon <tool> setup` to trigger the update.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. install devonfw-ide (`setup`)
2. install intellij (`devon intellij setup`)
3. run `devon ide update`

### Comments/Hints:

1. We should fix the actual bug with intellij update
2. We should consider to resume the update on the error of an individual tool (maybe with `doAskToConfirm`)

Workaround: delete `software/intellij` before running `devon ide update`.

### Affected version:

* 2021.12.005

**Comment by HobbyFlo** [comment]
i can report the same issue. A hacky fix for me was to disable the version check:
open the "intellij" file in an editor. Comment line 47 like this     #doRunCommand "command -v idea" "verify installation of IntelliJ". Then run the setup again.

**Comment by hohwille** [comment]
@HobbyFlo thanks for the feedback.
I plan a release soon and we should have a fix for this (at least a quickfix for intellij verification).

**Comment by tobka777** [comment]
I have removed the command statement. ``idea` is not defined in Windows and the installation paths vary depending on the operating system. Furthermore, a JSON is always output afterwards, which contains the version and more details.
Additionally, the version is always output if it was not called with silent, because then `doInstall` was executed.
