### ISSUE TITLE
unzip: command not found (create doUnzip function)

### ISSUE THREAD

**Issue by Bene90** [devonfw/ide#734]
```
unzip: command not found
```

On some systems the `unzip` command is not preinstalled (including linux distros like Ubuntu)

**Comment by hohwille** [comment]
As a solution we plan to add `doUnzip` to `functions`.
In addition to calling `unzip` command with given params, it should first check if `unzip` command is present.
If not, the command should be installed according to current OS (or if not possible the user should be informed to install it manually giving an URL with instructions).
