### ISSUE TITLE
 Update Rancher Desktop install documentation 

### ISSUE THREAD

**Issue by Bene90** [devonfw/ide#745]
As user i want to have an udpated documentation about the Rancher Desktop installation.

During the installation of rancher desktop, the install guide of rancher desktop pops up. The user might be confused by that.
That behaviour should be documented within the documentation (e.g. with screenshots).

Related to #690.

**Comment by hohwille** [comment]
See remaining comments in #768

**Comment by cinnamon-coder-hub** [comment]
Regarding [this comment](https://github.com/devonfw/ide/pull/768#pullrequestreview-1038408301) I recently commited a fixed version of docker.asciidoc to include these useful remarks in docker.asciidoc., so the issue should be closeable after a review of this commit.

**Comment by hohwille** [comment]
Closing as suggested above.
