### ISSUE TITLE
Wrapper: Test MAC OS specific

### ISSUE THREAD

**Issue by Bene90** [devonfw/ide#748]
As developer i want to test MAC OS specific behavouir.
This refers to the following tasks:
#712
#690
#711
#713

**Comment by sarahffm** [comment]
#690: Not OK. Installation works but wrapper command doesn't. [Bug](https://github.com/devonfw/ide/issues/906) added.

**Comment by CREITZ25** [comment]
#711 AWC Cli Integration for Mac is implemented

**Comment by sarahffm** [comment]
#712: The Azure CLI installation requires pip which is not yet implemented for MacOS.
