### ISSUE TITLE
Prompt default value for Settings URL

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/ide#749]
As an end user, I want a default value for SETTINGS so that I'll not be confused while installing IDE.

While installing IDE, SETTINGS:  is bit confusing the new user.  A default url can be given in bracket, then the user can press enter and continue with installation.

**Comment by hohwille** [comment]
@sujith-mn thanks for your feedback. I assume you are talking about this prompt during setup:
```
Missing your settings at /d/projects/test/settings and no SETTINGS_URL is defined.
Further details can be found here:
https://github.com/devonfw/ide/blob/master/documentation/settings.asciidoc
Please contact the technical lead of your project to get the SETTINGS_URL for your project.
In case you just want to test devonfw-ide you may simply hit return to install default settings.

Settings URL:
```

So are you suggesting that the last line should be like this instead?
```
Settings URL [https://github.com/devonfw/ide-settings.git]:
```

**Comment by hohwille** [comment]
FYI: Please note that the use-case for real project usage of devonfw-ide is to provide a project specific settings URL. However, devonfw-developers or people who want to use devonfw-ide just to get some tools installed easily just want to hit return here.
So at least when it makes you think before you hit enter this is actually desired and intended :)

**Comment by sujith-mn** [comment]
Yes.. This way the new user does not need to think about SETTINGS_URL while trying. Also they'll get a hint that it is a git URL.

**Comment by hohwille** [comment]
Was trivial to implement in 1 minute. Crated PR #776
