### ISSUE TITLE
DoD for IDE

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#750]
As a devonfw-ide developer, I want an IDE specific definition of done (DoD) so that I know exactly what to do and how to do it in order to satisfy the standard requirements and acceptance-criteria (of a new commandlet).

The [devonfw DoD](https://github.com/devonfw/.github/blob/master/CONTRIBUTING.asciidoc#definition-of-done) is a good starting point but too generic. Instead we should copy it to our `ide` repo in a specific `documentation/DoD.asciidoc` file and adjust it to our specific needs. Example points to add for new commandlets/tools are:
* Added license information for new tools to link:LICENSE.asciidoc[] ...
* Added `«commandlet».asciidoc` if new commandlet `«commandlet»` was added and include it in link:scripts.asciidoc[] ...
* Tested that new commandlet installs tool locally to `software` folder and allows multi-tenancy so multiple installations of `devonfw-ide` can exist in parallel on the same computer with different versions and configurations of the same tool without interfering each other.
* ...

**Comment by tobka777** [comment]
Note also at the acceptance criteria in #637
