### ISSUE TITLE
Present a form in website to customize devonfw-ide

### ISSUE THREAD

**Issue by suprishi** [devonfw/ide#752]
As an admin, I want a form which will help me customize devonfw-ide.

The form can be pre-loaded with the default values (the softwares that we bundle by default) and provide additional fields for other softwares and their versions. On submit, user will be able to download the file with all their softwares listed. Additionally, if possible, user will be taken to a forked repo of ide-settings to update the file changes.

**Comment by hohwille** [comment]
Closing stale issue. I would rather see dashboard for this purpose rather than creating our own dynamic web tool that IMHO will not easily work 7x24.
