### ISSUE TITLE
Restructure ide document as per new structure

### ISSUE THREAD

**Issue by ssarmokadam** [devonfw/ide#753]
Below is the latest structure

![image.png](https://images.zenhubusercontent.com/607d2b8a591b7cfff555c394/c1ffaca2-5b60-4940-90f0-d18fe1338d2a)

![image](https://user-images.githubusercontent.com/16591200/174770128-b2f11853-e04a-4281-bed4-68d4f37ea2d8.png)

**Comment by hohwille** [comment]
Closing analog to #757 #758 #820 and #759
