### ISSUE TITLE
Restructure Ide introduction

### ISSUE THREAD

**Issue by ssarmokadam** [devonfw/ide#754]
Restructure Ide introduction:
1. What is devonfw-ide?
2. Why we need devonfw-ide?

This content should appear on devonfw-ide landing page and not as sub-menus.

**Comment by ssarmokadam** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-62825383d986530011ae300d/issues/devonfw/ide/754?planning-poker) with ZenHub @sujith-mn @suprishi

**Comment by suprishi** [comment]
PR link: https://github.com/devonfw/ide/pull/763

**Comment by suprishi** [comment]
Updated PR as per review comments from team review.
