### ISSUE TITLE
devonfw-ide quickstart page

### ISSUE THREAD

**Issue by ssarmokadam** [devonfw/ide#755]
Devonfw-ide quick start:

1. pre-requisite for devonfw-ide
2. how to download devonfw-ide
3. Install devonfw-ide - extract zip and run setup.bat file
4. Description what softwares are getting installed
5. Run sample commands using devonfw command shell.

**Comment by ssarmokadam** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-62825383d986530011ae300d/issues/devonfw/ide/755?planning-poker) with ZenHub @sujith-mn @suprishi

**Comment by sujith-mn** [comment]
Links in devonfw.com home page needs to be handled while restructuring..
