### ISSUE TITLE
devonfw-cli commandlet

### ISSUE THREAD

**Issue by ssarmokadam** [devonfw/ide#756]

**Comment by ssarmokadam** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-62825383d986530011ae300d/issues/devonfw/ide/756?planning-poker) with ZenHub @sujith-mn @suprishi

**Comment by sujith-mn** [comment]
Seems like this document may not required any change, this can be used as it is.
