### ISSUE TITLE
Get ide ready for your project -Step1

### ISSUE THREAD

**Issue by ssarmokadam** [devonfw/ide#757]
Short description for roles such as admin and developer
(Playlist for admin)
- **Customize** devonfw-ide for your project
![image.png](https://images.zenhubusercontent.com/607d2b8a591b7cfff555c394/2698d571-7319-435a-b943-de90b88c6f36)

**Comment by hohwille** [comment]
we have ideas for creating a video tutorial on this or even reviving dashboard to guide you through the process.
As this issue is open and stale for a very long time, I will finally close it.
