### ISSUE TITLE
Get ide ready for your project -Step2

### ISSUE THREAD

**Issue by ssarmokadam** [devonfw/ide#758]
![image.png](https://images.zenhubusercontent.com/607d2b8a591b7cfff555c394/b4cb66e5-132c-4ddb-899e-30d51a0e62f4)

**Comment by ssarmokadam** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-62825383d986530011ae300d/issues/devonfw/ide/758?planning-poker) with ZenHub @sujith-mn @suprishi

**Comment by sujith-mn** [comment]
Discussion pending with Jorg.

**Comment by hohwille** [comment]
Same as #757:
we have ideas for creating a video tutorial on this or even reviving dashboard to guide you through the process.
As this issue is open and stale for a very long time, I will finally close it.
