### ISSUE TITLE
devonfw-ide FAQ

### ISSUE THREAD

**Issue by ssarmokadam** [devonfw/ide#759]
come up with few FAQ useful for user.

**Comment by hohwille** [comment]
do we have any first questions? Adding an empty FAQ as AsciiDoc or so seems rather pointless.
IMHO we should simply use the discussion tab on github for this as it perfectly addresses such needs.
Do you agree and we can close this issue (or if you prefer you could add a link to the discussion to the README to make it more explicit)?

**Comment by hohwille** [comment]
https://github.com/devonfw/ide/discussions/925

**Comment by hohwille** [comment]
FAQ discussion had been created. No questions yet arrived.
Closing this issue after 1 year of no progress.
