### ISSUE TITLE
Nightly check of ide-mirrors

### ISSUE THREAD

**Issue by tobka777** [devonfw/ide#799]
As a devon IDE user, I want no errors in the installation process so that I can quickly use the installed tools.

We should create a github action to validate changes and PRs in https://github.com/devonfw/ide-mirrors:

files should be terminated by newline
ext-mappings should be present in every subfolder
ext-mappings should be compliant with urls (urls entities should all end with ${ext} or all end with an extension «extension» where ext-mappings contains one line *=«extension» )

Acceptance criteria:
- [ ] mirrors does not contain CRLF (\r or \r\n) -> only \n
- [ ] call urls in mirror with replacements of architecture, os, ext and check if page exists (no 404 error)
- [ ] check for win, macos, linux
- [ ] check for configured versions of devon-ide

**Comment by mustafaokyay** [comment]
Looks like a duplicate of #821

**Comment by hohwille** [comment]
This story is done thanks to @arexhepi7 
I will check on the next PR that comes for mirrors that everything is working as expected.
Maybe I will also find some time to create some broken PRs to test that it reveals according problems.

**Comment by tobka777** [comment]
Already merged: https://github.com/devonfw/ide-mirrors/pull/27
