### ISSUE TITLE
Website PDF generation failure on restructuring devonfw-ide documents

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/ide#820]
If you want to do small changes for existing doc snipplets (asciidoc files), simply go ahead and create a small PR. Once merged, the changes will be reflected on github, website and in next PDF generation.

For actual restructurings I understood that we need new entry paths (e.g. devonfw-ide for developer, devonfw-ide for project admin). So in that case, I would suggest to simply create new AsciiDoc files in documentation that address this and link to other existing places in the documentation. Now, we have the following entry-points into the devonfw-ide documentation

https://github.com/hohwille/ide/blob/master/documentation/devonfw-ide.asciidoc IMHO used by the website

https://github.com/hohwille/ide/blob/master/documentation/devonfw-ide-doc.asciidoc IMHO used to generate PDF of devonfw-ide release

https://github.com/hohwille/ide/blob/master/README.asciidoc used as entry point on github directly.
So you should be able to include additional things into the website without adding them into the PDF if needed.

Acceptance Criteria
----------------------
Verify the PDF generation is working
Add new document and verify the PDF generation.
Note: restructuring of document will be verifed later.

**Comment by sujith-mn** [comment]
As per the discussion with Jorg, the existing PDF genreation will be executed on IDE. Then a modification will be done and again do the PDF generation to see any issue.

**Comment by hohwille** [comment]
I am also closing this issue after one year without further progress.
IMHO also the title is missleading as currently the website generation has no such failure - there was a PR introducing such failure that was never merged.
