### ISSUE TITLE
github actions for QA of ide-mirrors

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#821]
We should create a github action to validate changes and PRs in https://github.com/devonfw/ide-mirrors:
1. files should be terminated by newline
2. `ext-mappings` should be present in every subfolder
3. `ext-mappings` should be compliant with `urls` (`urls` entities should all end with `${ext}` or all end with an extension «extension» where `ext-mappings` contains one line `*=«extension»` )

**Comment by hohwille** [comment]
Replacement for https://github.com/devonfw/ide-mirrors/issues/3 as I am closing the issue tracker in mirrors.

**Comment by mustafaokyay** [comment]
Is a duplicate of #799. Description and comments are migrated to #799

**Comment by mustafaokyay** [comment]
Closed because it is a duplicate of #799. Description and comments are migrated to #799

**Comment by hohwille** [comment]
Aspect `1.` was not explicitly listed in #799 ACs and they have also never been checked.
This aspect 1. is still not implemented and @CREITZ25 just found bugs because of that... :(
