### ISSUE TITLE
Integration of github CLI

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#833]
As a devonfw-ide user, I want to have github CLI integrated so that I can directly create repositories, secrets, workflows, etc. via commandline and make use of automation.

Acceptence criteria:
* See [DoD](https://github.com/devonfw/ide/blob/master/documentation/DoD.asciidoc)

**Comment by hohwille** [comment]
https://github.com/cli/cli

**Comment by Akuhana** [comment]
Referencing a PR for ide-mirrors https://github.com/devonfw/ide-mirrors/pull/32

**Comment by Akuhana** [comment]
PR for the GitHub CLI implementation https://github.com/devonfw/ide/pull/890
