### ISSUE TITLE
Setup not working if SettingsURL not ending with .git

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#835]
### Expected behavior

As a devonfw-ide user, I want to be able to setup my project with any working GIT Settings URL so that I can get started without problems and my project has the flexibility to use any kind of git service with whatever URL formats.
I would even expect any valid GIT URL including local ones (https://stackoverflow.com/questions/978052/how-can-i-make-my-local-repository-available-for-git-pull) to work without issues.

### Actual behavior

The setup tries a CURL download instead of a git clone if the GIT URL does not end with `.git` ending up in strange errors:
```
./setup /d/projects/devonfw/settings
Setting up your devonfw-ide in /d/projects/test
Installing devon autocompletion
Starting installation of devonfw-ide-settings in version  to /d/projects/test/settings
Trying to download settings from /d/projects/devonfw/settings
curl: (3) URL using bad/illegal format or missing URL
Failed to download /d/projects/devonfw/settings with exit code 3

******** ATTENTION ********
ERROR: Failed to download  from /d/projects/devonfw/settings
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 3
```

Please also see that with git the URL is working fine:
```
git clone /d/projects/devonfw/settings
Cloning into 'settings'...
done.
```
### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. download devonfw-ide
2. extract the content to new folder
3. run setup and supply a valid git URL that does not end with `.git`

### Comments/Hints:

Problem comes from here:
https://github.com/devonfw/ide/blob/94a9ff7d46bc6d38146075d531206dfa7908b36f/scripts/src/main/resources/scripts/command/ide#L99

Why don't we just call `doGitPullOrClone` instead of `doDownload`?

Some additional magic to support branch encoded in URL was placed inside `doInstall` instead of `doGitPullOrClone`.
https://github.com/devonfw/ide/blob/86b690280cbc8def707570c1384957283eebc223/scripts/src/main/resources/scripts/functions#L784

I would strongly question this approach and suggest to move that magic to `doGitPullOrClone` and simply call this directly to clone or update `settings` or `mirrors` instead of calling `doDownload` that is IMHO just wrong here.

### Affected version:

* Version 2022.04.003
* OS: Windows, Linux, and Mac

**Comment by hohwille** [comment]
Note: According to git history this problem was there from the start. I did not trace it back to `oasp4j-ide` but simply assume that already I made this wrong so we can already decide it should be changed as suggested in this issue.

**Comment by CREITZ25** [comment]
The problem is not the ending .git, the problem is if we start ./setup in one directory, and the settings directory is not in the same directory. The ./setup <settings> command means to create another devonfw IDE instance. This is easily done with the devon ide create <directory> command.

**Comment by hohwille** [comment]
> The problem is not the ending .git, the problem ---

For the record: This was a misunderstanding that we could clarify.
