### ISSUE TITLE
Make README more intuitive for a new potential user

### ISSUE THREAD

**Issue by Akuhana** [devonfw/ide#886]
As a potential devonfw user, I want to be able to know what devonfw is and how to install it quickly from the main GitHub page so that I don't have to search how to do it. Currently, there's a video with an explanation, but for the people that want a quick overview of the project, they have to search for this information either on the devonfw website (which is not linked on the main GitHub page) or search through the different documentation pages. If the user decides that a quick explanation is not enough, then he can go to the specific documentation site, which explains it in more detail.

As someone, who finds the GitHub page first and has no idea of the project or that a project website exists, I want:
- A link to the devonfw website (In the about section and in the README.md file)
- To see a 2-3 line introduction of the project
- Quickly download the devon ide via download links (The same links that are available on the devonfw website for linux/macos/windows). Currently the devonfw website shows a different way of installing devon than the GitHub documentation. Either have both ways explained or unify them.
- Get explanation where to find more information on certain topics (link to docs)

A good example of such would be the [TensorFlow](https://github.com/tensorflow/tensorflow) page on GitHub.

**Comment by tobka777** [comment]
@hohwille what do you think if we extend the GitHub readme also with regard to Constributing and Licence, as it is often done. So that we follow the headings like here https://www.makeareadme.com/

I would suggest the following headings: devonfw-ide, Installation, Documentation, Contributing, Licence

**Comment by hohwille** [comment]
> I would suggest the following headings: devonfw-ide, Installation, Documentation, Contributing, Licence

Fully fine. The suggested example [TensorFlow](https://github.com/tensorflow/tensorflow) has a similar structure.
The `LICENSE.asciidoc` is already linked but as you suggest this should be in a separate section at the end.
(FYI: Github also shows the project license on the right bar together with about, readme, code of conduct, etc.)
