### ISSUE TITLE
Check VSCode Plugins

### ISSUE THREAD

**Issue by alfeilex** [devonfw/ide#887]
### Expected behavior

As a user, I want install default vs code plugins without any errors 

### Actual behavior

There is an error to install [devonfw-extension-pack.properties](https://github.com/devonfw/ide-settings/blob/1e7e0ede083acb1b06e55d2eebc536096c548f76/vscode/plugins/devonfw-extension-pack.properties#L1) and the functionality of the other plugin [lombok](https://github.com/devonfw/ide-settings/blob/1e7e0ede083acb1b06e55d2eebc536096c548f76/vscode/plugins/lombok.properties#L1) also needs to be tested. It contained errors too.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Activate each plugin [here](https://github.com/devonfw/ide-settings/tree/1e7e0ede083acb1b06e55d2eebc536096c548f76/vscode/plugins)
2. Run `devon vscode setup` on Windows

### Comments/Hints:
Error output for [devonfw-extension-pack.properties](https://github.com/devonfw/ide-settings/blob/1e7e0ede083acb1b06e55d2eebc536096c548f76/vscode/plugins/devonfw-extension-pack.properties#L1) : `Installing extensions...
Installing extension 'devonfw.devonfw-extension-pack'...
(node:10184) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use Code --trace-deprecation ... to show where the warning was created)
connect ETIMEDOUT 13.107.6.175:443
Failed Installing Extensions: devonfw.devonfw-extension-pack`

### Affected version:

* OS: Windows

**Comment by alfeilex** [comment]
I tried to use this command to get more information about the output: 
`code --verbose --install-extension devonfw.devonfw-extension-pack`

After installing some [extensionsPack packages](https://github.com/devonfw/extension-pack-vscode/blob/166aca69bea24f2838b654ef85690d76d9cd616b/package.json#L24) the output freeze with this last output:

```
TRACE [File Watcher (node.js)] [raw] ["rename"] .c36f2885-fdd8-4d92-947f-4a2faeecbbcd
TRACE [File Watcher (node.js)] [raw] ["rename"] devonfw.devonfw-extension-pack-5.7.0
 INFO Renamed to c:\Users\alfeil\.vscode\extensions\devonfw.devonfw-extension-pack-5.7.0
TRACE [File Watcher (node.js)] [raw] ["change"] devonfw.devonfw-extension-pack-5.7.0
TRACE [File Watcher (node.js)] [ADDED] c:\Users\alfeil\.vscode\extensions\devonfw.devonfw-extension-pack-5.7.0
 INFO Extracting completed. devonfw.devonfw-extension-pack
TRACE [File Watcher (node.js)] >> normalized [ADDED] c:\Users\alfeil\.vscode\extensions\.c36f2885-fdd8-4d92-947f-4a2faeecbbcd
TRACE [File Watcher (node.js)] >> normalized [ADDED] c:\Users\alfeil\.vscode\extensions\devonfw.devonfw-extension-pack-5.7.0
TRACE Started scanning system extensions
TRACE Started scanning user extensions
TRACE [File Watcher (node.js)] [DELETED] c:\Users\alfeil\.vscode\extensions\.c36f2885-fdd8-4d92-947f-4a2faeecbbcd
TRACE [File Watcher (node.js)] [CHANGED] c:\Users\alfeil\.vscode\extensions\devonfw.devonfw-extension-pack-5.7.0
TRACE [File Watcher (node.js)] >> normalized [DELETED] c:\Users\alfeil\.vscode\extensions\.c36f2885-fdd8-4d92-947f-4a2faeecbbcd
TRACE [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\alfeil\.vscode\extensions\devonfw.devonfw-extension-pack-5.7.0
TRACE Scanned system extensions: 89
TRACE Scanned user extensions: 79
```
It seems that the [devonfw.devonfw-extensions-pack](https://github.com/devonfw/extension-pack-vscode) is not terminating correctly. That is also caused the nightly tests to freeze after testing the `vscode` command.

**Comment by alfeilex** [comment]
It seems that there is no option to speed up the installation of the package. Therefore, we should perhaps remove the automatic installation of this package when installing `vscode`. 

@tobka777 suggested to use the "[Recommend](https://dev.to/askrishnapravin/recommend-vs-code-extensions-to-your-future-teammates-4gkb)" option to propose the installation to the user. I think that would be a great solution since this plugin install ~82 extensions.

If we use this option, then we should add `plugin-active=false` in the properties file. Otherwise, we can expand `integration-test-vscode` to add this so that the nightly tests runs to the end.

Depending on this, I can create an associated PR for it.

**Comment by hohwille** [comment]
See also issue #982

**Comment by hohwille** [comment]
See also https://github.com/devonfw/extension-pack-vscode/issues/12
