### ISSUE TITLE
predefine lombok plugin for intellij

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#897]
Issue #491 was implemented and closed but plugin for intellij is still not present:
https://github.com/devonfw/ide-settings/tree/master/intellij/plugins

> https://projectlombok.org/setup/intellij (intellij - see https://github.com/devonfw/ide/issues/453)

Also update this documentation when implementing this story:
https://github.com/devonfw/ide/blob/master/documentation/lombok.asciidoc#lombok-for-intellij

**Comment by pavanpuligandla** [comment]
We are unable to automatically load plugins on IntelliJ IDE 2021.2.3 while using Devon. Is there any official support for IntelliJ IDE as it has become more popular in java community? Please let us know

**Comment by hohwille** [comment]
> We are unable to automatically load plugins on IntelliJ IDE 2021.2.3 while using Devon. Is there any official support for IntelliJ IDE as it has become more popular in java community? Please let us know

@pavanpuligandla thanks for your interest in devonfw-ide and your feedback.
IMHO you want to report a new bug that is not related to this story. Can you create a new bug ticket for your problem?
Could you also provide more details ("we are unable to ..." does not give us a clue what you did and what happened).

**Comment by mustafaokyay** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IDE-61dbfc20045ead0022812582/issues/devonfw/ide/897?planning-poker) with Zenhub @alfeilex @Amueller36 @hohwille @tobka777 @CREITZ25 @cinnamon-coder-hub

**Comment by Ttring** [comment]
The official Lombok [https://projectlombok.org/setup/intellij](url) page states, "Jetbrains IntelliJ IDEA editor is compatible with Lombok without plugin as of version 2020.3. ". Would it be necessary to implement Lombok plugin in settings ?
