### ISSUE TITLE
Remove the hard-coded Eclipse plugins from eclipse commandlet

### ISSUE THREAD

**Issue by Akuhana** [devonfw/ide#904]
As a devonfw user, I want to change the update site in the properties file and see the changes reflect when executing the setup script of the Eclipse commandlet so that I don't need to update the hard coded lines every time plugins update_site or plugin_id needs to be updated. Changes have to be made to the following lines: https://github.com/devonfw/ide/blob/bb58f7996485e11398a0e4a2c82e0901f551214b/scripts/src/main/resources/scripts/command/eclipse#L174-L209

**Comment by Amueller36** [comment]
I think I included the fixes for this issues in my Pull request here: https://github.com/devonfw/ide/pull/952

I didn't see that this was an issue itself, sorry.
