### ISSUE TITLE
Docker command wrapper not working on Mac

### ISSUE THREAD

**Issue by sarahffm** [devonfw/ide#906]
### Expected behavior

As a devon IDE user, I want to use the command wrapper for docker without errors after installing Docker/Rancher Desktop on Mac.

### Actual behavior

There is an error after running `devon docker <<args>>`.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Install docker (`devon docker setup`).
2. Run any docker command, e.g. `devon docker -v`.

### Related/Dependent Issues

#690 

### Comments/Hints:

Parts of the error message:

![image](https://user-images.githubusercontent.com/58327878/192254174-bc1b9e9e-0ccc-45fd-91d2-a14eb39fb407.png)

### Affected version:

* OS: MacOS (Monterey 12.5, M1 Mac)

**Comment by CREITZ25** [comment]
Tested again and found no more errors
