### ISSUE TITLE
Available versions for IntelliJ

### ISSUE THREAD

**Issue by sarahffm** [devonfw/ide#916]
As a devon IDE user, I want to know which versions are available for IntelliJ so that I can easily switch versions.

The versions-url and versions-url-op in ide-mirrors are still missing for IntelliJ.
https://www.jetbrains.com/idea/download/other.html looks promising, but so far we haven't been able to extract all versions from the curl response.

Related Issue:
#826

**Comment by hohwille** [comment]
Community edition can be found here:
https://github.com/JetBrains/intellij-community
Starting point could be
https://api.github.com/repos/JetBrains/intellij-community/tags

**Comment by hohwille** [comment]
An alternative could be to establish a different mechanism:
We could easier figure out what the latest release is.
Our nightly workflow could get this latest release and if not at the top of `available-versions`, it would add it.
Besides with this approach we could:
* Before adding a new release, test the download using devonfw-ide. On success add and commit. On failure log the error and leave that `available-versions` unchanged.
* Allow manual corrections in `available-versions` as the existing entries would not be overwritten.
* Further in case of an error in the process, we would not cause much harm as then in the worst case the latest version(s) are missing and will be added the next run or have to be added manually...

A drawback of this approach is that if multiple new versions are published the same day, the approach will not work and manual intervention would be required.

**Comment by hohwille** [comment]
Besides for IntelliJ the versions are not a big surprise:
* 2022.2.3
* 2022.2.2
* 2022.2.1
* 2022.2
* 2022.1.4
* 2022.1.3
* 2022.1.2
* 2022.1.1
* 2022.1
* ...

**Comment by hohwille** [comment]
For the start, I created the file manually. I omitted versions from 2017 and before as IMHO nobody will use them anymore today.

**Comment by hohwille** [comment]
Due to #963 and #941 I can now close this as fixed. I had added the versions manually and we are about create a replacement for mirrors since the current workflow will not work stable and will be disabled anyhow.
