### ISSUE TITLE
Available versions for GitHub CLI

### ISSUE THREAD

**Issue by sarahffm** [devonfw/ide#917]
As a devon IDE user, I want to know which versions are available for GitHub CLI so that I can easily switch versions.

The versions-url and (if necessary) versions-url-op in ide-mirrors are missing for GitHub CLI (gh).

Related Issue:
#826

**Comment by tobka777** [comment]
@hohwille I think this is already done or is there an other related PR. See: https://github.com/devonfw/ide-mirrors/pull/36

**Comment by hohwille** [comment]
Closing as this is already done. We will do further improvements with #941
