### ISSUE TITLE
Improvement of available versions fetched from GitHub API

### ISSUE THREAD

**Issue by ahmedagdmoun** [devonfw/ide#918]
As a Devon IDE user, I want to list **all** available versions of a certain tool so that I can easily choose one of them or switch between different versions.
This was already implemented in #826, however as I was trying to add available versions for my newly integrated tool Quarkus CLI following the same approach, it turned out that the GitHub Search API returns only a limited set of data and thus only a limited number of versions can be fetched, so if there are too many versions, only a part is saved to the `available-versions` file and the rest are not.

Acceptance criteria:
All available versions are saved to the `available-versions` file in ide-mirrors.

**Comment by hohwille** [comment]
PR https://github.com/devonfw/ide-mirrors/pull/35 is still open.

**Comment by hohwille** [comment]
I will also merge this PR 35 so only one thing is left to do:
Centralize the following aspects currently implemented redundantly in multiple `versions-url-op` files into a single place in `get-versions`
* The filtering of unstable versions (e.g. `grep -i -Ev "cr|rc|beta|alpha|pre|dev|test"`)
* The sorting of the versions from newest down to oldest (`sort -V -r`)

**Comment by hohwille** [comment]
The github API will IMHO return much more data but still limits the resulting JSON.
Therefore we either need paging or we change the entire approach of #826 as discussed already in #916.
However, I will create a new issue for this idea so we can close this one and simplify understanding what is to be done.

**Comment by hohwille** [comment]
Created #941 hence closing this issue.
