### ISSUE TITLE
available-versions for java incomplete

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#931]
### Expected behavior

As a devonfw-ide user, I want to make use of the new version support including completion, etc. so that my life gets easier maintaining versions. Therefore `available-versions` should contain all stable versions of the according tool that are available.

### Actual behavior

For `java` the list is incomplete and older versions ( `8.*`) are missing.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Open https://github.com/devonfw/ide-mirrors/blob/master/java/available-versions

### Related/Dependent Issues

* #826

### Comments/Hints:

In [get-versions](https://github.com/devonfw/ide-mirrors/blob/master/get-versions#L56) there is a detection if the `available-versions` file is empty due to some `curl` error. However, for tools like `java` that have a [versions](https://github.com/devonfw/ide-mirrors/blob/master/java/versions) config using sub-folders, this would need to be checked for each individual `curl` download and not only for the aggregated result:
https://github.com/devonfw/ide-mirrors/blob/master/get-versions#L26

**Comment by alfeilex** [comment]
PR for this issue --> https://github.com/devonfw/ide-mirrors/pull/39

**Comment by hohwille** [comment]
Solved by @alfeilex with the linked PR. Thanks again 👍 
Hence closing this issue.
