### ISSUE TITLE
Consider extending test-functions-doc with invocation of undeclared functions

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#939]
As a devonfw-ide PO, I want automated tests on the code so that bugs are detected early.
Developing bash is tedious. Where other programming languages like Java or C# would raise compile errors, we get successful build and tests even though the code is obviously broken.

As we have a strict convention to name all functions following the pattern `do[A-Z][a-zA-Z]*` we could easily extend our `test-functions-doc` with a check that greps all such patterns from functions and for each unique of them (`sort -u`) check if has been declared.
Otherwise raise and error and break the build.

So if `functions` contains e.g. `doUndefinedFunction` but not `function doUndefinedFunction()` then the test should report that `doUndefinedFunction` is undefined and fail.

**Comment by mustafaokyay** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IDE-61dbfc20045ead0022812582/issues/devonfw/ide/939?planning-poker) with Zenhub @alfeilex @Amueller36 @cinnamon-coder-hub @CREITZ25 @hohwille @tobka777
