### ISSUE TITLE
Python failed in integration test on Windows

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#948]
Integration test on Windows failed last night:
https://github.com/devonfw/ide/actions/runs/3246832640/jobs/5326053484

```
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [6 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users
Error: min\AppData\Local\Temp\pip-install-ig23yzj3[ERROR] Command execution failed.
```

**Comment by alfeilex** [comment]
It's not possible to install configobj with `devon pip install configobj`

Output:
```
Collecting configobj
  Using cached configobj-5.0.6.tar.gz (33 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Schuryk\AppData\Local\Temp\pip-install-issp2x47\configobj_050893ee40f5442ebb27f65a37e8e7ab\setup.py", line 17, in <module>
          from _version import __version__
      ModuleNotFoundError: No module named '_version'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

The reason for this new error is that there is a new version of azure-cli that requires configobj.

**Comment by alfeilex** [comment]
Because I am stuck with this problem, I created an [issue](https://github.com/pypa/pip/issues/11526). Hopefully they can help us with this problem.

**Comment by alfeilex** [comment]
I was able to figure out that the problem caused by the package **configobj** itself. So I created a new issue [here](https://github.com/DiffSK/configobj/issues/219) to get help from the authors.

**Comment by hohwille** [comment]
Some aspects we might be able to learn whilst still struggling with proper python integration:
https://justinmayer.com/posts/homebrew-python-is-not-for-you/

**Comment by alfeilex** [comment]
Python currently works on Windows without errors. But for MacOS and Linux systems we need other approaches to integrate python into the ide. 

Therefore, this issue can be closed. The other OS's will be covered in this issue: #997

**Comment by hohwille** [comment]
I am closing this issue accordingly.
