### ISSUE TITLE
Support for MSI

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#978]
In `doExtract` (in `functions`) we should add support for MSI files that can be extracted.
https://github.com/devonfw/ide/blob/605aa475d5a0103ccc22f20525ecdb3d6876094f/scripts/src/main/resources/scripts/functions#L673
Also remove `msi` from here:
https://github.com/devonfw/ide/blob/605aa475d5a0103ccc22f20525ecdb3d6876094f/scripts/src/main/resources/scripts/functions#L747

@CREITZ25 already found out how to extract MSI files so this could be done easily.

After that we can revisit `aws` commandlet and see if we can switch to a local installation by extracting MSI.
Also #874 can afterwards be revisited.

However, the scope of this issue is only to create a PR that extends `doExtract` so `*.msi` files are automatically extracted.
If that breaks any existing behavior (will happen for `aws` and maybe for for `docker`), simply add `noUnpack` option to keep previous behavior.
Then after being merged, we can change commandlets (and mirrors/urls config) to use MSI.

**Comment by mustafaokyay** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IDE-61dbfc20045ead0022812582/issues/devonfw/ide/978?planning-poker) with Zenhub @alfeilex @Amueller36 @cinnamon-coder-hub @CREITZ25 @hohwille @tobka777

**Comment by CREITZ25** [comment]
This issue will be implemented together with #964 and #992

**Comment by CREITZ25** [comment]
How to see the configuration of a msi Archive:
https://learn.microsoft.com/en-us/windows/win32/msi/orca-exe
