### ISSUE TITLE
release workflow failing due to gpg issue

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#979]
I tested #813 for the first time to build a new release.
However, it does not work:

```
[INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ devonfw-ide-doc ---
gpg: signing failed: Inappropriate ioctl for device
gpg: signing failed: Inappropriate ioctl for device
```

We discussed exactly this problem.
See https://github.com/devonfw/maven-parent/issues/16

**Comment by hohwille** [comment]
See the logs here:
https://github.com/devonfw/ide/actions/runs/3465131187/jobs/5787502635

Also notice that https://issues.apache.org/jira/browse/MNG-7338 was not addressed.

**Comment by hohwille** [comment]
I quickly fixed the log spam issue but regarding gpg all seems fine and I can not figure out what is wrong.
The parent was properly updated to version 11:
https://github.com/devonfw/ide/blob/d72d893239cacf7b67b233b2b18880511ffe9c26/pom.xml#L9

This is the version I released after [commiting the fix](https://github.com/devonfw/maven-parent/commit/f4bbbf53f73902b7aaa7d179db41b97da63d6763) for devonfw/maven-parent#16

Also the property is correctly set in the workflow:
https://github.com/devonfw/ide/blob/d72d893239cacf7b67b233b2b18880511ffe9c26/.github/workflows/release.yml#L39

**Comment by hohwille** [comment]
I found [this](https://github.com/keybase/keybase-issues/issues/2798)
and tried to fix it this way.
Now I am getting the next error:
```
gpg: signing failed: No such file or directory
```

I found these one on it:
* https://unix.stackexchange.com/questions/714824/gpg-signing-failed-no-such-file-or-directory
* https://unix.stackexchange.com/questions/608842/zshrc-export-gpg-tty-tty-says-not-a-tty

**Comment by hohwille** [comment]
So I am giving up again on this. Automation is great but only if it works.
Going back to build the release locally on my machine where I know how to make it work.

**Comment by hohwille** [comment]
The changes that have been made for #813 now also broke the local release build due to `nexus-staging-maven-plugin:1.6.13:deploy` that has not been added only to the github workflow but for general deployment.
However, I now triggered many autostaged deployments and always the doc artifact remains in nexus but all other artifacts of the release are missing.
IMHO `nexus-staging-maven-plugin` is somehow buggy.
I will have to give up for today but my time is running out as I need to prepare a training that requires this release... What a pity...

**Comment by hohwille** [comment]
Besides, I found out that the `documentation/pom.xml` is not inheriting from `maven-parent` version `11` but version `9`.
See [here](https://repo1.maven.org/maven2/com/devonfw/tools/devonfw-docgen/2021.12.002/devonfw-docgen-2021.12.002.pom). Also applies to the [latest version](https://repo1.maven.org/maven2/com/devonfw/tools/devonfw-docgen/2021.12.004/devonfw-docgen-2021.12.004.pom).

Further the `nexus-staging-maven-plugin` is added to our devonfw-ide toplevel `pom.xml` but as `documentation/pom.xml` is not inheriting from there, it does not have this plugin.

As a result the other modules are automatically published to maven central except `devonfw-ide-doc` that needs to be closed and released manually in OSSRH.

It seems we have to update `maven-parent` and `docgen` once more to solve this.

**Comment by alfeilex** [comment]
After some time I was finally able to reproduce the bug in my own release process. With some changes I was able to fix the errors and deploy the release to my own repository. 

The problem is probably, as mentioned by @hohwille, with the `documentation/pom.xml`. This is the only element in the build that can't be deployed and breaks the whole release process. If you remove the documentation module from `pom.xml` you will see that the release works and there are no errors like `gpg: signing failed: Inappropriate ioctl for device`.

https://github.com/devonfw/ide/blob/master/pom.xml#L39

[Here](https://github.com/devonfw/ide/compare/master...alfeilex:ide:functional-release?expand=1#) is the branch comparing to the `upstream/master`. In this branch the automate release is working without errors.

**Comment by hohwille** [comment]
For the next release we can give it another try as the gpg issue should be resolved now.
My assumption is that it works but the documentation still needs manual staging (hanging in s01.oss.sonatype.org until I click close and release) while the rest automatically gets staged to maven central.

I could do additional improvements to `maven-parent` to better centralize also `nexus-staging-maven-plugin` and its version + config, what will require yet another release of maven-parent, docgen and finally devonfw-ide to finally get everything perfect.

**Comment by hohwille** [comment]
The workflow did now pass this problem so this issue can be closed as fixed.
However, the workflow still failed so I created #1057.
