### ISSUE TITLE
Settings for intellij are not getting updated in existing workspaces

### ISSUE THREAD

**Issue by ssarmokadam** [devonfw/ide#988]
### Expected behavior

As a user, I want to update my intellij settings in existing workspaces of devonfw-ide.(if .idea folder already exists in workspace)
For Example:  I have updated settings of intellij related with codestyles. I have defined rule like import statement in class should not allow *. This setting should be applicable across all workspace new or already existing workspaces.

### Actual behavior
on execution of devon ide update command, changes in intellij setting folder are getting pulled successfully. Those changes are reflected in new workspaces created after this update but are not visible in already existing workspaces.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Complete devonfw-ide setup.
2. Launch intellij on main workspace using devon intellij command
3. Open settings-> Editor->code style -> java -> imports
4. Change as highlighted in below image

![ide-import](https://user-images.githubusercontent.com/16591200/202675456-399553f2-dd07-4df3-9381-bb92ef73ff64.jpg)

5. Commit changes in git repo of settings.
6. Execute devon ide update. 
7. Launch intellij in already existing workspace where this changes were not configured already.

### Comments/Hints:
If **.idea** folder already exists in workspace this changes are not getting reflected on launch. After execution of **devon intellij ws-up** this changes will be reflected.

### Affected version:

* OS: Windows/Linux/Mac? Windows
* Ide version : 2022.08.003
* Browser: Chrome/Firefox/Safari?

**Comment by Ttring** [comment]
Further explanations to this issue. 

- After all changes to codeStyle are made in Intellij, the changes appear in ide>Settings>Intelij>Workspace>Setup>.idea. For example, a new folder named "codeStyle" will appear in the .idea folder.



- However, the changes are not reflected in ide>Workspaces (If .idea folder already exists in workspace this changes are not getting reflected on launch.)


- The administrator then commits the changes to the branch.


- The team members are informed about the changes.


- The team members run "devon ide update" using the URL settings, but the changes are not displayed.

**Comment by hohwille** [comment]
Documentation:
https://github.com/devonfw/ide/blob/master/documentation/configurator.asciidoc#how-it-works

Were the "changes" placed in the `setup` folder in `settings` repo? If yes, then the behavior is as designed and no bug - all you need to do is to move your changes to `update` folder.
